import { HW, annotated, compare, examples, fill, list, match, mc, ms, mist, order, passage, sa, structure, table, text, tf, tip, vocab, type SeedLesson } from "./dsl";

// Beginner course, Teaching Weeks 3-5 (Units 5-8). Topics follow the academy's syllabus; all text is ORIGINAL.

const KARIM = "Hi, I'm Karim. I live in Nizwa. I like sport, and I like music. I play football on Fridays with my friends. We don't play on Mondays because we have school. I don't like cold weather, but I like hot summers. I speak Arabic and English. I don't speak French. Do you like football?";
const BUS_DRIVER = "Salim is a bus driver in Muscat. He gets up at 5:00. He has breakfast at 5:30, and he starts work at 6:30. He drives a bus all morning. At 12:00 he has lunch. He finishes work at 3:00. In the evening he watches TV, and he goes to bed at 9:30. Salim never works on Fridays.";
const SALALAH_EMAIL = "Hi Mum,\n\nI'm in Salalah! It's a beautiful city. There is a big beach near my hotel, and there are two small shops next to the hotel. My room is small, but it's nice. There isn't a TV, but there is a balcony. I can see the sea from the balcony.\n\nLove,\nNora";
const MY_CITY = "My favourite city is Muscat. It is a beautiful city. There are many parks and a big market. There is a beach next to the city, and there are some old forts. The people are very friendly. I like Muscat because it is quiet, and the food is cheap.";

export const BEGINNER_W3_W5: SeedLesson[] = [
  // ============================================================ WEEK 3
  {
    slug: "beginner-grammar-present-simple-negative-questions",
    level: "BEGINNER", category: "GRAMMAR", title: "Present Simple: don't and Do you …?", topic: "Present Simple",
    difficulty: "BASIC", minutes: 10, prereq: ["beginner-grammar-present-simple"],
    objective: "Make negatives and questions with I, you, we and they in the Present Simple.",
    tags: ["grammar", "present-simple", "negatives", "questions", "likes-dislikes", "A1"],
    ref: { book: HW, level: "Beginner", area: "Grammar", topic: "Present Simple: I / you / we / they (Unit 5)" },
    sections: [
      text("With **I, you, we** and **they**, use **don't** for negatives and **Do** for questions. The verb stays in its **base form**.", "Explanation"),
      table("Present Simple with I / you / we / they", ["Type", "Form", "Example"], [
        ["Positive", "subject + verb", "I like tea. They play football."],
        ["Negative", "subject + don't + verb", "I don't like coffee. We don't work on Fridays."],
        ["Question", "Do + subject + verb?", "Do you like sport? Do they play football?"],
        ["Short answers", "Yes, I do. / No, I don't.", "Do you like tea? — Yes, I do."],
      ]),
      structure("Structure", "I / you / we / they + don't + verb\nDo + I / you / we / they + verb?", "Do not add -s to the verb: I don't like (not I don't likes)."),
      examples("Examples", { "": ["I like music. I don't like cold weather.", "Do you speak English? — Yes, I do.", "We don't play on Mondays."] }),
    ],
    exercises: [
      fill("I ___ like coffee. (negative)", ["don't"], "I don't like coffee."),
      fill("___ you like football? Yes, I ___.", ["Do", "do"], "Do you like…? Yes, I do."),
      mist("Find the mistake.", ["We", "doesn't", "play on Mondays."], 1, "don't", "We → don't."),
      mc("They ___ speak French.", ["don't", "doesn't", "isn't"], 0, "They → don't."),
      order("Put the words in the correct order.", ["Do", "you", "like", "music?"], "word", "Do + subject + verb?"),
      sa("Give a short answer: “Do you like tea?” (No) — No, ___.", ["I don't", "I do not"], "No, I don't.", { hint: "two words" }),
    ],
  },
  {
    slug: "beginner-vocab-sports-free-time",
    level: "BEGINNER", category: "VOCABULARY", title: "Sports and Free Time", topic: "Free time",
    difficulty: "BASIC", minutes: 8, prereq: ["beginner-vocab-food-drink"],
    objective: "Name common sports and free-time activities and say what you like.",
    tags: ["vocabulary", "sports", "free-time", "likes-dislikes", "listening-support", "A1"],
    ref: { book: HW, level: "Beginner", area: "Vocabulary", topic: "Sports and free time (Unit 5)" },
    sections: [
      text("Use **play** with sports and games (play football) and **listen to** with music. You can say **I like…** and **I don't like…**."),
      vocab([
        { word: "football", pos: "noun", meaning: "a game with a ball and two teams", ar: "كرة القدم", pron: "/ˈfʊtbɔːl/", ex: "I play football on Fridays.", col: ["play football"], visual: "⚽" },
        { word: "tennis", pos: "noun", meaning: "a game with rackets and a ball", ar: "التنس", pron: "/ˈtenɪs/", ex: "She plays tennis.", col: ["play tennis"], visual: "🎾" },
        { word: "swimming", pos: "noun", meaning: "moving in water", ar: "السباحة", pron: "/ˈswɪmɪŋ/", ex: "I like swimming.", col: ["go swimming"], visual: "🏊" },
        { word: "music", pos: "noun", meaning: "sounds from songs", ar: "الموسيقى", pron: "/ˈmjuːzɪk/", ex: "We listen to music.", col: ["listen to music"], right: "I listen to music.", wrong: "I listen music.", note: "Listen needs to.", visual: "🎧" },
        { word: "reading", pos: "noun", meaning: "looking at words and understanding them", ar: "القراءة", pron: "/ˈriːdɪŋ/", ex: "I like reading books.", col: ["read a book"], visual: "📖" },
      ], "Free-time words"),
    ],
    exercises: [
      match("Match the verb with the activity.", [["play", "football"], ["listen to", "music"], ["go", "swimming"], ["read", "a book"]], "play + sport; listen to + music; go + -ing."),
      mc("I ___ tennis on Saturdays.", ["play", "listen", "read"], 0, "play tennis."),
      fill("I listen ___ music every day.", ["to"], "listen to music."),
      mist("Find the mistake.", ["We", "listen", "music every day."], 1, "listen to", "Listen needs to."),
      sa("A game with a ball and two teams: ___", ["football"], "football.", { hint: "f _ _ _ _ _ _ l" }),
      order("Put the words in the correct order.", ["I", "don't", "like", "tennis."], "word", "Subject + don't + like + noun."),
    ],
  },
  {
    slug: "beginner-vocab-languages-nationalities",
    level: "BEGINNER", category: "VOCABULARY", title: "Languages and Nationalities", topic: "Nationalities",
    difficulty: "BASIC", minutes: 8, prereq: ["beginner-vocab-countries-cities"],
    objective: "Say the nationality and language for common countries.",
    tags: ["vocabulary", "nationalities", "languages", "personal-information", "A1"],
    ref: { book: HW, level: "Beginner", area: "Vocabulary", topic: "Nationalities and languages (Unit 5)" },
    sections: [
      text("A **nationality** tells us where a person is from (Omani, Egyptian). Nationalities and languages start with a **capital letter**. Use **speak** for languages: I **speak** Arabic."),
      table("Countries, nationalities and languages", ["Country", "Nationality", "Language"], [
        ["Oman", "Omani", "Arabic"], ["Egypt", "Egyptian", "Arabic"], ["Spain", "Spanish", "Spanish"], ["France", "French", "French"], ["Japan", "Japanese", "Japanese"], ["India", "Indian", "Hindi / English"], ["England", "English", "English"],
      ]),
      structure("Structure", "I am + nationality.   I speak + language.", "Nationality and language often have the same word: I am Spanish. I speak Spanish."),
    ],
    exercises: [
      match("Country → nationality.", [["Oman", "Omani"], ["Egypt", "Egyptian"], ["Japan", "Japanese"], ["Spain", "Spanish"], ["France", "French"]], "Learn the endings."),
      fill("She is from Japan. She speaks ___.", ["Japanese"], "Japan → Japanese."),
      mist("Find the mistake.", ["He is", "omani", "."], 1, "Omani", "Nationalities start with a capital letter."),
      mc("I ___ Arabic and English.", ["speak", "say", "am"], 0, "We speak a language."),
      sa("A person from Egypt is ___.", ["Egyptian"], "Egypt → Egyptian.", { hint: "E _ _ _ _ _ _ n" }),
      order("Put the words in the correct order.", ["I", "speak", "Arabic", "and", "English."], "word", "Subject + speak + language."),
    ],
  },
  {
    slug: "beginner-reading-karims-life",
    level: "BEGINNER", category: "READING", title: "Reading: Karim's Life", topic: "Likes and habits",
    difficulty: "BASIC", minutes: 10, prereq: ["beginner-reading-e-pal"],
    objective: "Read a short text about likes and habits and find true and false information.",
    tags: ["reading", "reading-details", "likes-dislikes", "true-false", "A1"],
    ref: { book: HW, level: "Beginner", area: "Reading", topic: "A student's life (Unit 5)" },
    sections: [
      text("This text uses **I like**, **I don't like** and **I play**. To decide if a sentence is **true or false**, find the same information in the text.", "Reading strategy"),
      passage("Example", "I'm Sami. I live in Sohar. I like tea, but I don't like coffee. I play tennis on Saturdays.", "A short text"),
      list("Guided practice", ["Does Sami like coffee? → No.", "When does he play tennis? → on Saturdays."]),
    ],
    exercises: [
      mc("Where does Karim live?", ["in Nizwa", "in Muscat", "in Sur"], 0, "“I live in Nizwa.”", KARIM),
      mc("When does Karim play football?", ["on Fridays", "on Mondays", "on Sundays"], 0, "“I play football on Fridays.”", KARIM),
      tf("Karim plays football on Mondays.", false, "“We don't play on Mondays because we have school.”", KARIM),
      tf("Karim likes hot summers.", true, "“I like hot summers.”", KARIM),
      mc("Which language does Karim NOT speak?", ["Arabic", "English", "French"], 2, "“I don't speak French.”", KARIM),
      mc("Why don't they play on Mondays?", ["They have school.", "It is cold.", "They don't like football."], 0, "“because we have school”.", KARIM),
    ],
  },
  {
    slug: "beginner-writing-table-to-paragraph-1",
    level: "BEGINNER", category: "WRITING", title: "Writing Workshop 1: From a Table to a 50-Word Paragraph", topic: "Table-to-paragraph",
    difficulty: "BASIC", minutes: 14, prereq: ["beginner-writing-table-to-sentences", "beginner-writing-and-but"],
    objective: "Turn a student profile table into a paragraph of about 50 words, using and and but.",
    tags: ["writing", "table-to-paragraph", "conjunctions", "likes-dislikes", "A1"],
    ref: { book: HW, level: "Beginner", area: "Writing", topic: "Paragraph from table information, ~50 words (Unit 5)" },
    sections: [
      text("In **Task A** of the writing exam, you get a **table** and write a **paragraph of about 50 words**. Use **he / she / they** instead of the name, the correct **verb form**, and the linkers **and** and **but**.", "Explanation"),
      table("The table", ["Name", "Country", "Job", "Languages", "Likes", "Doesn't like"], [["Nora", "Oman", "student", "Arabic, English", "tea, football", "cold weather"]]),
      annotated("Table → paragraph (about 50 words)", [
        ["Who", "Nora is from Oman. She is a student."],
        ["Languages", "She speaks Arabic and English."],
        ["Likes", "She likes tea and football, but she doesn't like cold weather."],
      ]),
      list("Steps", ["1. Write the name and country.", "2. Use she / he for the job and the languages.", "3. Join ideas with and.", "4. Use but for the difference (likes / doesn't like).", "5. Check: capital letters, full stops, verb -s with he / she."]),
      tip("Use the verb -s with he and she: She likes, She speaks. With they: They like, They speak.", "Grammar check"),
    ],
    exercises: [
      order("Put the sentences in the correct order.", ["Nora is from Oman.", "She is a student.", "She speaks Arabic and English.", "She likes tea and football, but she doesn't like cold weather."], "paragraph", "Country, job, languages, likes and dislikes."),
      fill("Nora likes tea ___ football.", ["and"], "and joins two things she likes."),
      fill("She likes tea, ___ she doesn't like coffee.", ["but"], "but shows the difference."),
      mist("Find the mistake.", ["Nora is a student.", "She speak", "Arabic and English."], 1, "speaks", "She → speaks."),
      mc("Table: Omar · Egypt · driver · Arabic · likes: music · doesn't like: fish. Which sentence is correct?", ["He likes music, but he doesn't like fish.", "He like music, but he doesn't likes fish.", "Omar likes music but him not like fish."], 0, "He likes …, but he doesn't like …"),
      order("Put the words in the correct order.", ["She", "likes", "tea", "and", "football."], "word", "Subject + likes + noun + and + noun."),
    ],
  },

  // ============================================================ WEEK 4
  {
    slug: "beginner-grammar-adverbs-of-frequency",
    level: "BEGINNER", category: "GRAMMAR", title: "always, sometimes, never", topic: "Adverbs of frequency",
    difficulty: "BASIC", minutes: 8, prereq: ["beginner-grammar-present-simple-negative-questions"],
    objective: "Say how often you do things with always, usually, sometimes and never.",
    tags: ["grammar", "adverbs-of-frequency", "daily-routines", "A1"],
    ref: { book: HW, level: "Beginner", area: "Grammar", topic: "Adverbs of frequency (Unit 6)" },
    sections: [
      text("**Adverbs of frequency** say **how often**. They go **before the main verb**: I **always** walk to school. They go **after the verb be**: He is **never** late.", "Explanation"),
      table("How often?", ["Adverb", "How often", "Example"], [
        ["always", "100%", "I always drink tea."], ["usually", "about 80%", "She usually gets up at six."], ["sometimes", "about 40%", "We sometimes eat out."], ["never", "0%", "He never works on Friday."],
      ]),
      structure("Structure", "subject + adverb + verb\nsubject + am / is / are + adverb", "Never is already negative: I never eat fish (not I don't never eat)."),
    ],
    exercises: [
      order("Put the words in the correct order.", ["I", "always", "drink", "tea."], "word", "Adverb before the main verb."),
      order("Put the words in the correct order.", ["He", "is", "never", "late."], "word", "After the verb be."),
      fill("She ___ works on Friday. She is always at home. (never)", ["never"], "Never = 0%."),
      mist("Find the mistake.", ["My dog", "always is", "hungry."], 1, "is always", "After the verb be."),
      match("Match the adverb with its meaning.", [["always", "every time"], ["sometimes", "not every time"], ["never", "no times"]], "The scale goes from always to never."),
      mc("Which is correct?", ["I sometimes play tennis.", "I play sometimes tennis.", "Sometimes I plays tennis."], 0, "Adverb before the verb."),
    ],
  },
  {
    slug: "beginner-grammar-does-doesnt",
    level: "BEGINNER", category: "GRAMMAR", title: "he / she / it: does and doesn't", topic: "Present Simple",
    difficulty: "BASIC", minutes: 10, prereq: ["beginner-grammar-adverbs-of-frequency"],
    objective: "Make questions and negatives with he, she and it using does and doesn't.",
    tags: ["grammar", "present-simple", "third-person", "questions", "negatives", "A1"],
    ref: { book: HW, level: "Beginner", area: "Grammar", topic: "does / doesn't (Unit 6)" },
    sections: [
      text("With **he, she, it**, use **doesn't** for negatives and **Does** for questions. The main verb has **no -s**.", "Explanation"),
      table("he / she / it", ["Type", "Form", "Example"], [
        ["Positive", "verb + s", "She works in a bank."],
        ["Negative", "doesn't + verb", "She doesn't work on Friday."],
        ["Question", "Does + subject + verb?", "Does he play tennis?"],
        ["Short answers", "Yes, he does. / No, she doesn't.", "Does she like tea? — Yes, she does."],
      ]),
      structure("Structure", "he / she / it + doesn't + base verb\nDoes + he / she / it + base verb?", "Only ONE verb takes -s: She works. She doesn't work. Does she work?"),
    ],
    exercises: [
      fill("She ___ like coffee. (negative)", ["doesn't"], "She doesn't like coffee."),
      fill("___ he play tennis? Yes, he ___.", ["Does", "does"], "Does he…? Yes, he does."),
      mist("Find the mistake.", ["He", "doesn't likes", "fish."], 1, "doesn't like", "After doesn't, no -s."),
      mist("Find the mistake.", ["Do", "she", "work in a bank?"], 0, "Does", "She takes Does."),
      order("Put the words in the correct order.", ["Does", "she", "live", "in", "Muscat?"], "word", "Does + subject + verb."),
      sa("Give a short answer: “Does he work on Friday?” (No) — No, he ___.", ["doesn't", "does not"], "No, he doesn't.", { hint: "one word" }),
    ],
  },
  {
    slug: "beginner-vocab-daily-routine-verbs",
    level: "BEGINNER", category: "VOCABULARY", title: "Daily Routine Verbs", topic: "Daily routines",
    difficulty: "BASIC", minutes: 8, prereq: ["beginner-vocab-sports-free-time"],
    objective: "Use common daily-routine phrases: get up, go to work, have lunch.",
    tags: ["vocabulary", "daily-routines", "collocations", "listening-support", "A1"],
    ref: { book: HW, level: "Beginner", area: "Vocabulary", topic: "Daily routine collocations (Unit 6)" },
    sections: [
      text("Words that **go together** are called **collocations**. For a daily routine, learn the whole phrase: **get up**, **have breakfast**, **go to work**."),
      vocab([
        { word: "get up", pos: "phrase", meaning: "leave your bed", ar: "يستيقظ", pron: "/ɡet ʌp/", ex: "I get up at six.", col: ["get up early"], visual: "⏰" },
        { word: "have breakfast", pos: "phrase", meaning: "eat in the morning", ar: "يتناول الفطور", pron: "/hæv ˈbrekfəst/", ex: "We have breakfast at seven.", col: ["have lunch", "have dinner"], right: "have breakfast", wrong: "eat the breakfast", note: "Say have breakfast / lunch / dinner.", visual: "🍳" },
        { word: "go to work", pos: "phrase", meaning: "travel to your job", ar: "يذهب إلى العمل", pron: "/ɡəʊ tə wɜːk/", ex: "He goes to work by bus.", col: ["go to school"], visual: "🚌" },
        { word: "finish work", pos: "phrase", meaning: "stop working", ar: "ينهي العمل", pron: "/ˈfɪnɪʃ wɜːk/", ex: "She finishes work at four.", col: ["finish school"], visual: "🏁" },
        { word: "go to bed", pos: "phrase", meaning: "go to sleep", ar: "يذهب إلى النوم", pron: "/ɡəʊ tə bed/", ex: "I go to bed at ten.", col: ["go to bed late"], visual: "🛏️" },
      ], "Routine phrases"),
    ],
    exercises: [
      order("Put the routine in order.", ["get up", "have breakfast", "go to work", "have lunch", "go to bed"], "word", "A normal day."),
      match("Match the words that go together.", [["have", "breakfast"], ["go to", "work"], ["get", "up"], ["go to", "bed"]], "These phrases go together."),
      fill("I ___ breakfast at seven.", ["have"], "have breakfast."),
      mist("Find the mistake.", ["He", "eats the breakfast", "at seven."], 1, "has breakfast", "Say have breakfast."),
      mc("She ___ work at four o'clock.", ["finishes", "finish", "finishing"], 0, "She takes finishes."),
      sa("You sleep in a ___. (a piece of furniture)", ["bed"], "You sleep in a bed.", { hint: "b _ d" }),
    ],
  },
  {
    slug: "beginner-vocab-days-prepositions-of-time",
    level: "BEGINNER", category: "VOCABULARY", title: "Days of the Week and Prepositions of Time", topic: "Time",
    difficulty: "BASIC", minutes: 10, prereq: ["beginner-vocab-daily-routine-verbs"],
    objective: "Say the days of the week and use at, on and in with time.",
    tags: ["vocabulary", "days", "prepositions", "time", "A1"],
    ref: { book: HW, level: "Beginner", area: "Vocabulary", topic: "Days; prepositions of time (Unit 6)" },
    sections: [
      text("The days of the week always start with a **capital letter**: Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday. To say **when**, use **at**, **on** or **in**."),
      table("at, on, in", ["Preposition", "Use with", "Examples"], [
        ["at", "clock times", "at 8:00 · at half past six"], ["on", "days", "on Monday · on Fridays"], ["in", "parts of the day", "in the morning · in the afternoon · in the evening"],
      ]),
      tip("We say at night, but in the morning / afternoon / evening.", "Watch out"),
    ],
    exercises: [
      fill("I get up ___ 6:00.", ["at"], "at + time."),
      fill("We play football ___ Fridays.", ["on"], "on + day."),
      fill("She studies ___ the evening.", ["in"], "in + part of the day."),
      mist("Find the mistake.", ["The class starts", "in Monday", "."], 1, "on Monday", "Days take on."),
      order("Put the days in order.", ["Sunday", "Monday", "Tuesday", "Wednesday"], "word", "Sunday is the first day here."),
      match("in, on or at?", [["7:30", "at"], ["Tuesday", "on"], ["the morning", "in"], ["night", "at"]], "at + time; on + day; in + part of day."),
    ],
  },
  {
    slug: "beginner-reading-bus-driver-day",
    level: "BEGINNER", category: "READING", title: "Reading: A Day in the Life of a Bus Driver", topic: "Times and routines",
    difficulty: "BASIC", minutes: 10, prereq: ["beginner-reading-karims-life"],
    objective: "Find times and activities in a text about someone's day.",
    tags: ["reading", "reading-scanning", "daily-routines", "time", "A1"],
    ref: { book: HW, level: "Beginner", area: "Reading", topic: "A day in the life (Unit 6)" },
    sections: [
      text("A text about a day gives **times** and **activities** in order. **Scan** for times (5:00, 6:30) and read the verb next to them.", "Reading strategy"),
      passage("Example", "Huda is a nurse. She gets up at 5:30. She starts work at 7:00. She finishes at 3:00.", "A short routine"),
      list("Guided practice", ["When does she get up? → 5:30.", "When does she start work? → 7:00."]),
    ],
    exercises: [
      mc("What time does Salim get up?", ["5:00", "5:30", "6:30"], 0, "“He gets up at 5:00.”", BUS_DRIVER),
      mc("What time does he start work?", ["5:30", "6:30", "12:00"], 1, "“he starts work at 6:30”.", BUS_DRIVER),
      mc("What does he do at 12:00?", ["He has lunch.", "He goes to bed.", "He finishes work."], 0, "“At 12:00 he has lunch.”", BUS_DRIVER),
      sa("What time does he finish work? (write the time)", ["3:00", "3", "three"], "“He finishes work at 3:00.”", { context: BUS_DRIVER }),
      mc("When does Salim never work?", ["on Fridays", "on Mondays", "in the evening"], 0, "“Salim never works on Fridays.”", BUS_DRIVER),
      tf("Salim goes to bed at 9:30.", true, "“he goes to bed at 9:30”.", BUS_DRIVER),
    ],
  },
  {
    slug: "beginner-writing-timetable-to-paragraph",
    level: "BEGINNER", category: "WRITING", title: "From a Timetable to a Paragraph: A Day in the Life", topic: "Timetable-to-paragraph",
    difficulty: "BASIC", minutes: 14, prereq: ["beginner-writing-table-to-paragraph-1", "beginner-vocab-days-prepositions-of-time"],
    objective: "Change a daily timetable into a paragraph of about 50 words in time order.",
    tags: ["writing", "table-to-paragraph", "daily-routines", "time-order", "A1"],
    ref: { book: HW, level: "Beginner", area: "Writing", topic: "Timetable-to-paragraph (Unit 6)" },
    sections: [
      text("A **timetable** shows **times and activities**. To write a paragraph, keep the **same order**, use **at + time**, and add **linking words**: **then**, **after that**, **in the evening**.", "Explanation"),
      table("Layla's timetable", ["Time", "Activity"], [["6:30", "get up"], ["7:00", "have breakfast"], ["8:00", "go to school"], ["1:30", "have lunch"], ["4:00", "play football"], ["9:00", "go to bed"]]),
      annotated("Timetable → paragraph", [
        ["Morning", "Layla gets up at 6:30. She has breakfast at 7:00, and she goes to school at 8:00."],
        ["Afternoon", "She has lunch at 1:30. Then she plays football at 4:00."],
        ["Evening", "She goes to bed at 9:00."],
      ]),
      tip("Use the -s / -es form with she / he: gets up, has, goes, plays.", "Grammar check"),
    ],
    exercises: [
      order("Put the sentences in the correct order.", ["Layla gets up at 6:30.", "She has breakfast at 7:00.", "She goes to school at 8:00.", "She goes to bed at 9:00."], "paragraph", "Follow the timetable order."),
      fill("Layla ___ (get) up at 6:30 and ___ (have) breakfast at 7:00.", ["gets", "has"], "She → gets, has."),
      fill("She has lunch ___ 1:30. ___ she plays football.", ["at", "Then"], "at + time; Then = next."),
      mist("Find the mistake.", ["Layla", "go", "to school at 8:00."], 1, "goes", "She → goes."),
      order("Put the words in the correct order.", ["She", "goes", "to", "bed", "at", "9:00."], "word", "Subject + goes + to bed + at + time."),
      mc("Which word joins two events in time order?", ["Then", "But", "Because"], 0, "Then = next."),
    ],
  },

  // ============================================================ WEEK 5
  {
    slug: "beginner-grammar-question-words-why-how-many-much",
    level: "BEGINNER", category: "GRAMMAR", title: "Why, How many and How much", topic: "Question words",
    difficulty: "BASIC", minutes: 8, prereq: ["beginner-grammar-does-doesnt"],
    objective: "Ask about reasons, numbers and prices with Why, How many and How much.",
    tags: ["grammar", "question-words", "questions", "A1"],
    ref: { book: HW, level: "Beginner", area: "Grammar", topic: "Why, How many, How much (Unit 7)" },
    sections: [
      text("**Why** asks for a **reason** (answer with **Because**). **How many** asks about a **number** of countable things. **How much** asks about **price** or an amount of an uncountable thing.", "Explanation"),
      table("Question words", ["Word", "Asks about", "Example"], [
        ["Why", "reason", "Why are you late? — Because the bus is late."],
        ["How many", "number (plural nouns)", "How many books are there? — There are ten."],
        ["How much", "price / amount", "How much is this bag? — It's five rials."],
      ]),
      structure("Structure", "How many + plural noun + are there?\nHow much + is / are + noun?", "How much milk? (uncountable) · How many eggs? (countable)"),
    ],
    exercises: [
      fill("___ are you happy? Because it's Friday.", ["Why"], "Why asks for a reason."),
      fill("How ___ books do you have?", ["many"], "Books are countable: how many."),
      fill("How ___ is this pen? It's one rial.", ["much"], "Price: how much."),
      mc("“Why do you like Muscat?” “___ it is beautiful.”", ["Because", "So", "But"], 0, "A reason: Because."),
      order("Put the words in the correct order.", ["How", "many", "children", "have", "you", "got?"], "word", "How many + noun + have you got?"),
      match("Which question word?", [["a reason", "Why"], ["a number", "How many"], ["a price", "How much"]], "Choose by meaning."),
    ],
  },
  {
    slug: "beginner-grammar-object-pronouns",
    level: "BEGINNER", category: "GRAMMAR", title: "Object Pronouns: me, him, her, it, us, them", topic: "Pronouns",
    difficulty: "BASIC", minutes: 8, prereq: ["beginner-grammar-question-words-why-how-many-much"],
    objective: "Use object pronouns after verbs and prepositions.",
    tags: ["grammar", "pronouns", "object-pronouns", "A1"],
    ref: { book: HW, level: "Beginner", area: "Grammar", topic: "Object pronouns (Unit 7)" },
    sections: [
      text("Use **object pronouns** **after a verb** or **after a preposition** (with, for, to). They replace the noun: I like **her**. Come with **us**.", "Explanation"),
      table("Subject and object pronouns", ["Subject", "Object"], [["I", "me"], ["you", "you"], ["he", "him"], ["she", "her"], ["it", "it"], ["we", "us"], ["they", "them"]]),
      structure("Structure", "subject + verb + object pronoun\nI like him. She calls us.", "Not: I like he. Say: I like him."),
    ],
    exercises: [
      match("Subject → object.", [["he", "him"], ["she", "her"], ["we", "us"], ["they", "them"], ["I", "me"]], "The pronoun changes after a verb."),
      fill("Sara is my friend. I like ___.", ["her"], "After like: her."),
      fill("Ali and Omar are here. Call ___.", ["them"], "They → them."),
      mist("Find the mistake.", ["I like", "he", "very much."], 1, "him", "After a verb: him."),
      mc("Come with ___!", ["we", "us", "our"], 1, "After with: us."),
      order("Put the words in the correct order.", ["She", "likes", "them", "a", "lot."], "word", "Subject + likes + them."),
    ],
  },
  {
    slug: "beginner-grammar-this-that",
    level: "BEGINNER", category: "GRAMMAR", title: "this and that", topic: "Demonstratives",
    difficulty: "BASIC", minutes: 6, prereq: ["beginner-grammar-object-pronouns"],
    objective: "Use this for things near you and that for things far from you.",
    tags: ["grammar", "demonstratives", "A1"],
    ref: { book: HW, level: "Beginner", area: "Grammar", topic: "this / that (Unit 7)" },
    sections: [
      text("Use **this** for a thing that is **near** you. Use **that** for a thing that is **far** from you. For more than one, use **these** (near) and **those** (far).", "Explanation"),
      table("this and that", ["Feature", "Near", "Far"], [["One", "this", "that"], ["More than one", "these", "those"]]),
      examples("Examples", { "": ["This is my bag. (in my hand)", "That is my school. (over there)", "These are my books.", "Those are my friends."] }),
    ],
    exercises: [
      mc("(a pen in your hand) ___ is my pen.", ["This", "That"], 0, "Near: this."),
      mc("(a building over there) ___ is my school.", ["This", "That"], 1, "Far: that."),
      fill("___ are my books. (near, plural)", ["These"], "Near + plural: these."),
      mist("Find the mistake.", ["Look at", "this people", "over there."], 1, "those people", "Far + plural: those."),
      match("Near or far?", [["this", "near"], ["that", "far"], ["these", "near (plural)"], ["those", "far (plural)"]], "This / these = near; that / those = far."),
      order("Put the words in the correct order.", ["That", "is", "my", "house."], "word", "That + is + noun."),
    ],
  },
  {
    slug: "beginner-grammar-there-is-are",
    level: "BEGINNER", category: "GRAMMAR", title: "There is / There are", topic: "there is / there are",
    difficulty: "BASIC", minutes: 10, prereq: ["beginner-grammar-this-that"],
    objective: "Say what is in a place with there is, there are, there isn't and there aren't.",
    tags: ["grammar", "there-is-are", "places", "home", "A1"],
    ref: { book: HW, level: "Beginner", area: "Grammar", topic: "There is / There are (Unit 8)" },
    sections: [
      text("Use **there is** for **one** thing and **there are** for **two or more** things. Use them to describe a **place**.", "Explanation"),
      table("Forms", ["Feature", "One thing", "More than one"], [
        ["Positive", "There is a sofa.", "There are two beds."], ["Negative", "There isn't a TV.", "There aren't any chairs."],
        ["Question", "Is there a garden?", "Are there any shops?"], ["Short answers", "Yes, there is. / No, there isn't.", "Yes, there are. / No, there aren't."],
      ]),
      structure("Structure", "There is + a / an + singular noun\nThere are + plural noun", "Use any in negatives and questions with plurals: There aren't any chairs. Are there any shops?"),
    ],
    exercises: [
      fill("___ a big bed in my room.", [["There is", "There's"]], "One bed: there is."),
      fill("There ___ two chairs in the kitchen.", ["are"], "Two: there are."),
      mist("Find the mistake.", ["There", "is", "three windows."], 1, "are", "Three windows: there are."),
      mc("___ a shop near your house?", ["Is there", "Are there", "There is"], 0, "One shop: Is there…?"),
      order("Put the words in the correct order.", ["There", "isn't", "a", "TV", "in", "the", "room."], "word", "There isn't + a + noun + place."),
      sa("Short answer: “Are there any shops?” (No) — No, there ___.", ["aren't", "are not"], "No, there aren't.", { hint: "one word" }),
    ],
  },
  {
    slug: "beginner-grammar-prepositions-of-place",
    level: "BEGINNER", category: "GRAMMAR", title: "Prepositions of Place: in, on, under, next to", topic: "Prepositions",
    difficulty: "BASIC", minutes: 8, prereq: ["beginner-grammar-there-is-are"],
    objective: "Say where things are with in, on, under and next to.",
    tags: ["grammar", "prepositions", "places", "home", "A1"],
    ref: { book: HW, level: "Beginner", area: "Grammar", topic: "Prepositions of place (Unit 8)" },
    sections: [
      text("**Prepositions of place** say **where** something is.", "Explanation"),
      table("Prepositions of place", ["Preposition", "Meaning", "Example"], [
        ["in", "inside", "The keys are in my bag."], ["on", "on the top of", "The book is on the table."], ["under", "below", "The cat is under the chair."], ["next to", "beside", "The lamp is next to the bed."],
      ]),
      structure("Structure", "The + noun + is / are + preposition + the + noun", "Use in for cities and countries: in Muscat, in Oman."),
    ],
    exercises: [
      fill("The cat is ___ the chair. (below)", ["under"], "under = below."),
      fill("The book is ___ the table.", ["on"], "on the surface."),
      mc("The lamp is ___ the bed. (beside)", ["next to", "under", "in"], 0, "next to = beside."),
      mist("Find the mistake.", ["My keys are", "on", "my bag."], 1, "in", "Inside a bag: in."),
      match("Match the meaning.", [["in", "inside"], ["on", "on top of"], ["under", "below"], ["next to", "beside"]], "Each preposition shows a position."),
      order("Put the words in the correct order.", ["The", "cat", "is", "under", "the", "table."], "word", "The + noun + is + under + the + noun."),
    ],
  },
  {
    slug: "beginner-vocab-adjectives-opposites",
    level: "BEGINNER", category: "VOCABULARY", title: "Adjectives and Opposites", topic: "Adjectives",
    difficulty: "BASIC", minutes: 8, prereq: ["beginner-vocab-adjective-noun-order"],
    objective: "Learn common adjectives and their opposites.",
    tags: ["vocabulary", "adjectives", "opposites", "describing", "A1"],
    ref: { book: HW, level: "Beginner", area: "Vocabulary", topic: "Adjectives and opposites (Unit 7)" },
    sections: [
      text("Learn adjectives **in pairs**. When you know **big**, you also know **small**."),
      table("Opposites", ["Adjective", "Opposite", "Example"], [
        ["big", "small", "a big house · a small flat"], ["old", "new", "an old car · a new phone"], ["expensive", "cheap", "an expensive watch · a cheap pen"],
        ["good", "bad", "good food · bad weather"], ["hot", "cold", "hot tea · cold water"], ["easy", "difficult", "an easy test · a difficult test"],
      ]),
      structure("Structure", "a / an + adjective + noun\nThe + noun + is + adjective", "The phone is new. It's a new phone."),
    ],
    exercises: [
      match("Match the opposites.", [["big", "small"], ["old", "new"], ["expensive", "cheap"], ["hot", "cold"], ["easy", "difficult"]], "Learn the pairs."),
      fill("This test is not easy. It's ___.", ["difficult"], "The opposite of easy: difficult."),
      mc("The tea is ___. Be careful!", ["hot", "cold", "cheap"], 0, "Be careful = hot."),
      mc("Which sentence makes sense?", ["The bag is expensive, so it costs a lot.", "The bag is cheap, so it costs a lot.", "The bag is expensive, so it costs very little."], 0, "Expensive things cost a lot; cheap things cost little."),
      order("Put the words in the correct order.", ["It", "is", "a", "small", "flat."], "word", "a + adjective + noun."),
      sa("The opposite of “new” is ___.", ["old"], "new ↔ old.", { hint: "o _ d" }),
    ],
  },
  {
    slug: "beginner-vocab-rooms-furniture",
    level: "BEGINNER", category: "VOCABULARY", title: "Rooms and Furniture", topic: "Home",
    difficulty: "BASIC", minutes: 10, prereq: ["beginner-vocab-adjectives-opposites"],
    objective: "Name the rooms in a home and the furniture in each room.",
    tags: ["vocabulary", "home", "furniture", "rooms", "listening-support", "A1"],
    ref: { book: HW, level: "Beginner", area: "Vocabulary", topic: "Rooms and furniture (Unit 8)" },
    sections: [
      text("Learn the rooms of a home and the things **in each room**."),
      table("Rooms and furniture", ["Room", "Furniture"], [
        ["living room", "sofa, TV, table, lamp"], ["kitchen", "fridge, cooker, sink, table"], ["bedroom", "bed, wardrobe, lamp"], ["bathroom", "shower, toilet, mirror"],
      ]),
      vocab([
        { word: "sofa", pos: "noun", meaning: "a soft seat for two or three people", ar: "أريكة", pron: "/ˈsəʊfə/", ex: "There is a blue sofa in the living room.", col: ["a comfortable sofa"], visual: "🛋️" },
        { word: "bed", pos: "noun", meaning: "you sleep in it", ar: "سرير", pron: "/bed/", ex: "My bed is next to the window.", col: ["go to bed"], visual: "🛏️" },
        { word: "fridge", pos: "noun", meaning: "keeps food cold", ar: "ثلاجة", pron: "/frɪdʒ/", ex: "The milk is in the fridge.", col: ["in the fridge"], visual: "🧊" },
        { word: "shower", pos: "noun", meaning: "you wash under it", ar: "دش", pron: "/ˈʃaʊə/", ex: "The bathroom has a shower.", col: ["have a shower"], visual: "🚿" },
      ], "Key words"),
    ],
    exercises: [
      match("Which room?", [["sofa", "living room"], ["fridge", "kitchen"], ["bed", "bedroom"], ["shower", "bathroom"]], "Think about where you use each thing."),
      mc("You sleep in the ___.", ["bedroom", "kitchen", "bathroom"], 0, "Bedroom."),
      mc("The ___ keeps food cold.", ["fridge", "sofa", "lamp"], 0, "A fridge keeps food cold."),
      fill("There is a big ___ in the living room. (you sit on it)", ["sofa"], "A sofa."),
      mist("Find the mistake.", ["There is a", "cooker", "in the bathroom."], 1, "shower", "A cooker is in the kitchen."),
      order("Put the words in the correct order.", ["There", "is", "a", "fridge", "in", "the", "kitchen."], "word", "There is + a + noun + place."),
    ],
  },
  {
    slug: "beginner-vocab-places-in-town",
    level: "BEGINNER", category: "VOCABULARY", title: "Places in Town", topic: "Places",
    difficulty: "BASIC", minutes: 8, prereq: ["beginner-vocab-rooms-furniture"],
    objective: "Name places in a town and say where they are.",
    tags: ["vocabulary", "places", "town", "listening-support", "A1"],
    ref: { book: HW, level: "Beginner", area: "Vocabulary", topic: "Places in town (Unit 8)" },
    sections: [
      text("Learn the places in a town. Use **in** for towns and **next to** for places near each other."),
      table("Places", ["Place", "You…"], [
        ["shop", "buy things"], ["bank", "get money"], ["school", "study"], ["hospital", "see a doctor"], ["park", "walk and play"], ["restaurant", "eat"],
      ]),
      structure("Structure", "There is a + place + next to / near + place.", "Example: There is a bank next to the shop."),
    ],
    exercises: [
      match("Match the place with what you do.", [["shop", "buy things"], ["bank", "get money"], ["hospital", "see a doctor"], ["park", "walk and play"]], "Each place has a use."),
      mc("You study at a ___.", ["school", "bank", "restaurant"], 0, "School."),
      fill("You eat in a ___.", ["restaurant"], "A restaurant."),
      mist("Find the mistake.", ["There are", "a bank", "next to the shop."], 0, "There is", "One bank: there is."),
      order("Put the words in the correct order.", ["There", "is", "a", "park", "next", "to", "the", "school."], "word", "There is + a + place + next to + place."),
      sa("You get money at a ___.", ["bank"], "A bank.", { hint: "b _ _ k" }),
    ],
  },
  {
    slug: "beginner-reading-email-salalah",
    level: "BEGINNER", category: "READING", title: "Reading: An Email from Salalah", topic: "Descriptions",
    difficulty: "BASIC", minutes: 10, prereq: ["beginner-reading-bus-driver-day"],
    objective: "Read a short email and find what there is in a place.",
    tags: ["reading", "reading-details", "there-is-are", "places", "A1"],
    ref: { book: HW, level: "Beginner", area: "Reading", topic: "An email from holiday (Unit 7-8)" },
    sections: [
      text("An **email** from a holiday describes **a place**. Look for **there is / there are** to find what is in the place.", "Reading strategy"),
      passage("Example", "Hi Dad! I'm in Sur. There is a nice hotel near the sea. There are three restaurants next to it.", "A short email"),
      list("Guided practice", ["What is near the sea? → a hotel.", "How many restaurants? → three."]),
    ],
    exercises: [
      mc("Where is Nora?", ["in Salalah", "in Muscat", "in Cairo"], 0, "“I'm in Salalah!”", SALALAH_EMAIL),
      mc("What is near her hotel?", ["a big beach", "a bank", "a school"], 0, "“There is a big beach near my hotel.”", SALALAH_EMAIL),
      sa("How many small shops are there? (write a number)", ["2", "two"], "“there are two small shops”.", { context: SALALAH_EMAIL }),
      tf("There is a TV in her room.", false, "“There isn't a TV.”", SALALAH_EMAIL),
      mc("What can Nora see from the balcony?", ["the sea", "a park", "a school"], 0, "“I can see the sea from the balcony.”", SALALAH_EMAIL),
      mc("Her room is ___.", ["small but nice", "big and cold", "expensive"], 0, "“My room is small, but it's nice.”", SALALAH_EMAIL),
    ],
  },
  {
    slug: "beginner-reading-favourite-city",
    level: "BEGINNER", category: "READING", title: "Reading: My Favourite City", topic: "Opinions about a place",
    difficulty: "BASIC", minutes: 10, prereq: ["beginner-reading-email-salalah"],
    objective: "Find reasons and details in a short text about a favourite place.",
    tags: ["reading", "reading-details", "reading-main-idea", "places", "A1"],
    ref: { book: HW, level: "Beginner", area: "Reading", topic: "The best place in the world (Unit 8)" },
    sections: [
      text("When someone tells you about a **favourite place**, they give **reasons** with **because**. Find the reason for each opinion.", "Reading strategy"),
      passage("Example", "My favourite place is the beach. I like it because it is quiet, and the sea is blue.", "Opinion + reason"),
      list("Guided practice", ["Opinion → I like the beach.", "Reason → it is quiet; the sea is blue."]),
    ],
    exercises: [
      mc("What is the writer's favourite city?", ["Muscat", "Cairo", "Salalah"], 0, "“My favourite city is Muscat.”", MY_CITY),
      mc("What is next to the city?", ["a beach", "a mountain", "a lake"], 0, "“There is a beach next to the city.”", MY_CITY),
      mc("Why does the writer like Muscat?", ["It is quiet and the food is cheap.", "It is big and busy.", "It is cold."], 0, "“because it is quiet, and the food is cheap”.", MY_CITY),
      tf("The people in Muscat are unfriendly.", false, "“The people are very friendly.”", MY_CITY),
      tf("There are many parks.", true, "“There are many parks and a big market.”", MY_CITY),
      mc("What is the main idea of the text?", ["Muscat is the writer's favourite city.", "Cities are big.", "Parks are cheap."], 0, "The whole text describes Muscat.", MY_CITY),
    ],
  },
  {
    slug: "beginner-writing-describing-room",
    level: "BEGINNER", category: "WRITING", title: "Describing a Room or a Flat", topic: "Spatial description",
    difficulty: "BASIC", minutes: 12, prereq: ["beginner-writing-timetable-to-paragraph", "beginner-grammar-prepositions-of-place"],
    objective: "Write a short paragraph describing a room with there is / there are and prepositions of place.",
    tags: ["writing", "describing-places", "there-is-are", "prepositions", "A1"],
    ref: { book: HW, level: "Beginner", area: "Writing", topic: "Describing a room or flat (Unit 8)" },
    sections: [
      text("To describe a room, follow a **path** with your eyes: **start** with the room, say **what there is**, then say **where things are** with **prepositions**.", "Explanation"),
      table("A flat plan", ["Room", "Things"], [["living room", "a sofa, a TV, a table"], ["kitchen", "a fridge, a cooker"], ["bedroom", "a bed, a lamp"]]),
      annotated("Model paragraph (about 50 words)", [
        ["Start", "My flat is small, but it is nice. There is a living room, a kitchen and a bedroom."],
        ["Living room", "In the living room, there is a sofa and a TV. The table is next to the sofa."],
        ["Bedroom", "In the bedroom, there is a bed. The lamp is on the table next to the bed."],
      ]),
      tip("Use there is for one thing and there are for two or more.", "Grammar check"),
    ],
    exercises: [
      order("Put the sentences in the correct order.", ["My flat is small, but it is nice.", "There is a living room, a kitchen and a bedroom.", "In the living room, there is a sofa.", "The lamp is next to the bed."], "paragraph", "General, rooms, details."),
      fill("In the bedroom ___ a bed and a lamp.", ["there is"], "Use there is; the first item is a bed."),
      fill("The lamp is ___ to the bed.", ["next"], "next to."),
      mist("Find the mistake.", ["In the kitchen,", "there is", "two chairs."], 1, "there are", "Two chairs: there are."),
      order("Put the words in the correct order.", ["The", "table", "is", "next", "to", "the", "sofa."], "word", "The + noun + is + next to + the + noun."),
      mc("Which sentence describes where a thing is?", ["The book is on the table.", "I like books.", "Books are good."], 0, "Preposition of place: on the table."),
    ],
  },
];

void [compare, examples, ms, tip];
