import { HW, annotated, compare, examples, fill, list, match, mc, ms, mist, order, passage, sa, structure, table, text, tf, tip, vocab, type SeedLesson } from "./dsl";

// Beginner course, Teaching Weeks 6-8 (Units 1-12 review, Units 9-12). Topics follow the academy's syllabus; all text is ORIGINAL.

const TARIQ_FLAT = "Tariq is 22 and he is a student. He lives in a small flat near the university. There are two rooms and a small kitchen. His flat isn't expensive, but it is old. He usually gets up at seven, and he goes to the university by bus. On Fridays, he plays football with his friends. Tariq's sister, Maha, lives in Dubai. She is a nurse.";
const BAD_LUCK = "Last Monday was a bad day for Tariq. He got up late, and he missed the bus. He walked to work in the rain, but he didn't have an umbrella. At work, he lost his phone and he broke a cup. In the evening, he went home and made dinner, but the food was bad. He went to bed hungry. “Tomorrow is a new day,” he said.";
const SUR_WEEKEND = "Last weekend, Huda went to Sur with her friends. They travelled by car, and they arrived at ten o'clock. In the morning, they visited the old boat-building place and took photos. At lunch, they ate fish and rice in a small restaurant. In the afternoon, they walked on the beach. They didn't swim because it was windy. They came home in the evening. It was a lovely weekend.";
const PHONE = "I have a smartphone. It is small, but it can do a lot. I can call my family, send messages, take photos, listen to music and read books. I can't cook dinner with it, but I can find recipes!\n\nMy grandfather can't use a smartphone. He can use an old phone. He says, “Phones are good, but I like to talk to people.”";
const MEALS = "In many countries, people have three meals a day: breakfast, lunch and dinner. The times are different. In Oman, many families have a big lunch at about one o'clock. In Spain, people often have dinner late, at about nine or ten o'clock. In Japan, many people have rice for breakfast. In England, a traditional breakfast is eggs, toast and tea.";

export const BEGINNER_W6_W8: SeedLesson[] = [
  // ============================================================ WEEK 6 · REVIEW (Units 1-8)
  {
    slug: "beginner-grammar-review-units-1-8",
    level: "BEGINNER", category: "GRAMMAR", title: "Grammar Review: Verb to be, Present Simple and Possessives (Units 1–8)", topic: "Review",
    difficulty: "BASIC", minutes: 14, prereq: ["beginner-grammar-prepositions-of-place"],
    objective: "Revise verb to be, Present Simple, possessives, question forms and there is / there are before the mid-term exam.",
    tags: ["grammar", "review", "verb-to-be", "present-simple", "possessives", "A1"],
    ref: { book: HW, level: "Beginner", area: "Grammar", topic: "Revision, Units 1-8" },
    sections: [
      text("This lesson brings together the grammar of **Units 1–8**. Use the table to check the forms, then do the practice.", "Explanation"),
      table("Grammar checklist", ["Point", "Form", "Example"], [
        ["Verb to be", "I am · he / she / it is · we / you / they are", "She is a nurse. They aren't here."],
        ["Possessive adjectives", "my · your · his · her · our · their", "Her name is Aisha."],
        ["Possessive 's", "owner + 's + thing", "Omar's phone"],
        ["Present Simple (I / you / we / they)", "verb · don't + verb · Do + subject + verb?", "I like tea. I don't like coffee. Do you like tea?"],
        ["Present Simple (he / she / it)", "verb + s · doesn't + verb · Does + subject + verb?", "He works. He doesn't work. Does he work?"],
        ["there is / there are", "There is + one · There are + many", "There is a bank. There are two shops."],
      ]),
      list("Common mistakes to avoid", ["He like → He **likes**.", "She doesn't likes → She doesn't **like**.", "I am from **oman** → I am from **Oman**.", "in 7:00 → **at** 7:00; in Monday → **on** Monday."]),
    ],
    exercises: [
      mc("She ___ a teacher.", ["am", "is", "are"], 1, "She → is."),
      mc("My father ___ in a bank.", ["work", "works", "working"], 1, "He → works."),
      mc("Omar ___ like coffee.", ["don't", "doesn't", "isn't"], 1, "Omar = he: doesn't."),
      mc("Is this ___ bag? Yes, it's my bag.", ["your", "you", "yours"], 0, "Possessive adjective before a noun: your."),
      mc("___ two shops next to the bank.", ["There is", "There are", "It is"], 1, "Two shops: there are."),
      order("Put the words in the correct order.", ["Where", "does", "your", "sister", "work?"], "word", "Where + does + subject + verb."),
    ],
  },
  {
    slug: "beginner-vocab-review-units-1-8",
    level: "BEGINNER", category: "VOCABULARY", title: "Vocabulary Review: High-Frequency Word Sets (Units 1–8)", topic: "Review",
    difficulty: "BASIC", minutes: 12, prereq: ["beginner-vocab-places-in-town"],
    objective: "Revise the vocabulary sets from Units 1–8 before the mid-term exam.",
    tags: ["vocabulary", "review", "word-sets", "A1"],
    ref: { book: HW, level: "Beginner", area: "Vocabulary", topic: "Revision, Units 1-8" },
    sections: [
      text("Revise the **word sets** you have learned. Group words by **topic** to remember them better."),
      table("Word sets", ["Topic", "Words"], [
        ["Objects", "book, pen, bag, phone, key, umbrella"], ["Family", "father, mother, son, daughter, brother, sister, uncle, aunt"], ["Jobs", "teacher, doctor, driver, engineer, student, cook"],
        ["Free time", "football, tennis, swimming, music, reading"], ["Daily routine", "get up, have breakfast, go to work, go to bed"], ["Rooms", "living room, kitchen, bedroom, bathroom"],
        ["Places", "shop, bank, school, hospital, park, restaurant"],
      ]),
    ],
    exercises: [
      match("Which topic?", [["uncle", "Family"], ["engineer", "Jobs"], ["kitchen", "Rooms"], ["swimming", "Free time"], ["bank", "Places"]], "Choose the topic for each word."),
      mc("Which word is a job?", ["doctor", "sofa", "umbrella"], 0, "Doctor is a job."),
      mc("Which word is NOT a room?", ["kitchen", "bedroom", "bank"], 2, "A bank is a place in town."),
      fill("You open a door with a ___.", ["key"], "key."),
      mist("Find the mistake.", ["My mother is", "an teacher", "."], 1, "a teacher", "Teacher starts with a consonant sound: a."),
      match("Opposites.", [["big", "small"], ["old", "new"], ["hot", "cold"], ["cheap", "expensive"]], "Learn adjectives in pairs."),
    ],
  },
  {
    slug: "beginner-reading-mc-practice",
    level: "BEGINNER", category: "READING", title: "Reading Practice: Multiple-Choice Questions", topic: "Exam practice",
    difficulty: "BASIC", minutes: 12, prereq: ["beginner-reading-favourite-city"],
    objective: "Practise answering multiple-choice questions and guessing the meaning of words from context.",
    tags: ["reading", "reading-multiple-choice", "reading-vocabulary-context", "review", "A1"],
    ref: { book: HW, level: "Beginner", area: "Reading", topic: "Multiple-choice reading; vocabulary in context (revision)" },
    sections: [
      text("In an exam, read the **text first**, then each **question**. Find the **words from the question** in the text. **Cross out** the wrong answers. Check that your answer matches the text.", "Reading strategy"),
      list("Steps", ["1. Read the text once.", "2. Read the question.", "3. Find the answer in the text.", "4. Choose the option that matches. Do not choose only because a word is the same."]),
      tip("For a word you don't know, read the sentence around it. The other words help you guess.", "Vocabulary in context"),
    ],
    exercises: [
      mc("Where does Tariq live?", ["in a big house", "in a small flat near the university", "in Dubai"], 1, "“He lives in a small flat near the university.”", TARIQ_FLAT),
      mc("How many rooms are there?", ["two rooms and a kitchen", "four rooms", "one room"], 0, "“There are two rooms and a small kitchen.”", TARIQ_FLAT),
      mc("His flat is ___.", ["new and expensive", "old and not expensive", "big and cheap"], 1, "“isn't expensive, but it is old”.", TARIQ_FLAT),
      mc("What does Tariq do on Fridays?", ["He plays football.", "He goes to the university.", "He visits Dubai."], 0, "“On Fridays, he plays football with his friends.”", TARIQ_FLAT),
      mc("In the text, “near” means…", ["far from", "not far from", "inside"], 1, "near = not far from.", TARIQ_FLAT),
      mc("Who is Maha?", ["Tariq's sister", "Tariq's mother", "a student"], 0, "“Tariq's sister, Maha”.", TARIQ_FLAT),
    ],
  },
  {
    slug: "beginner-writing-editing-agreement-prepositions",
    level: "BEGINNER", category: "WRITING", title: "Editing Workshop: Subject–Verb Agreement and Prepositions", topic: "Error correction",
    difficulty: "BASIC", minutes: 12, prereq: ["beginner-writing-describing-room"],
    objective: "Find and correct mistakes in agreement (he likes / they like) and prepositions (in London, at 7:00, on Friday).",
    tags: ["writing", "editing", "error-correction", "agreement", "prepositions", "A1"],
    ref: { book: HW, level: "Beginner", area: "Writing", topic: "Peer-editing and error correction (Units 1-8 revision)" },
    sections: [
      text("Good writers **check their work**. Look for two common types of mistakes: **verb agreement** and **prepositions**.", "Explanation"),
      table("Common mistakes", ["Type", "Mistake", "Correction"], [
        ["Agreement", "He like tea.", "He likes tea."], ["Agreement", "They likes football.", "They like football."], ["Agreement", "She don't work.", "She doesn't work."],
        ["Preposition (place)", "I live at London.", "I live in London."], ["Preposition (time)", "The class starts in 8:00.", "The class starts at 8:00."], ["Preposition (day)", "We play in Friday.", "We play on Friday."],
      ]),
      list("Checklist", ["Does each verb agree with its subject (he likes / they like)?", "Are the prepositions right (in London, at 7:00, on Friday)?", "Capital letters and full stops?"]),
    ],
    exercises: [
      sa("Correct the sentence: He like tea.", ["He likes tea.", "He likes tea"], "he + likes.", { hint: "He likes …" }),
      sa("Correct the sentence: They likes football.", ["They like football.", "They like football"], "they + like.", { hint: "They like …" }),
      mist("Find the mistake.", ["I live", "at London", "with my family."], 1, "in London", "Cities take in."),
      mist("Find the mistake.", ["The class starts", "in 8:00", "on Monday."], 1, "at 8:00", "Clock times take at."),
      mist("Find the mistake.", ["We play football", "in Friday", "."], 1, "on Friday", "Days take on."),
      mc("Which sentence is correct?", ["She don't work on Friday.", "She doesn't work on Friday.", "She doesn't works on Friday."], 1, "She doesn't work."),
    ],
  },

  // ============================================================ WEEK 7 · GRAMMAR
  {
    slug: "beginner-grammar-was-were-born",
    level: "BEGINNER", category: "GRAMMAR", title: "Past of be: was, were and was born", topic: "Past tense",
    difficulty: "BASIC", minutes: 10, prereq: ["beginner-grammar-review-units-1-8"],
    objective: "Use was and were to talk about the past, and say where and when you were born.",
    tags: ["grammar", "past-simple", "was-were", "born", "A1"],
    ref: { book: HW, level: "Beginner", area: "Grammar", topic: "was / were; was born (Unit 9)" },
    sections: [
      text("**Was** and **were** are the past of **am / is / are**. Use **was** with I, he, she, it and **were** with we, you, they.", "Explanation"),
      table("Past of be", ["Present", "Past", "Example"], [
        ["I am · he / she / it is", "was", "I was at home. She was tired."], ["we / you / they are", "were", "We were in Muscat. They were late."],
        ["negative", "wasn't · weren't", "I wasn't there. They weren't happy."], ["question", "Was / Were + subject?", "Were you at school? — Yes, I was."],
      ]),
      structure("Was born", "I was born in + year / place.   He was born on + date.", "We say I was born in Sohar in 2001. (not I born)"),
    ],
    exercises: [
      fill("She ___ at home yesterday.", ["was"], "She → was."),
      fill("We ___ in Muscat last year.", ["were"], "We → were."),
      mist("Find the mistake.", ["I", "born", "in Sohar in 2001."], 1, "was born", "We say I was born."),
      mc("___ you at school yesterday? Yes, I ___.", ["Were / was", "Was / were", "Are / am"], 0, "Were you…? Yes, I was."),
      order("Put the words in the correct order.", ["He", "wasn't", "at", "home", "yesterday."], "word", "Subject + wasn't + place + time."),
      sa("Make it negative: They were late. → They ___ late.", ["weren't", "were not"], "weren't.", { hint: "weren't" }),
    ],
  },
  {
    slug: "beginner-grammar-past-simple-regular",
    level: "BEGINNER", category: "GRAMMAR", title: "Past Simple: Regular Verbs (-ed)", topic: "Past Simple",
    difficulty: "BASIC", minutes: 10, prereq: ["beginner-grammar-was-were-born"],
    objective: "Make the Past Simple of regular verbs with -ed and use it for finished actions.",
    tags: ["grammar", "past-simple", "regular-verbs", "A1"],
    ref: { book: HW, level: "Beginner", area: "Grammar", topic: "Past Simple: regular verbs (Unit 9-10)" },
    sections: [
      text("Use the **Past Simple** for **finished actions** in the past: yesterday, last week, two days ago. **Regular verbs** add **-ed**.", "Explanation"),
      table("Spelling", ["Rule", "Example"], [
        ["+ -ed", "work → worked · play → played · visit → visited"], ["ends in -e: + -d", "live → lived · like → liked"], ["consonant + y: y → -ied", "study → studied"], ["one vowel + one consonant: double", "stop → stopped"],
      ]),
      table("Time words", ["Word", "Example"], [["yesterday", "I visited my aunt yesterday."], ["last week / last year", "We travelled last week."], ["two days ago", "She called two days ago."]]),
      structure("Structure", "subject + verb-ed (the same for all persons)", "I worked · she worked · they worked."),
    ],
    exercises: [
      fill("I ___ (visit) my aunt yesterday.", ["visited"], "visit + ed."),
      fill("She ___ (live) in Cairo two years ago.", ["lived"], "live + d."),
      mc("We ___ football last Friday.", ["play", "played", "playing"], 1, "Finished time: played."),
      mist("Find the mistake.", ["He", "stoped", "at the bank."], 1, "stopped", "Double the p: stopped."),
      match("Base → past.", [["work", "worked"], ["study", "studied"], ["stop", "stopped"], ["like", "liked"]], "Follow the spelling rules."),
      order("Put the words in the correct order.", ["She", "visited", "her", "aunt", "yesterday."], "word", "Subject + verb-ed + object + time."),
    ],
  },
  {
    slug: "beginner-grammar-past-simple-irregular",
    level: "BEGINNER", category: "GRAMMAR", title: "Past Simple: Irregular Verbs", topic: "Past Simple",
    difficulty: "BASIC", minutes: 10, prereq: ["beginner-grammar-past-simple-regular"],
    objective: "Use common irregular past forms: went, had, bought, made, saw.",
    tags: ["grammar", "past-simple", "irregular-verbs", "A1"],
    ref: { book: HW, level: "Beginner", area: "Grammar", topic: "Past Simple: irregular verbs (Unit 9-10)" },
    sections: [
      text("Some verbs are **irregular**. They do not add -ed. You must **learn** the past forms.", "Explanation"),
      table("Common irregular verbs", ["Base form", "Past form"], [
        ["go", "went"], ["have", "had"], ["buy", "bought"], ["make", "made"], ["see", "saw"], ["get", "got"], ["eat", "ate"], ["take", "took"], ["come", "came"], ["lose", "lost"],
      ]),
      structure("Structure", "subject + irregular past form", "The past form is the same for all persons: I went · she went · they went."),
      examples("Examples", { "": ["I went to the market yesterday.", "She bought a new bag.", "We had lunch at one o'clock."] }),
    ],
    exercises: [
      match("Base form → past form.", [["go", "went"], ["have", "had"], ["buy", "bought"], ["make", "made"], ["see", "saw"]], "Learn the irregular forms."),
      fill("Yesterday I ___ (go) to the market and ___ (buy) some fruit.", ["went", "bought"], "go → went; buy → bought."),
      mist("Find the mistake.", ["We", "goed", "to Sur last week."], 1, "went", "Go is irregular: went."),
      mc("She ___ a cake for the party.", ["maked", "made", "make"], 1, "make → made."),
      order("Put the words in the correct order.", ["We", "had", "lunch", "at", "one", "o'clock."], "word", "Subject + had + object + time."),
      sa("Past of “see”: ___", ["saw"], "see → saw.", { hint: "s _ w" }),
    ],
  },
  {
    slug: "beginner-grammar-past-simple-did-didnt",
    level: "BEGINNER", category: "GRAMMAR", title: "Past Simple: didn't and Did you …?", topic: "Past Simple",
    difficulty: "BASIC", minutes: 10, prereq: ["beginner-grammar-past-simple-irregular"],
    objective: "Make Past Simple negatives and questions with did and didn't, and use time expressions (ago, last, yesterday).",
    tags: ["grammar", "past-simple", "negatives", "questions", "time-expressions", "A1"],
    ref: { book: HW, level: "Beginner", area: "Grammar", topic: "Past Simple negatives and questions (Unit 10)" },
    sections: [
      text("For **negatives** use **didn't** + base verb. For **questions** use **Did** + subject + base verb. The main verb is in its **base form**: no -ed and no past form.", "Explanation"),
      table("Past Simple with did", ["Type", "Form", "Example"], [
        ["Positive", "verb-ed / irregular", "I watched the film."],
        ["Negative", "didn't + base verb", "I didn't watch the film."],
        ["Question", "Did + subject + base verb?", "Did you watch the film?"],
        ["Short answers", "Yes, I did. / No, I didn't.", "Did she go? — No, she didn't."],
      ]),
      table("Time expressions", ["Expression", "Example"], [["ago", "two years ago · a week ago"], ["last", "last night · last week · last year"], ["yesterday", "yesterday morning · yesterday evening"]]),
      structure("Structure", "didn't + base verb · Did + subject + base verb?", "Not: I didn't watched. Say: I didn't watch."),
    ],
    exercises: [
      fill("I ___ watch TV last night. (negative)", ["didn't"], "didn't + base verb."),
      fill("___ you go to school yesterday? No, I ___.", ["Did", "didn't"], "Did you…? No, I didn't."),
      mist("Find the mistake.", ["She", "didn't went", "to work."], 1, "didn't go", "After didn't use the base form."),
      order("Put the words in the correct order.", ["Did", "you", "have", "breakfast", "this", "morning?"], "word", "Did + subject + verb + object."),
      mc("She called me two days ___.", ["ago", "last", "before"], 0, "ago after the time period."),
      sa("Make it negative: We went to the beach. → We ___ go to the beach.", ["didn't", "did not"], "didn't + base verb.", { hint: "didn't" }),
    ],
  },

  // ============================================================ WEEK 7 · VOCABULARY
  {
    slug: "beginner-vocab-years-months-dates",
    level: "BEGINNER", category: "VOCABULARY", title: "Years, Months, Dates and Ordinal Numbers", topic: "Dates",
    difficulty: "BASIC", minutes: 10, prereq: ["beginner-vocab-numbers-31-100-prices"],
    objective: "Say years, months and dates with ordinal numbers.",
    tags: ["vocabulary", "dates", "months", "numbers", "A1"],
    ref: { book: HW, level: "Beginner", area: "Vocabulary", topic: "Years, months, dates, ordinals (Unit 9)" },
    sections: [
      text("Use **ordinal numbers** for dates: the **first**, the **second**, the **third**. Months start with a capital letter."),
      table("Ordinals", ["Number", "Word"], [["1st", "first"], ["2nd", "second"], ["3rd", "third"], ["4th", "fourth"], ["5th", "fifth"], ["12th", "twelfth"], ["20th", "twentieth"], ["31st", "thirty-first"]]),
      list("Saying years", ["1998: nineteen ninety-eight", "2005: two thousand and five", "2024: twenty twenty-four"]),
      tip("Months: January, February, March, April, May, June, July, August, September, October, November, December.", "Months"),
    ],
    exercises: [
      match("Number → word.", [["1st", "first"], ["2nd", "second"], ["3rd", "third"], ["5th", "fifth"]], "1st, 2nd, 3rd are irregular."),
      sa("Write in words: 20th → ___", ["twentieth"], "twentieth.", { hint: "twent…" }),
      mc("How do we say 2005?", ["two thousand and five", "twenty zero five", "two zero zero five"], 0, "two thousand and five."),
      fill("My birthday is ___ March. (preposition)", ["in"], "in + month."),
      mist("Find the mistake.", ["My birthday is on", "the two", "of May."], 1, "the second", "Use ordinal: the second."),
      order("Put the months in order.", ["January", "February", "March", "April"], "word", "The year starts with January."),
    ],
  },
  {
    slug: "beginner-vocab-collocations-have-do-go",
    level: "BEGINNER", category: "VOCABULARY", title: "Collocations with have, do and go", topic: "Collocations",
    difficulty: "BASIC", minutes: 10, prereq: ["beginner-vocab-years-months-dates"],
    objective: "Use the verbs have, do and go with the correct nouns.",
    tags: ["vocabulary", "collocations", "have-do-go", "listening-support", "A1"],
    ref: { book: HW, level: "Beginner", area: "Vocabulary", topic: "Collocations with have, do, go (Unit 10)" },
    sections: [
      text("Some verbs go with **certain nouns**. Learn them together: **have** lunch, **do** homework, **go** shopping."),
      table("have, do, go", ["Verb", "Goes with"], [
        ["have", "breakfast, lunch, dinner, a shower, a good time, a party"], ["do", "homework, exercise, the shopping, the housework, your best"], ["go", "shopping, swimming, home, to school, to bed, on holiday"],
      ]),
      compare("Common mistakes", [["I make my homework.", "I do my homework.", "do + homework."], ["We eat a shower.", "We have a shower.", "have + shower."], ["She goes to the shopping.", "She goes shopping.", "go + shopping."]]),
    ],
    exercises: [
      match("Which verb?", [["homework", "do"], ["lunch", "have"], ["shopping", "go"], ["a party", "have"], ["exercise", "do"]], "Learn the pairs."),
      fill("I ___ my homework every evening.", ["do"], "do homework."),
      fill("We ___ lunch at one o'clock.", ["have"], "have lunch."),
      mist("Find the mistake.", ["We", "make", "shopping on Saturdays."], 1, "go", "go shopping."),
      mc("They ___ swimming on Fridays.", ["go", "do", "have"], 0, "go swimming."),
      order("Put the words in the correct order.", ["She", "does", "her", "homework", "at", "home."], "word", "Subject + does + object + place."),
    ],
  },
  {
    slug: "beginner-vocab-holiday-words",
    level: "BEGINNER", category: "VOCABULARY", title: "Holiday Vocabulary", topic: "Holidays",
    difficulty: "BASIC", minutes: 10, prereq: ["beginner-vocab-collocations-have-do-go"],
    objective: "Use common holiday words to describe a trip.",
    tags: ["vocabulary", "holidays", "travel", "listening-support", "A1"],
    ref: { book: HW, level: "Beginner", area: "Vocabulary", topic: "Holiday vocabulary (Unit 10)" },
    sections: [
      text("Use these words to talk about a **holiday**: where you **went**, what you **did**, and what you **saw**."),
      vocab([
        { word: "hotel", pos: "noun", meaning: "a place to stay when you travel", ar: "فندق", pron: "/həʊˈtel/", ex: "We stayed in a small hotel.", col: ["stay in a hotel"], visual: "🏨" },
        { word: "beach", pos: "noun", meaning: "sand next to the sea", ar: "شاطئ", pron: "/biːtʃ/", ex: "We walked on the beach.", col: ["go to the beach"], visual: "🏖️" },
        { word: "photo", pos: "noun", meaning: "a picture from a camera", ar: "صورة", pron: "/ˈfəʊtəʊ/", ex: "I took some photos.", col: ["take a photo"], right: "take a photo", wrong: "make a photo", note: "We take photos.", visual: "📷" },
        { word: "museum", pos: "noun", meaning: "a building with old or interesting things", ar: "متحف", pron: "/mjuˈziːəm/", ex: "We visited a museum.", col: ["visit a museum"], visual: "🏛️" },
        { word: "souvenir", pos: "noun", meaning: "a small thing you buy to remember a place", ar: "تذكار", pron: "/ˌsuːvəˈnɪə/", ex: "I bought a souvenir for my mother.", col: ["buy a souvenir"], visual: "🎁" },
      ], "Holiday words"),
    ],
    exercises: [
      match("Match the word with its meaning.", [["hotel", "a place to stay"], ["beach", "sand next to the sea"], ["museum", "a building with old things"], ["souvenir", "a thing you buy to remember a place"]], "Each word has its own meaning."),
      fill("We stayed in a small ___ near the sea.", ["hotel"], "A hotel is a place to stay."),
      mist("Find the mistake.", ["I", "made", "some photos on holiday."], 1, "took", "We take photos."),
      mc("We visited a ___ and saw old boats.", ["museum", "hotel", "beach"], 0, "A museum has old things."),
      sa("You buy a ___ to remember a place.", ["souvenir"], "souvenir.", { hint: "s _ _ _ _ _ _ r" }),
      order("Put the words in the correct order.", ["We", "took", "many", "photos", "at", "the", "beach."], "word", "Subject + took + object + place."),
    ],
  },

  // ============================================================ WEEK 7 · READING & WRITING
  {
    slug: "beginner-reading-bad-luck-day",
    level: "BEGINNER", category: "READING", title: "Reading: A Day of Bad Luck", topic: "Past events",
    difficulty: "BASIC", minutes: 10, prereq: ["beginner-reading-mc-practice"],
    objective: "Follow the events of a short story in the Past Simple.",
    tags: ["reading", "reading-details", "past-simple", "narrative", "A1"],
    ref: { book: HW, level: "Beginner", area: "Reading", topic: "A bad day (Unit 9)" },
    sections: [
      text("A story about the past uses the **Past Simple**. Follow **what happened first, next and last**. Look for **time words** (last Monday, in the evening).", "Reading strategy"),
      passage("Example", "Last Friday, Maha went to the market. She bought some fruit, and she lost her keys.", "A tiny story"),
      list("Guided practice", ["Where did she go? → the market.", "What did she buy? → fruit.", "What did she lose? → her keys."]),
    ],
    exercises: [
      mc("What happened first on Monday?", ["He got up late.", "He lost his phone.", "He made dinner."], 0, "“He got up late.”", BAD_LUCK),
      mc("How did Tariq go to work?", ["by bus", "on foot, in the rain", "by car"], 1, "“He walked to work in the rain.”", BAD_LUCK),
      tf("Tariq had an umbrella.", false, "“he didn't have an umbrella”.", BAD_LUCK),
      mc("What did he break at work?", ["a cup", "a phone", "a bag"], 0, "“he broke a cup”.", BAD_LUCK),
      mc("What did he do in the evening?", ["He made dinner.", "He went shopping.", "He played football."], 0, "“he went home and made dinner”.", BAD_LUCK),
      mc("How was the food?", ["good", "bad", "cold"], 1, "“the food was bad”.", BAD_LUCK),
    ],
  },
  {
    slug: "beginner-reading-weekend-sur",
    level: "BEGINNER", category: "READING", title: "Reading: Huda's Weekend in Sur", topic: "A weekend trip",
    difficulty: "BASIC", minutes: 10, prereq: ["beginner-reading-bad-luck-day"],
    objective: "Find details about a past weekend in a short text.",
    tags: ["reading", "reading-details", "past-simple", "travel", "A1"],
    ref: { book: HW, level: "Beginner", area: "Reading", topic: "A weekend away (Unit 10)" },
    sections: [
      text("A text about a **weekend** gives **places, times** and **activities**. Find the **verb in the past** (went, visited, ate) to know what happened.", "Reading strategy"),
      passage("Example", "On Saturday, Ali went to Nizwa. He visited the fort and ate lunch in a café.", "A short text"),
      list("Guided practice", ["Where did he go? → Nizwa.", "What did he visit? → the fort."]),
    ],
    exercises: [
      mc("Where did Huda go?", ["to Sur", "to Muscat", "to Nizwa"], 0, "“Huda went to Sur.”", SUR_WEEKEND),
      mc("How did they travel?", ["by car", "by bus", "by plane"], 0, "“They travelled by car.”", SUR_WEEKEND),
      mc("What did they eat for lunch?", ["fish and rice", "chicken", "pizza"], 0, "“they ate fish and rice”.", SUR_WEEKEND),
      tf("They swam in the sea.", false, "“They didn't swim because it was windy.”", SUR_WEEKEND),
      mc("What did they do in the afternoon?", ["They walked on the beach.", "They visited the museum.", "They went home."], 0, "“In the afternoon, they walked on the beach.”", SUR_WEEKEND),
      mc("When did they come home?", ["in the morning", "in the evening", "at lunch"], 1, "“They came home in the evening.”", SUR_WEEKEND),
    ],
  },
  {
    slug: "beginner-writing-past-event-paragraph",
    level: "BEGINNER", category: "WRITING", title: "Writing About a Past Event (about 50 words)", topic: "Past paragraph",
    difficulty: "BASIC", minutes: 14, prereq: ["beginner-writing-editing-agreement-prepositions", "beginner-grammar-past-simple-did-didnt"],
    objective: "Write a guided paragraph about a past holiday or weekend using the Past Simple in time order.",
    tags: ["writing", "past-simple", "sequencing", "paragraph", "A1"],
    ref: { book: HW, level: "Beginner", area: "Writing", topic: "Writing about a past holiday or weekend (Unit 9-10)" },
    sections: [
      text("To write about a **past weekend or holiday**, follow **time order**: **first**, **then**, **after that**, **in the evening**. Use the **Past Simple** for every verb. Write about **50 words**.", "Explanation"),
      table("Notes: Huda's weekend", ["When", "What she did"], [["Saturday morning", "go to Sur by car"], ["lunch", "eat fish and rice"], ["afternoon", "walk on the beach"], ["evening", "come home"]]),
      annotated("Notes → paragraph", [
        ["Beginning", "Last weekend, Huda went to Sur by car."],
        ["Middle", "She ate fish and rice for lunch. In the afternoon, she walked on the beach."],
        ["End", "In the evening, she came home. It was a lovely weekend."],
      ]),
      list("Checklist", ["All verbs in the Past Simple (went, ate, walked, came).", "Time words: last weekend, in the afternoon, in the evening.", "Capital letters and full stops."]),
    ],
    exercises: [
      order("Put the sentences in the correct order.", ["Last weekend, Huda went to Sur.", "She ate fish and rice for lunch.", "In the afternoon, she walked on the beach.", "In the evening, she came home."], "paragraph", "Follow the time order."),
      fill("Last weekend, we ___ (go) to the beach and ___ (take) photos.", ["went", "took"], "go → went; take → took."),
      mist("Find the mistake.", ["Yesterday I", "go", "to the market."], 1, "went", "Past Simple: went."),
      mc("Which time word starts the evening part?", ["In the evening,", "Last year,", "Two days ago,"], 0, "In the evening."),
      order("Put the words in the correct order.", ["She", "walked", "on", "the", "beach", "in", "the", "afternoon."], "word", "Subject + verb + place + time."),
      mc("Which sentence is correct?", ["She eated fish.", "She ate fish.", "She eats fish yesterday."], 1, "eat → ate."),
    ],
  },

  // ============================================================ WEEK 8 · GRAMMAR
  {
    slug: "beginner-grammar-can-cant",
    level: "BEGINNER", category: "GRAMMAR", title: "can and can't", topic: "Ability",
    difficulty: "BASIC", minutes: 10, prereq: ["beginner-grammar-past-simple-did-didnt"],
    objective: "Say what you can and can't do, and ask about ability.",
    tags: ["grammar", "modal-verbs", "can", "abilities", "A1"],
    ref: { book: HW, level: "Beginner", area: "Grammar", topic: "can / can't (Unit 11)" },
    sections: [
      text("Use **can** to say what you are **able** to do. Use **can't** for what you are **not able** to do. The verb after can is in the **base form**.", "Explanation"),
      table("can / can't", ["Type", "Form", "Example"], [
        ["Positive", "subject + can + verb", "I can swim. She can cook."], ["Negative", "subject + can't + verb", "He can't drive."], ["Question", "Can + subject + verb?", "Can you swim?"], ["Short answers", "Yes, I can. / No, I can't.", "Can she cook? — Yes, she can."],
      ]),
      structure("Structure", "can + base verb (same for all persons)", "No -s: She can swim (not She cans swim). No to: I can swim (not I can to swim)."),
    ],
    exercises: [
      fill("I ___ swim, but I ___ drive. (can / can't)", ["can", "can't"], "can = able; can't = not able."),
      mc("She ___ speak three languages.", ["can", "cans", "is can"], 0, "No -s after can."),
      mist("Find the mistake.", ["He", "can swims", "very well."], 1, "can swim", "Base form after can."),
      order("Put the words in the correct order.", ["Can", "you", "speak", "English?"], "word", "Can + subject + verb."),
      sa("Give a short answer: “Can you drive?” (No) — No, I ___.", ["can't", "cannot"], "No, I can't.", { hint: "one word" }),
      order("Put the words in the correct order.", ["My", "brother", "can't", "swim."], "word", "Subject + can't + verb."),
    ],
  },
  {
    slug: "beginner-grammar-adverbs-of-manner",
    level: "BEGINNER", category: "GRAMMAR", title: "Adverbs of Manner: well, fast, fluently", topic: "Adverbs",
    difficulty: "BASIC", minutes: 8, prereq: ["beginner-grammar-can-cant"],
    objective: "Say how well you do things with adverbs such as well, fast and fluently.",
    tags: ["grammar", "adverbs", "manner", "abilities", "A1"],
    ref: { book: HW, level: "Beginner", area: "Grammar", topic: "Adverbs of manner (Unit 11)" },
    sections: [
      text("An **adverb of manner** says **how** you do something. Most add **-ly** to the adjective: slow → slow**ly**. Some are **irregular**: good → **well**, fast → **fast**.", "Explanation"),
      table("Adverbs", ["Adjective", "Adverb", "Example"], [
        ["slow", "slowly", "He walks slowly."], ["quiet", "quietly", "Please talk quietly."], ["fluent", "fluently", "She speaks English fluently."], ["good", "well", "I can swim well."], ["fast", "fast", "He runs fast."],
      ]),
      structure("Structure", "verb + (object) + adverb", "I can swim well. She speaks English fluently."),
    ],
    exercises: [
      fill("She can cook very ___. (good)", ["well"], "The adverb of good is well."),
      fill("Please speak more ___. (slow)", ["slowly"], "slow + ly."),
      mist("Find the mistake.", ["He can run", "good", "."], 1, "well", "Adverb: well."),
      match("Adjective → adverb.", [["quiet", "quietly"], ["slow", "slowly"], ["good", "well"], ["fast", "fast"]], "Most add -ly; good → well."),
      order("Put the words in the correct order.", ["She", "speaks", "English", "fluently."], "word", "Subject + verb + object + adverb."),
      mc("He drives ___. He is always late.", ["slowly", "slow", "slows"], 0, "The adverb is slowly."),
    ],
  },
  {
    slug: "beginner-grammar-like-would-like",
    level: "BEGINNER", category: "GRAMMAR", title: "like and would like", topic: "Offers and requests",
    difficulty: "BASIC", minutes: 8, prereq: ["beginner-grammar-adverbs-of-manner"],
    objective: "Use like for general likes and would like for polite requests and offers.",
    tags: ["grammar", "would-like", "requests", "food", "A1"],
    ref: { book: HW, level: "Beginner", area: "Grammar", topic: "would like / like (Unit 12)" },
    sections: [
      text("**Like** = you enjoy something **all the time**. **Would like** = you want something **now** (polite). Use it in a café or shop.", "Explanation"),
      table("like or would like?", ["Feature", "Meaning", "Example"], [["like", "general", "I like tea. (I enjoy it)"], ["would like", "want now (polite)", "I'd like a tea, please. (I want it now)"]]),
      structure("Structure", "I'd like + noun.   Would you like + noun?", "Answers: Yes, please. / No, thank you."),
    ],
    exercises: [
      fill("I ___ a coffee, please. (would like)", [["'d like", "would like"]], "Polite request: I'd like."),
      mc("Waiter: “What ___ you like to drink?”", ["do", "would", "are"], 1, "Would you like…?"),
      mist("Find the mistake.", ["I like", "a glass of water,", "please."], 1, "I'd like a glass of water", "For a request now, use would like."),
      match("General or now?", [["I like fish.", "general"], ["I'd like fish, please.", "now (request)"], ["Would you like tea?", "an offer"]], "like = general; would like = now."),
      order("Put the words in the correct order.", ["Would", "you", "like", "some", "tea?"], "word", "Would + you + like + noun."),
      sa("Answer politely: “Would you like some water?” — Yes, ___.", ["please"], "Yes, please.", { hint: "p _ _ _ _ _" }),
    ],
  },
  {
    slug: "beginner-grammar-some-any",
    level: "BEGINNER", category: "GRAMMAR", title: "some and any", topic: "Quantity",
    difficulty: "BASIC", minutes: 8, prereq: ["beginner-grammar-like-would-like"],
    objective: "Use some in positive sentences and any in negatives and questions.",
    tags: ["grammar", "quantifiers", "some-any", "food", "A1"],
    ref: { book: HW, level: "Beginner", area: "Grammar", topic: "some and any (Unit 12)" },
    sections: [
      text("Use **some** and **any** when you do not say the exact number. **Some** goes in **positive** sentences. **Any** goes in **negatives** and **questions**.", "Explanation"),
      table("some / any", ["Sentence", "Word", "Example"], [["Positive", "some", "I have some milk. There are some apples."], ["Negative", "any", "I don't have any milk. There aren't any apples."], ["Question", "any", "Do you have any milk? Are there any apples?"], ["Offer / request", "some", "Would you like some tea? Can I have some water?"]]),
      structure("Structure", "some + plural noun / uncountable noun\nany (negatives and questions)"),
    ],
    exercises: [
      fill("I have ___ apples. (positive)", ["some"], "Positive: some."),
      fill("There aren't ___ eggs. (negative)", ["any"], "Negative: any."),
      fill("Do you have ___ milk?", ["any"], "Question: any."),
      mc("Would you like ___ tea?", ["some", "any"], 0, "An offer uses some."),
      mist("Find the mistake.", ["I don't have", "some", "money."], 1, "any", "Negative: any."),
      match("some or any?", [["I have ___ bread. (+)", "some"], ["I don't have ___ bread. (−)", "any"], ["Have you got ___ bread? (?)", "any"]], "some in positives; any in negatives and questions."),
    ],
  },

  // ============================================================ WEEK 8 · VOCABULARY
  {
    slug: "beginner-vocab-verb-noun-collocations",
    level: "BEGINNER", category: "VOCABULARY", title: "Verb + Noun Collocations", topic: "Collocations",
    difficulty: "BASIC", minutes: 8, prereq: ["beginner-vocab-holiday-words"],
    objective: "Use common verb + noun partners: play the guitar, ride a bike, speak English, cook dinner.",
    tags: ["vocabulary", "collocations", "abilities", "listening-support", "A1"],
    ref: { book: HW, level: "Beginner", area: "Vocabulary", topic: "Verb + noun collocations (Unit 11)" },
    sections: [
      text("Some verbs and nouns always go together. Use them to say what you **can** and **can't** do."),
      table("Verb + noun", ["Verb", "Noun", "Example"], [
        ["play", "the guitar / the piano / football", "I can play the guitar."], ["ride", "a bike / a horse", "She can ride a horse."], ["speak", "English / French", "He can speak English."],
        ["cook", "dinner / rice", "I can cook dinner."], ["drive", "a car", "My father can drive a car."],
      ]),
    ],
    exercises: [
      match("Match the verb with the noun.", [["play", "the guitar"], ["ride", "a bike"], ["speak", "English"], ["cook", "dinner"], ["drive", "a car"]], "Learn the pairs."),
      fill("I can ___ a bike.", ["ride"], "ride a bike."),
      fill("She can ___ the piano.", ["play"], "play the piano."),
      mist("Find the mistake.", ["He can", "say", "English very well."], 1, "speak", "We speak a language."),
      order("Put the words in the correct order.", ["I", "can", "play", "the", "guitar."], "word", "Subject + can + verb + object."),
      sa("You ___ dinner in the kitchen.", ["cook"], "cook dinner.", { hint: "c _ _ k" }),
    ],
  },
  {
    slug: "beginner-vocab-shops-cafe",
    level: "BEGINNER", category: "VOCABULARY", title: "Shops, Amenities and the Café", topic: "Shopping and food",
    difficulty: "BASIC", minutes: 10, prereq: ["beginner-vocab-verb-noun-collocations"],
    objective: "Name shops and café items and order politely.",
    tags: ["vocabulary", "shopping", "food", "cafe", "listening-support", "A1"],
    ref: { book: HW, level: "Beginner", area: "Vocabulary", topic: "Shops, amenities, food and café vocabulary (Unit 12)" },
    sections: [
      text("In a **café** you can order **food and drinks**. Be polite: **I'd like … please.** In a **shop** you can ask: **How much is it?**"),
      table("At the café", ["Drinks", "Food"], [["tea, coffee, juice, water", "sandwich, cake, pizza, salad"]]),
      table("Shops", ["Shop", "You buy…"], [["supermarket", "food and drinks"], ["bookshop", "books"], ["pharmacy", "medicine"], ["clothes shop", "clothes"]]),
      list("Useful phrases", ["I'd like a coffee, please.", "How much is the cake?", "Can I have the bill, please?"]),
    ],
    exercises: [
      match("Where do you buy it?", [["books", "bookshop"], ["medicine", "pharmacy"], ["food", "supermarket"], ["clothes", "clothes shop"]], "Match the shop with what it sells."),
      mc("You order a hot drink. You say: “I'd like a ___, please.”", ["coffee", "cake", "sandwich"], 0, "Coffee is a hot drink."),
      fill("Can I have the ___, please? (to pay)", ["bill"], "You ask for the bill."),
      mist("Find the mistake.", ["I want", "a coffee,", "please."], 0, "I'd like", "Be polite: I'd like a coffee, please."),
      order("Put the words in the correct order.", ["How", "much", "is", "the", "cake?"], "word", "How much + is + the + noun?"),
      sa("A ___ sells books.", ["bookshop"], "A bookshop sells books.", { hint: "b _ _ _ _ _ _ p" }),
    ],
  },

  // ============================================================ WEEK 8 · READING & WRITING
  {
    slug: "beginner-reading-my-phone",
    level: "BEGINNER", category: "READING", title: "Reading: My Phone", topic: "Abilities",
    difficulty: "BASIC", minutes: 10, prereq: ["beginner-reading-weekend-sur"],
    objective: "Find what people can and can't do in a short text.",
    tags: ["reading", "reading-details", "can-cant", "technology", "A1"],
    ref: { book: HW, level: "Beginner", area: "Reading", topic: "The smartphone (Unit 11)" },
    sections: [
      text("This text uses **can** and **can't**. Underline **what people can do** and **what they can't do**.", "Reading strategy"),
      passage("Example", "My sister can play the piano, but she can't play the guitar.", "can and can't"),
      list("Guided practice", ["can → play the piano.", "can't → play the guitar."]),
    ],
    exercises: [
      mc("What can the writer do with a smartphone?", ["take photos and listen to music", "cook dinner", "drive a car"], 0, "“take photos, listen to music”.", PHONE),
      tf("The writer can cook dinner with the phone.", false, "“I can't cook dinner with it”.", PHONE),
      mc("What can the writer find with the phone?", ["recipes", "a car", "a house"], 0, "“I can find recipes!”", PHONE),
      tf("The writer's grandfather can use a smartphone.", false, "“My grandfather can't use a smartphone.”", PHONE),
      mc("What phone can the grandfather use?", ["an old phone", "a new phone", "no phone"], 0, "“He can use an old phone.”", PHONE),
      mc("What does the grandfather like?", ["talking to people", "taking photos", "cooking"], 0, "“I like to talk to people.”", PHONE),
    ],
  },
  {
    slug: "beginner-reading-meals-world",
    level: "BEGINNER", category: "READING", title: "Reading: Meals Around the World", topic: "Food and culture",
    difficulty: "BASIC", minutes: 10, prereq: ["beginner-reading-my-phone"],
    objective: "Find facts about meals in different countries.",
    tags: ["reading", "reading-details", "food", "culture", "A1"],
    ref: { book: HW, level: "Beginner", area: "Reading", topic: "Meal times around the world (Unit 12)" },
    sections: [
      text("This kind of text compares **different countries**. Note **the country** and **the fact** for each one.", "Reading strategy"),
      passage("Example", "In Oman, many people drink coffee with dates. In England, many people drink tea with milk.", "Two countries"),
      list("Guided practice", ["Oman → coffee with dates.", "England → tea with milk."]),
    ],
    exercises: [
      mc("How many meals do people often have a day?", ["three", "two", "five"], 0, "“three meals a day”.", MEALS),
      mc("In Oman, when do many families have a big lunch?", ["about one o'clock", "about nine o'clock", "about six o'clock"], 0, "“a big lunch at about one o'clock”.", MEALS),
      mc("In Spain, when do people often have dinner?", ["early", "late, at nine or ten", "at noon"], 1, "“dinner late, at about nine or ten o'clock”.", MEALS),
      mc("What do many people in Japan have for breakfast?", ["rice", "toast", "pizza"], 0, "“many people have rice for breakfast”.", MEALS),
      tf("A traditional English breakfast is fish and rice.", false, "“eggs, toast and tea”.", MEALS),
      mc("What is the main idea of the text?", ["Meals and meal times are different in different countries.", "Breakfast is the best meal.", "Everybody eats rice."], 0, "The text compares countries.", MEALS),
    ],
  },
  {
    slug: "beginner-writing-survey-to-paragraph",
    level: "BEGINNER", category: "WRITING", title: "Writing Workshop 2: From Survey Data to a 50-Word Paragraph", topic: "Survey-to-paragraph",
    difficulty: "BASIC", minutes: 14, prereq: ["beginner-writing-past-event-paragraph", "beginner-grammar-some-any"],
    objective: "Turn survey or table data into a paragraph of about 50 words using some / any, can / can't and would like.",
    tags: ["writing", "table-to-paragraph", "survey", "can-cant", "some-any", "A1"],
    ref: { book: HW, level: "Beginner", area: "Writing", topic: "Paragraph from survey / table data, ~50 words (Units 11-12)" },
    sections: [
      text("In **Task A** you can also get a **survey table**. Write **one paragraph** (about 50 words). Use **he / she** instead of the name, **can / can't** for abilities, **like / don't like** for food and **would like** for wishes.", "Explanation"),
      table("Survey table", ["Name", "Likes", "Doesn't like", "Can", "Can't", "Would like"], [["Huda", "chicken, rice", "fish", "swim, cook", "drive", "a coffee"]]),
      annotated("Table → paragraph", [
        ["Likes", "Huda likes chicken and rice, but she doesn't like fish."],
        ["Abilities", "She can swim and she can cook, but she can't drive."],
        ["Wish", "She would like some coffee, please."],
      ]),
      list("Checklist", ["Use she / he (not the name again).", "Use the verb -s: likes, doesn't like.", "Use some in positive wishes; any in negatives.", "Join ideas with and and but."]),
    ],
    exercises: [
      order("Put the sentences in the correct order.", ["Huda likes chicken and rice, but she doesn't like fish.", "She can swim and she can cook, but she can't drive.", "She would like some coffee, please."], "paragraph", "Likes, abilities, wish."),
      fill("She can swim ___ she can cook.", ["and"], "and adds two abilities."),
      fill("She can cook, ___ she can't drive.", ["but"], "but shows the difference."),
      mist("Find the mistake.", ["Huda", "like", "chicken and rice."], 1, "likes", "Huda = she: likes."),
      mc("Table: Omar · likes: pizza · can: play tennis · can't: swim. Which sentence is correct?", ["He likes pizza, and he can play tennis, but he can't swim.", "He like pizza, and he can plays tennis.", "Omar can't swimming."], 0, "Correct verb forms and linkers."),
      order("Put the words in the correct order.", ["She", "would", "like", "a", "cup", "of", "tea."], "word", "Subject + would like + object."),
    ],
  },
];

void [annotated, compare, examples, ms, tip];
