import { HW, annotated, compare, fill, list, match, mc, mist, order, passage, sa, structure, table, text, tf, tip, vocab, type SeedLesson } from "./dsl";

// Intermediate course, Units 10-12. Topics follow the academy's syllabus; all text is ORIGINAL.

const GARDEN = "THE GARDEN THAT WOULDN'T DIE\n\n(A fictional account)\n\nOn the edge of a quiet valley stands a walled garden that was left to grow wild for nearly fifty years. When a group of volunteers first pushed open its rusty gate, they found a jungle of brambles, fallen trees and broken greenhouses.\n\nThe volunteers had very little money, but they had determination. Working by themselves, they cleared the paths, repaired the walls and searched old records to find out what had once been planted there. Slowly, the vegetable beds and orchards reappeared, and rare fruit trees that everyone believed had died began to flower again.\n\nToday the garden is open to visitors, who often say that it is the most peaceful place they have ever seen. The volunteers, however, are more modest. “We didn't create anything,” says one of them. “We just gave it back the chance to grow.”";
const HOLIDAY = "THE HOLIDAY THAT WENT WRONG\n\nWe had planned the trip for a year. On the first night, however, the hotel told us that our room had been given to someone else. “I'm very sorry,” the receptionist said. “The manager will explain.”\n\nThe manager admitted that the hotel was full and promised that we would get a room the next day. My husband refused to leave the lobby. He warned the manager that he would write a bad review, and the manager explained that he couldn't do anything until morning.\n\nThe next day, the rain began. We asked the receptionist whether there was an indoor activity nearby, and she suggested visiting the museum. In the end, that was the best afternoon of the trip: we laughed so much that we forgot to be angry.";

export const INT_U10_U12: SeedLesson[] = [
  // ============================================================ UNIT 10
  {
    slug: "int-grammar-noun-phrases-articles",
    level: "INTERMEDIATE", category: "GRAMMAR", title: "Noun Phrases and Articles: a, an, the and Zero Article", topic: "Articles",
    difficulty: "CORE", minutes: 16, prereq: ["int-grammar-second-third-conditionals"],
    objective: "Build longer noun phrases and use the definite, indefinite and zero article accurately, including in generalisations.",
    tags: ["grammar", "articles", "noun-phrases", "generalisation", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Grammar", topic: "Noun phrases; articles (Unit 10)" },
    sections: [
      text("A **noun phrase** is a noun plus the words that describe it: **the old walled garden in the valley**. **Articles** show whether the noun is **new/general** (a/an, zero) or **known/specific** (the).", "Explanation"),
      table("Articles", ["Article", "Use", "Example"], [
        ["a / an", "first mention; one of many; jobs", "She bought a car. He is an engineer."],
        ["the", "already mentioned; unique; specific (defined)", "The car was red. The sun is hot. The book on the table is mine."],
        ["zero (no article)", "plural / uncountable in general; most names", "Books are expensive. Water is essential."],
      ]),
      list("Generalisations: pitfalls", ["**Plural or uncountable** without the: Students need support. (all students)", "**The + noun** for a specific group: The students in my class are friendly.", "**The + singular** for a whole species / invention (formal): The computer changed education.", "**Not** *The life is difficult* (in general) → Life is difficult."]),
      table("Order of a noun phrase", ["Determiner", "Opinion", "Size / age", "Colour / origin", "Material", "Noun"], [["a", "lovely", "old", "green", "wooden", "bench"], ["the", "beautiful", "small", "Omani", "silver", "dagger"]]),
      compare("Errors", [["I like the music.", "I like music. (in general)", "General: zero article."], ["She is doctor.", "She is a doctor.", "Jobs need a / an."], ["I went to the shop and bought a bread.", "I went to the shop and bought some bread.", "Bread is uncountable."]]),
    ],
    exercises: [
      mc("I love ___ music, especially classical. (in general)", ["the", "a", "no article"], 2, "General uncountable: zero article."),
      mc("She works as ___ engineer.", ["a", "an", "the"], 1, "Engineer starts with a vowel sound: an."),
      mc("I bought a car and a bike. ___ car is red.", ["A", "The", "No article"], 1, "Already mentioned: the."),
      mist("Find the mistake.", ["The life", "is", "difficult sometimes."], 0, "Life", "General: zero article."),
      fill("___ sun rises in the east. (write the article)", ["The"], "Unique: the sun."),
      order("Put the words in the correct order to make a noun phrase in a sentence.", ["She", "bought", "a", "lovely", "old", "wooden", "bench."], "word", "Determiner + opinion + age + material + noun."),
    ],
  },
  {
    slug: "int-grammar-reflexive-each-other",
    level: "INTERMEDIATE", category: "GRAMMAR", title: "Reflexive Pronouns and each other", topic: "Pronouns",
    difficulty: "CORE", minutes: 12, prereq: ["int-grammar-noun-phrases-articles"],
    objective: "Use reflexive pronouns and each other correctly and avoid over-use of reflexives.",
    tags: ["grammar", "reflexive-pronouns", "each-other", "pronouns", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Grammar", topic: "Reflexive pronouns; each other (Unit 10)" },
    sections: [
      text("**Reflexive pronouns** (myself, yourself, himself, herself, itself, ourselves, yourselves, themselves) are used when the **subject and the object are the same**. **Each other** is used when **two or more people do the same thing to one another**.", "Explanation"),
      table("Reflexive vs each other", ["Form", "Meaning", "Example"], [
        ["reflexive", "the doer and receiver are the same", "She taught herself to play the oud."],
        ["each other / one another", "reciprocal action", "They helped each other."],
        ["by + reflexive", "alone / without help", "I built the shelf by myself."],
        ["emphasis", "yourself, himself for emphasis", "The manager himself answered the phone."],
      ]),
      list("Do not use a reflexive after these verbs", ["wash, shave, dress, relax, concentrate (use without a reflexive): He got dressed. She washed quickly.", "meet, kiss, argue (each other is used): They met in Cairo.", "feel + adjective: I feel tired. (not *I feel myself tired*)"]),
      compare("Errors", [["They looked at themselves and smiled. (about each other)", "They looked at each other and smiled.", "Two people looking at one another."], ["I relaxed myself in the garden.", "I relaxed in the garden.", "No reflexive after relax."]]),
    ],
    exercises: [
      mc("She taught ___ to play the oud.", ["herself", "her", "each other"], 0, "Same subject and object: herself."),
      mc("Ali and Omar helped ___.", ["themselves", "each other", "them"], 1, "Reciprocal action: each other."),
      fill("I built the shelf all by ___.", ["myself"], "by myself = alone."),
      mist("Find the mistake.", ["I", "relaxed myself", "in the garden."], 1, "relaxed", "No reflexive after relax."),
      match("Reflexive or each other?", [["She looked at herself in the mirror.", "one person"], ["They looked at each other.", "two people"], ["We enjoyed ourselves.", "reflexive"], ["They respect one another.", "reciprocal"]], "Match by meaning."),
      mc("Which sentence is correct?", ["They argued with each other.", "They argued themselves.", "They argued each other."], 0, "With each other."),
    ],
  },
  {
    slug: "int-vocab-place-description",
    level: "INTERMEDIATE", category: "VOCABULARY", title: "Describing Places and Landscapes", topic: "Place vocabulary",
    difficulty: "CORE", minutes: 12, prereq: ["int-vocab-synonyms-nuance"],
    objective: "Describe places, buildings, gardens and landscapes using varied and precise vocabulary.",
    tags: ["vocabulary", "places", "landscape", "description", "listening-support", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Vocabulary", topic: "Describing places (Unit 10)" },
    sections: [
      text("Precise vocabulary for **places** helps you write **reports and descriptions**. Use a mix of **nouns for features** and **adjectives for atmosphere**."),
      table("Places", ["Category", "Words"], [
        ["Natural features", "valley · ridge · coastline · woodland · oasis · dune"],
        ["Buildings", "fort · courtyard · terrace · greenhouse · archway"],
        ["Atmosphere", "peaceful · tranquil · bustling · remote · picturesque · neglected"],
        ["Change", "restore · renovate · preserve · overgrown · abandoned"],
      ]),
      vocab([
        { word: "overgrown", pos: "adjective", meaning: "covered with plants that have grown too much", ar: "مغطّى بالأعشاب", pron: "/ˌəʊvəˈɡrəʊn/", ex: "The path was overgrown with brambles.", col: ["overgrown garden"], visual: "🌿" },
        { word: "restore", pos: "verb", meaning: "to return something to its original good condition", ar: "يرمّم", pron: "/rɪˈstɔː/", ex: "They restored the old fort.", col: ["restore a building"], visual: "🏰" },
        { word: "picturesque", pos: "adjective", meaning: "attractive in a way that looks like a picture", ar: "خلّاب", pron: "/ˌpɪktʃəˈresk/", ex: "It is a picturesque village.", col: ["a picturesque view"], visual: "🏞️" },
      ], "Place words"),
    ],
    exercises: [
      match("Match the word with its meaning.", [["overgrown", "covered with too many plants"], ["restore", "return to good condition"], ["picturesque", "attractive like a picture"], ["remote", "far from towns"]], "Learn the meaning with an example."),
      mc("The garden was ___: nobody had cared for it for years.", ["neglected", "bustling", "picturesque"], 0, "Neglected = not cared for."),
      fill("They plan to ___ the old fort to its original condition.", ["restore"], "restore = return to good condition."),
      mist("Find the mistake.", ["It is", "a picturesque", "and bustling desert with no people."], 2, "quiet / remote", "Bustling means full of activity; a desert with no people is quiet."),
      mc("Which adjective describes a quiet, calm place?", ["tranquil", "bustling", "crowded"], 0, "Tranquil = calm."),
      sa("A small enclosed area in the middle of a building is a ___", ["courtyard"], "courtyard.", { hint: "c _ _ _ _ _ _ _ d" }),
    ],
  },
  {
    slug: "int-reading-lost-garden",
    level: "INTERMEDIATE", category: "READING", title: "Reading: The Garden That Wouldn't Die", topic: "Descriptive report reading",
    difficulty: "CORE", minutes: 16, prereq: ["int-reading-money-matters"],
    objective: "Read a descriptive text about a restored place and identify sequence, cause and result.",
    tags: ["reading", "description", "sequence", "cause-effect", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Reading", topic: "A restored garden (Unit 10)" },
    sections: [
      text("Texts about **restoration or change** often follow a **time sequence**: before → action → result → today. Identify each stage, and notice the **cause and effect** links.", "Reading strategy"),
      passage("Example", "The old library had been closed for years. Volunteers repaired the roof and cleaned the shelves. Today it welcomes hundreds of readers.", "Before → action → today"),
      list("Guided practice", ["Before → closed for years.", "Action → repaired the roof and cleaned the shelves.", "Today → welcomes hundreds of readers."]),
    ],
    exercises: [
      mc("For how long was the garden left wild?", ["nearly fifty years", "five years", "a hundred years"], 0, "“nearly fifty years”.", GARDEN),
      mc("What did the volunteers find when they opened the gate?", ["a jungle of brambles and fallen trees", "a beautiful garden", "a car park"], 0, "“a jungle of brambles, fallen trees and broken greenhouses”.", GARDEN),
      mc("How did the volunteers find out what had once been planted?", ["by searching old records", "by asking tourists", "by guessing"], 0, "“searched old records”.", GARDEN),
      mc("What happened to the rare fruit trees?", ["They began to flower again.", "They were cut down.", "They were sold."], 0, "“began to flower again”.", GARDEN),
      mc("What quality do the volunteers show at the end?", ["modesty", "pride", "anger"], 0, "“We didn't create anything… just gave it back the chance to grow.”", GARDEN),
      tf("The volunteers had a lot of money.", false, "“very little money, but they had determination”.", GARDEN),
    ],
  },
  {
    slug: "int-writing-formal-descriptive-report",
    level: "INTERMEDIATE", category: "WRITING", title: "Formal Descriptive Writing: Places and Short Reports", topic: "Formal report",
    difficulty: "CHALLENGING", minutes: 20, prereq: ["int-writing-descriptive-adverbs", "int-writing-professional-correspondence"],
    objective: "Write a short formal report describing a place with headings, objective language and recommendations.",
    tags: ["writing", "report", "formal-writing", "description", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Writing", topic: "Formal descriptive report (Unit 10)" },
    sections: [
      text("A **formal report** presents information **clearly and objectively**. It uses **headings**, **impersonal language** (the passive, it is …) and often ends with **recommendations**.", "Explanation"),
      table("Structure of a short report", ["Section", "Content", "Language"], [
        ["Title", "Report on … / Proposal for …", "—"],
        ["Introduction", "Purpose of the report", "The aim of this report is to …"],
        ["Findings", "Description of the place (facts)", "The garden is located … It contains …"],
        ["Recommendations", "Suggestions", "It is recommended that … / I would suggest …"],
      ]),
      annotated("Model extract", [
        ["Introduction", "The aim of this report is to describe the walled garden and to consider its suitability for school visits."],
        ["Findings", "The garden, which was restored in 2021, contains several orchards and a small greenhouse. It is open daily from nine until five."],
        ["Recommendation", "It is recommended that visits be organised on weekday mornings, when the garden is quietest."],
      ]),
      tip("Avoid contractions, personal opinions (I love it) and informal words (nice, great). Use neutral vocabulary instead.", "Style"),
    ],
    exercises: [
      order("Put the report sections in order.", ["Title", "Introduction", "Findings", "Recommendations"], "paragraph", "Title, introduction, findings, recommendations."),
      mc("Which sentence is suitable for a formal report?", ["It is recommended that visits take place in the morning.", "I think you should go in the morning, it's great.", "Go in the morning!"], 0, "Impersonal and objective."),
      mist("Find the mistake (register).", ["The garden", "is really nice", "and contains several orchards."], 1, "is attractive", "Avoid informal nice/really in formal reports."),
      fill("The aim of this report ___ (be) to describe the garden.", ["is"], "The aim … is to."),
      mc("Which heading would you expect in a report?", ["Recommendations", "Once upon a time", "Dear Sir"], 0, "A report ends with recommendations."),
      match("Which part?", [["The aim of this report is to …", "introduction"], ["The garden contains an orchard.", "findings"], ["It is recommended that …", "recommendations"]], "Match the language with the section."),
    ],
  },

  // ============================================================ UNIT 11
  {
    slug: "int-grammar-modals-probability-past",
    level: "INTERMEDIATE", category: "GRAMMAR", title: "Modals of Probability in the Past: must have, might have, can't have", topic: "Modals of deduction",
    difficulty: "CHALLENGING", minutes: 16, prereq: ["int-grammar-reflexive-each-other", "int-grammar-modals-obligation"],
    objective: "Make deductions about the past with must have, might have, could have and can't have.",
    tags: ["grammar", "modal-verbs", "deduction", "probability", "past-modals", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Grammar", topic: "Modals of probability in the past (Unit 11)" },
    sections: [
      text("We use **modal + have + past participle** to say **how sure we are** about something that happened in the past, based on **evidence**.", "Explanation"),
      table("Degrees of certainty", ["Certainty", "Modal", "Example"], [
        ["almost certain (yes)", "must have + participle", "He must have left already: his coat has gone."],
        ["possible", "might / may / could have + participle", "She might have missed the bus."],
        ["almost certain (no)", "can't / couldn't have + participle", "He can't have seen us: he was in another country."],
      ]),
      compare("Common mistake", [["He mustn't have seen us.", "He can't have seen us.", "The negative deduction is can't have, not mustn't have."], ["She must have went.", "She must have gone.", "Use the past participle."]]),
      tip("Use these forms only for deduction (guessing from evidence). For certain facts use the past simple.", "Note"),
    ],
    exercises: [
      mc("The lights are off and the car has gone. They ___ already left.", ["must have", "can't have", "mustn't have"], 0, "Strong positive deduction: must have."),
      mc("She didn't answer, but she ___ missed my call: her phone is always on silent.", ["might have", "can't have", "mustn't have"], 0, "Possibility: might have."),
      mc("He ___ seen us. He was in another country.", ["must have", "can't have", "might"], 1, "Strong negative deduction: can't have."),
      mist("Find the mistake.", ["He", "mustn't have", "seen us."], 1, "can't have", "The negative of must have is can't have."),
      fill("She looks very tired. She ___ have slept well.", ["can't"], "Negative deduction: can't have."),
      order("Put the words in the correct order.", ["They", "must", "have", "forgotten", "the", "meeting."], "word", "Subject + must have + past participle."),
    ],
  },
  {
    slug: "int-vocab-proverbs",
    level: "INTERMEDIATE", category: "VOCABULARY", title: "English Proverbs and Their Meanings", topic: "Proverbs",
    difficulty: "CORE", minutes: 12, prereq: ["int-vocab-place-description"],
    objective: "Understand common English proverbs and use them appropriately in speech and writing.",
    tags: ["vocabulary", "proverbs", "idioms", "culture", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Vocabulary", topic: "Proverbs (Unit 11)" },
    sections: [
      text("**Proverbs** are short, well-known sayings that express **general advice** or **common experience**. They are used in **speech and essays**, but sparingly, because overuse sounds unnatural."),
      table("Common proverbs", ["Proverb", "Meaning", "When to use"], [
        ["Actions speak louder than words.", "What you do matters more than what you say.", "When someone promises but does not act"],
        ["A stitch in time saves nine.", "Fix small problems early to avoid bigger ones.", "Advice about maintenance"],
        ["Don't count your chickens before they hatch.", "Do not assume something will succeed before it does.", "Warning against over-confidence"],
        ["Better late than never.", "It's better to do something late than not at all.", "Someone arrives or finishes late"],
        ["Two heads are better than one.", "Working together gives better results.", "Encouraging teamwork"],
        ["Practice makes perfect.", "You improve with repeated practice.", "Learning a skill"],
      ]),
      tip("Many languages have proverbs with a similar idea. Try comparing an English proverb with one from your own language.", "Compare"),
    ],
    exercises: [
      match("Match the proverb with its meaning.", [["Practice makes perfect.", "You improve with repeated practice."], ["Two heads are better than one.", "Teamwork gives better results."], ["Better late than never.", "Doing something late is better than not at all."], ["Actions speak louder than words.", "What you do matters more than what you say."]], "Understand the idea, not the words."),
      mc("Ali promised to help but never did. Which proverb fits?", ["Actions speak louder than words.", "Practice makes perfect.", "Two heads are better than one."], 0, "Promises without actions."),
      mc("“Don't count your chickens before they hatch” warns against being ___.", ["over-confident", "generous", "slow"], 0, "Do not assume success in advance."),
      mist("Find the mistake.", ["A stitch", "in time", "saves seven."], 2, "nine", "The proverb is: A stitch in time saves nine."),
      fill("Practice makes ___.", ["perfect"], "Practice makes perfect."),
      mc("Which proverb encourages teamwork?", ["Two heads are better than one.", "Better late than never.", "A stitch in time saves nine."], 0, "Working together."),
    ],
  },
  {
    slug: "int-reading-proverbs-text",
    level: "INTERMEDIATE", category: "READING", title: "Reading: What Proverbs Tell Us", topic: "Reading for gist and inference",
    difficulty: "CHALLENGING", minutes: 16, prereq: ["int-reading-lost-garden"],
    objective: "Read a short reflective text on proverbs, summarise the main argument and infer the writer's view.",
    tags: ["reading", "gist", "inference", "culture", "proverbs", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Reading", topic: "Proverbs (Unit 11)" },
    sections: [
      text("For a reflective article, ask **What is the writer's main point?** and **How does the writer feel about it?** A good summary is **shorter than the text** and does not copy its words.", "Reading strategy"),
      passage("Example", "Proverbs are short, but they carry the experience of many generations. That is why they are still used today.", "Claim + reason"),
      list("Guided practice", ["Claim → proverbs carry experience.", "Reason → many generations.", "Result → still used today."]),
    ],
    exercises: [
      mc("What is the main idea of this short passage?", ["Proverbs carry the experience of many generations.", "Proverbs are difficult to learn.", "Proverbs are only used by old people."], 0, "The main claim of the passage.", "PROVERBS\n\nA proverb is a short saying that many people know. Most were created long ago, but they are still used because they express experiences that people share in every age. “Slow and steady wins the race” may come from a story about animals, but it also describes how many of us learn a language: a little every day, without rushing.\n\nHowever, proverbs should be used with care. Some advice contradicts other advice: “Look before you leap” tells us to be cautious, while “He who hesitates is lost” tells us to act quickly. Wise speakers therefore choose the proverb that fits the situation."),
      mc("Why does the writer mention “Slow and steady wins the race”?", ["to compare it with learning a language", "to tell a story about animals", "to criticise proverbs"], 0, "It describes how we learn a language.", "PROVERBS\n\nA proverb is a short saying that many people know. Most were created long ago, but they are still used because they express experiences that people share in every age. “Slow and steady wins the race” may come from a story about animals, but it also describes how many of us learn a language: a little every day, without rushing.\n\nHowever, proverbs should be used with care. Some advice contradicts other advice: “Look before you leap” tells us to be cautious, while “He who hesitates is lost” tells us to act quickly. Wise speakers therefore choose the proverb that fits the situation."),
      mc("Why should proverbs be used with care?", ["Some proverbs give opposite advice.", "They are always wrong.", "They are too long."], 0, "“Some advice contradicts other advice”.", "PROVERBS\n\nA proverb is a short saying that many people know. Most were created long ago, but they are still used because they express experiences that people share in every age. “Slow and steady wins the race” may come from a story about animals, but it also describes how many of us learn a language: a little every day, without rushing.\n\nHowever, proverbs should be used with care. Some advice contradicts other advice: “Look before you leap” tells us to be cautious, while “He who hesitates is lost” tells us to act quickly. Wise speakers therefore choose the proverb that fits the situation."),
      mc("What do “Look before you leap” and “He who hesitates is lost” show?", ["opposite pieces of advice", "similar advice", "old stories"], 0, "One says be cautious, the other says act quickly.", "PROVERBS\n\nA proverb is a short saying that many people know. Most were created long ago, but they are still used because they express experiences that people share in every age. “Slow and steady wins the race” may come from a story about animals, but it also describes how many of us learn a language: a little every day, without rushing.\n\nHowever, proverbs should be used with care. Some advice contradicts other advice: “Look before you leap” tells us to be cautious, while “He who hesitates is lost” tells us to act quickly. Wise speakers therefore choose the proverb that fits the situation."),
      tf("The writer thinks proverbs should never be used.", false, "The writer says they should be used with care, not never.", "PROVERBS\n\nA proverb is a short saying that many people know. Most were created long ago, but they are still used because they express experiences that people share in every age. “Slow and steady wins the race” may come from a story about animals, but it also describes how many of us learn a language: a little every day, without rushing.\n\nHowever, proverbs should be used with care. Some advice contradicts other advice: “Look before you leap” tells us to be cautious, while “He who hesitates is lost” tells us to act quickly. Wise speakers therefore choose the proverb that fits the situation."),
      mc("What is the writer's final advice?", ["Choose the proverb that fits the situation.", "Never use proverbs.", "Learn all proverbs."], 0, "The last sentence.", "PROVERBS\n\nA proverb is a short saying that many people know. Most were created long ago, but they are still used because they express experiences that people share in every age. “Slow and steady wins the race” may come from a story about animals, but it also describes how many of us learn a language: a little every day, without rushing.\n\nHowever, proverbs should be used with care. Some advice contradicts other advice: “Look before you leap” tells us to be cautious, while “He who hesitates is lost” tells us to act quickly. Wise speakers therefore choose the proverb that fits the situation."),
    ],
  },
  {
    slug: "int-writing-evaluative-essay",
    level: "INTERMEDIATE", category: "WRITING", title: "Writing an Evaluative Essay", topic: "Evaluative essay",
    difficulty: "CHALLENGING", minutes: 20, prereq: ["int-writing-essay-2-argumentative"],
    objective: "Evaluate an idea, a saying or a policy by weighing its strengths and weaknesses and reaching a justified judgement.",
    tags: ["writing", "evaluation", "essay", "judgement", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Writing", topic: "Evaluative essay (Unit 11)" },
    sections: [
      text("An **evaluative essay** does more than describe: it **judges** how **good, useful or true** something is, using **criteria** and **evidence**. It ends with a **justified judgement**.", "Explanation"),
      table("Plan", ["Part", "Content"], [
        ["Introduction", "State the item and how you will evaluate it (your criteria)"],
        ["Strengths", "Evidence that it is good / useful / true"],
        ["Weaknesses", "Limitations, exceptions, counter-evidence"],
        ["Judgement", "Balanced overall decision with reasons"],
      ]),
      table("Evaluative language", ["Function", "Phrases"], [
        ["Positive", "is valuable because … · is effective in that … · has the advantage of …"],
        ["Negative", "is limited by … · fails to … · overlooks the fact that …"],
        ["Judgement", "On balance, … · Overall, … · I would argue that … is largely / partly true"],
      ]),
      annotated("Model", [
        ["Item", "The proverb “Practice makes perfect” is widely accepted, but is it entirely true?"],
        ["Strength", "It is valuable because regular practice clearly improves skills such as language learning."],
        ["Weakness", "However, it overlooks the fact that poor practice can create bad habits."],
        ["Judgement", "On balance, practice is necessary but not sufficient: it must be guided and purposeful."],
      ]),
    ],
    exercises: [
      order("Put the parts of the evaluative essay in order.", ["Introduction with criteria", "Strengths", "Weaknesses", "Justified judgement"], "paragraph", "Introduce, strengths, weaknesses, judgement."),
      mc("Which sentence gives a JUDGEMENT?", ["On balance, practice is necessary but not sufficient.", "Practice is what we do.", "Some people practise."], 0, "On balance = overall judgement."),
      mc("Which phrase introduces a weakness?", ["However, it overlooks the fact that …", "It is valuable because …", "Firstly, …"], 0, "Overlooks = weakness."),
      mist("Find the mistake (evaluation).", ["The proverb is", "totally", "true in every case."], 1, "largely", "An evaluation avoids absolute claims."),
      fill("On ___, the proverb is largely true. (balance)", ["balance"], "On balance = overall."),
      mc("What does an evaluative essay require?", ["a judgement supported by evidence", "a story", "a list of facts"], 0, "Evaluate = judge with reasons."),
    ],
  },

  // ============================================================ UNIT 12
  {
    slug: "int-grammar-reported-speech",
    level: "INTERMEDIATE", category: "GRAMMAR", title: "Reported Speech: Statements, Backshift and Time Words", topic: "Reported speech",
    difficulty: "CHALLENGING", minutes: 18, prereq: ["int-grammar-modals-probability-past"],
    objective: "Report statements accurately using backshift and change pronouns, time and place words.",
    tags: ["grammar", "reported-speech", "backshift", "statements", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Grammar", topic: "Reported statements (Unit 12)" },
    sections: [
      text("In **reported speech** we tell someone what another person said **without quoting exactly**. The verb usually moves **one tense back** (backshift), and **pronouns, time and place words** change.", "Explanation"),
      table("Backshift", ["Direct speech", "Reported speech"], [
        ["Present Simple: “I work here.”", "Past Simple: She said (that) she worked there."],
        ["Present Continuous: “I'm working.”", "Past Continuous: She said she was working."],
        ["Past Simple: “I left.”", "Past Perfect: She said she had left."],
        ["Present Perfect: “I've finished.”", "Past Perfect: She said she had finished."],
        ["will: “I'll call.”", "would: She said she would call."],
        ["can: “I can swim.”", "could: She said she could swim."],
      ]),
      table("Time and place words", ["Direct", "Reported"], [["today", "that day"], ["tomorrow", "the next day / the following day"], ["yesterday", "the day before"], ["now", "then"], ["here", "there"], ["this", "that"]]),
      tip("Backshift is optional if the statement is still true or was said very recently: She said she works here.", "Note"),
      compare("Errors", [["She said me that she was tired.", "She told me that she was tired. / She said that she was tired.", "tell + person; say without a person."], ["He said he will come tomorrow.", "He said he would come the next day.", "Backshift and time word change."]]),
    ],
    exercises: [
      mc("“I work here,” she said. → She said she ___ there.", ["worked", "works", "had worked"], 0, "Present Simple → Past Simple; here → there."),
      mc("“I've finished,” he said. → He said he ___ finished.", ["has", "had", "would"], 1, "Present Perfect → Past Perfect."),
      fill("“I'll call you tomorrow,” she said. → She said she ___ call me the next day.", ["would"], "will → would; tomorrow → the next day."),
      mist("Find the mistake.", ["She", "said me", "that she was tired."], 1, "told me", "tell + person; say has no person."),
      match("Direct → reported.", [["today", "that day"], ["tomorrow", "the next day"], ["yesterday", "the day before"], ["now", "then"]], "Time words change in reported speech."),
      order("Put the words in the correct order.", ["He", "said", "he", "had", "left", "the", "day", "before."], "word", "Reported statement with Past Perfect."),
    ],
  },
  {
    slug: "int-grammar-reported-questions-verbs",
    level: "INTERMEDIATE", category: "GRAMMAR", title: "Reported Questions and Reporting Verbs", topic: "Reported speech",
    difficulty: "CHALLENGING", minutes: 16, prereq: ["int-grammar-reported-speech"],
    objective: "Report questions with statement word order and use verbs such as refuse, admit, warn and explain.",
    tags: ["grammar", "reported-speech", "reported-questions", "reporting-verbs", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Grammar", topic: "Reported questions; reporting verbs (Unit 12)" },
    sections: [
      text("Reported questions use **statement word order** (no auxiliary do, no question mark). **Reporting verbs** show **the purpose** of what was said in a single word.", "Explanation"),
      table("Reported questions", ["Direct", "Reported"], [
        ["“Where do you live?”", "She asked me where I lived."],
        ["“Are you coming?”", "She asked if / whether I was coming."],
        ["“What time did it start?”", "He asked what time it had started."],
      ]),
      table("Reporting verbs and patterns", ["Verb", "Pattern", "Example"], [
        ["refuse", "+ to-infinitive", "He refused to leave."],
        ["admit", "+ -ing / that", "She admitted making a mistake."],
        ["warn", "+ object + (not) to-infinitive", "They warned us not to swim."],
        ["explain", "+ that / how / why", "He explained that the room was full."],
        ["suggest", "+ -ing / that", "She suggested visiting the museum."],
        ["promise", "+ to-infinitive / that", "He promised to write."],
      ]),
      compare("Errors", [["She asked where did I live.", "She asked where I lived.", "Statement order."], ["He refused leaving.", "He refused to leave.", "refuse + infinitive."], ["She suggested to visit the museum.", "She suggested visiting the museum.", "suggest + -ing."]]),
    ],
    exercises: [
      mc("“Where do you live?” → She asked me where ___.", ["I lived", "did I live", "do I live"], 0, "Statement order; backshift."),
      mc("“Are you coming?” → She asked me ___ I was coming.", ["if", "that", "what"], 0, "Yes/no questions use if or whether."),
      mc("He ___ to leave the lobby until his room was ready.", ["refused", "admitted", "suggested"], 0, "refuse + to-infinitive."),
      mist("Find the mistake.", ["She", "suggested to visit", "the museum."], 1, "suggested visiting", "suggest + -ing."),
      fill("They warned us ___ to swim in the sea. (write the negative word)", ["not"], "warn + object + not + to-infinitive."),
      match("Which reporting verb?", [["“I'm sorry, I broke it.”", "admit"], ["“I won't go!”", "refuse"], ["“Don't touch that!”", "warn"], ["“Let's go to the museum.”", "suggest"]], "Choose the verb that shows the purpose."),
    ],
  },
  {
    slug: "int-vocab-reporting-verbs-phrases",
    level: "INTERMEDIATE", category: "VOCABULARY", title: "Reporting Verbs and Communication Vocabulary", topic: "Communication verbs",
    difficulty: "CORE", minutes: 12, prereq: ["int-vocab-proverbs"],
    objective: "Use a range of reporting and speaking verbs to show the purpose and manner of communication.",
    tags: ["vocabulary", "reporting-verbs", "communication", "manner", "listening-support", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Vocabulary", topic: "Reporting and communication verbs (Unit 12)" },
    sections: [
      text("Instead of always writing *said*, use verbs that show **purpose** and **manner**. This makes your writing more precise and interesting."),
      table("Purpose", ["Verb", "Meaning", "Example"], [
        ["announce", "make a public statement", "The manager announced the results."],
        ["complain", "say you are unhappy", "He complained about the noise."],
        ["insist", "say firmly", "She insisted on paying."],
        ["deny", "say something is not true", "He denied breaking the window."],
        ["persuade", "convince someone to do something", "I persuaded her to come."],
      ]),
      table("Manner", ["Verb", "Meaning"], [["whisper", "speak very quietly"], ["mutter", "speak quietly and unclearly, often complaining"], ["shout", "speak very loudly"], ["stammer", "speak with pauses because of nervousness"]]),
    ],
    exercises: [
      match("Match the verb with its meaning.", [["deny", "say something is not true"], ["insist", "say firmly"], ["mutter", "speak quietly and unclearly"], ["announce", "make a public statement"]], "Choose verbs by purpose."),
      mc("He ___ breaking the window, but everyone saw him.", ["denied", "announced", "whispered"], 0, "deny = say it is not true."),
      fill("She ___ on paying for dinner. (firmly said)", ["insisted"], "insist on + -ing."),
      mist("Find the mistake.", ["He", "denied to break", "the window."], 1, "denied breaking", "deny + -ing."),
      mc("She spoke so quietly that I could hardly hear. She ___.", ["whispered", "shouted", "announced"], 0, "Whisper = speak very quietly."),
      sa("To convince someone to do something is to ___ them.", ["persuade"], "persuade.", { hint: "p _ _ _ _ _ _ _" }),
    ],
  },
  {
    slug: "int-reading-holiday-from-hell",
    level: "INTERMEDIATE", category: "READING", title: "Reading: The Holiday That Went Wrong", topic: "Reported speech in narrative",
    difficulty: "CORE", minutes: 16, prereq: ["int-reading-proverbs-text"],
    objective: "Read a narrative told mostly in reported speech and identify who said what and why.",
    tags: ["reading", "narrative", "reported-speech", "humour", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Reading", topic: "The holiday from hell (Unit 12)" },
    sections: [
      text("Narratives often report speech with **reporting verbs** (admitted, warned, suggested). Ask **Who said it? To whom? Why?** and notice **how the tone changes** as the story develops.", "Reading strategy"),
      passage("Example", "The guide warned us not to swim, so we sat on the beach and watched the waves.", "warn + not to-infinitive"),
      list("Guided practice", ["Who → the guide.", "What → warned us not to swim.", "Result → they sat on the beach."]),
    ],
    exercises: [
      mc("What was wrong with the hotel room?", ["It had been given to someone else.", "It was too small.", "It had no bed."], 0, "“our room had been given to someone else”.", HOLIDAY),
      mc("What did the manager promise?", ["a room the next day", "a refund", "a free meal"], 0, "“promised that we would get a room the next day”.", HOLIDAY),
      mc("What did the husband warn the manager?", ["He would write a bad review.", "He would leave.", "He would call the police."], 0, "“warned the manager that he would write a bad review”.", HOLIDAY),
      mc("What did the receptionist suggest?", ["visiting the museum", "swimming", "going home"], 0, "“suggested visiting the museum”.", HOLIDAY),
      mc("How did the tone of the story change?", ["from angry to cheerful", "from cheerful to angry", "from sad to angry"], 0, "They laughed so much that they forgot to be angry.", HOLIDAY),
      tf("The holiday was perfect from the first night.", false, "The room problem on the first night.", HOLIDAY),
    ],
  },
  {
    slug: "int-writing-biography-report",
    level: "INTERMEDIATE", category: "WRITING", title: "Writing Biographies and Formal Reports", topic: "Biography and report writing",
    difficulty: "CHALLENGING", minutes: 20, prereq: ["int-writing-formal-descriptive-report", "int-grammar-reported-speech"],
    objective: "Write a short biography and a formal report that summarises events and uses reported speech.",
    tags: ["writing", "biography", "report", "reported-speech", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Writing", topic: "Biographies; formal reports (Unit 12)" },
    sections: [
      text("A **biography** tells the story of a person's life in **chronological order**. A **formal report** summarises **events or findings** in a neutral style. Both use **past tenses** and often **reported speech** for what people said.", "Explanation"),
      table("Biography structure", ["Part", "Content", "Tenses"], [
        ["Opening", "Who the person is and why they are notable", "Present Simple / Past Simple"],
        ["Early life", "Birth, family, education", "Past Simple, Past Perfect"],
        ["Career / achievements", "Key events in order", "Past Simple + time expressions"],
        ["Later life / legacy", "Recent events and impact", "Present Perfect, Past Simple"],
      ]),
      annotated("Model biography extract", [
        ["Opening", "Dr Salma Al Harthy is a marine biologist who has spent her life protecting coral reefs."],
        ["Early life", "She was born in Sohar in 1985 and had always been fascinated by the sea."],
        ["Career", "After studying in Scotland, she returned to Oman, where she founded a research team in 2012."],
        ["Reported speech", "She explained that reefs protect coastlines and that their loss would affect thousands of people."],
      ]),
      tip("In a formal report on an incident: use the passive (the guests were informed), reporting verbs (the manager stated that …) and neutral language.", "Report language"),
    ],
    exercises: [
      order("Put the biography parts in order.", ["Opening", "Early life", "Career and achievements", "Legacy"], "paragraph", "Chronological order."),
      mc("Which sentence is suitable for the EARLY LIFE part?", ["She was born in Sohar in 1985.", "She has published thirty papers.", "She will retire soon."], 0, "Early life = born, family, education."),
      mist("Find the mistake.", ["She explained", "that reefs protects", "coastlines."], 1, "protect", "Plural subject reefs: protect."),
      fill("The manager ___ (state) that the room had been given to another guest. (report, past)", ["stated"], "reporting verb in the past."),
      mc("Which sentence is suitable for a formal report about an incident?", ["The guests were informed that the room was unavailable.", "The guests were so angry!", "Everyone freaked out."], 0, "Passive, neutral."),
      mc("What order does a biography usually follow?", ["chronological", "random", "alphabetical"], 0, "Life events in time order."),
    ],
  },
];

void [compare, list, sa, structure, tip, vocab, annotated, passage, tf, table, text];
