import { HW, annotated, compare, fill, flow, list, match, mc, mist, order, passage, sa, structure, table, text, tf, tip, vocab, type SeedLesson } from "./dsl";

// Intermediate course, Units 4-6. Topics follow the academy's syllabus; all text is ORIGINAL.

const FLAT = "THE FLAT ON ORCHARD ROAD\n\nWhen Nadia first saw the flat, she almost didn't go in. The stairs were narrow and the paint was peeling. The landlord, a quiet man in a grey cap, unlocked the door without a word.\n\nInside, the rooms were small but full of light. In the kitchen there was an old table with one short leg, and someone had left a jar of dried lavender on the windowsill. “You must sign today if you want it,” said the landlord. “Other people are coming this afternoon.”\n\nNadia walked slowly from room to room. She should really compare it with other flats, she thought, and she ought to ask about the rent. But the light in the bedroom felt like a decision already made. “I'll take it,” she said. Only later, when she was carrying her boxes up the stairs, did she wonder whether she'd been too quick.";
const FOREST = "THE MAN WHO PLANTED A HILLSIDE\n\n(A fictional story)\n\nWhen Karim moved to the village, the hills above it were bare. Rain had washed the soil away, and the wells were running dry. Every morning, Karim walked slowly up the slope, carefully carrying a bucket of water and a bag of seedlings.\n\nAt first, the villagers laughed. “You will never finish,” they said. Karim answered calmly, “I'm not planning to finish. I'm planning to begin.” He planted patiently, one tree at a time, and he watered each one gently.\n\nYears passed. The trees grew tall and thick, and the roots held the soil together. Slowly, the springs returned. Birds came back, and children played happily in the shade. Today, Karim's hillside is green all year round, and people say that, if you listen carefully, you can hear the forest breathing.";
const WHOS_WHO = "WHO'S WHO: THREE LOCAL VOICES\n\nDr Salma Al Harthy is a marine biologist who studies coral reefs along the Gulf of Oman. She has published more than thirty papers, and about 60 percent of her research is done underwater.\n\nOmar Baqir, whose bakery opened in 2012, is known for bread that people queue for from six in the morning. His shop, which employs eleven people, sells nearly 2,000 loaves a day.\n\nMaryam Kazim, who teaches mathematics, is the person that students go to when they are stuck. Her classes, where the ratio of teacher to student is about one to eighteen, are famous for being fun.";

export const INT_U4_U6: SeedLesson[] = [
  // ============================================================ UNIT 4
  {
    slug: "int-grammar-modals-obligation",
    level: "INTERMEDIATE", category: "GRAMMAR", title: "Modals of Obligation and Permission: must, have to, should, can, may", topic: "Modal verbs",
    difficulty: "CORE", minutes: 16, prereq: ["int-grammar-past-narrative-tenses"],
    objective: "Distinguish subjective and objective obligation, advice, permission and prohibition with modal verbs.",
    tags: ["grammar", "modal-verbs", "obligation", "permission", "advice", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Grammar", topic: "Modal verbs of obligation (Unit 4)" },
    sections: [
      text("Modal verbs express **the speaker's attitude**: how strong an obligation is, and **who decides** it. The key contrast is between **subjective** obligation (my opinion or decision) and **objective** obligation (rules and laws).", "Explanation"),
      table("Obligation, advice, permission", ["Meaning", "Modal", "Example"], [
        ["strong obligation (speaker's feeling)", "must", "I must call my mother tonight."],
        ["obligation from a rule or law", "have to", "Drivers have to wear seat belts."],
        ["no obligation", "don't have to / needn't", "You don't have to come if you're busy."],
        ["prohibition", "mustn't / can't", "You mustn't smoke here."],
        ["advice", "should / ought to", "You should see a doctor."],
        ["permission (formal → informal)", "may / can", "May I sit here? Can I borrow your pen?"],
      ]),
      compare("Common confusions", [["You mustn't come if you don't want to.", "You don't have to come if you don't want to.", "Mustn't means prohibited; don't have to means not necessary."], ["I must to go now.", "I must go now.", "No to after a modal."], ["She musts leave.", "She must leave.", "Modals have no -s."]]),
      tip("Have to has past and future forms (had to, will have to). Must has no past form: use had to.", "Remember"),
    ],
    exercises: [
      mc("In this country, drivers ___ wear a seat belt. It's the law.", ["have to", "should", "may"], 0, "A law = objective obligation: have to."),
      mc("You ___ smoke in the hospital. It is not allowed.", ["don't have to", "mustn't", "needn't to"], 1, "Mustn't = prohibited."),
      mc("You ___ come to the party if you don't feel like it. It's your choice.", ["mustn't", "don't have to", "can't not"], 1, "No obligation: don't have to."),
      fill("Yesterday I ___ (have to) work late, so I missed the film.", ["had to"], "Past of must / have to: had to."),
      mist("Find the mistake.", ["We", "must to", "leave before ten."], 1, "must", "No to after a modal."),
      match("Which meaning?", [["You should see a doctor.", "advice"], ["You mustn't park here.", "prohibition"], ["Do I have to pay?", "asking about obligation"], ["May I come in?", "formal permission"]], "Match the modal to its meaning."),
    ],
  },
  {
    slug: "int-vocab-story-literary",
    level: "INTERMEDIATE", category: "VOCABULARY", title: "Vocabulary for Stories: Setting, Character and Emotion", topic: "Narrative vocabulary",
    difficulty: "CORE", minutes: 14, prereq: ["int-vocab-past-forms-time-expressions"],
    objective: "Use more precise vocabulary to describe settings, actions and feelings in a narrative.",
    tags: ["vocabulary", "narrative", "descriptive-language", "verbs-of-movement", "listening-support", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Vocabulary", topic: "Literary/story vocabulary (Unit 4)" },
    sections: [
      text("Strong narrative writing depends on **precise verbs and adjectives**. Replace general words (walk, look, said, sad) with more specific ones that show **manner and feeling**."),
      table("Replace weak words", ["Weak", "More precise", "Example"], [
        ["walk", "stroll · stride · wander · limp", "She strode into the room."],
        ["look", "glance · stare · gaze · peer", "He glanced at his watch."],
        ["said", "whispered · muttered · announced · replied", "“Be quiet,” she whispered."],
        ["sad", "miserable · heartbroken · gloomy", "He felt miserable after the news."],
        ["scared", "terrified · anxious · uneasy", "She felt uneasy in the empty street."],
      ]),
      vocab([
        { word: "peeling", pos: "adjective", meaning: "coming off in thin pieces, like old paint", ar: "متقشّر", pron: "/ˈpiːlɪŋ/", ex: "The paint on the door was peeling.", col: ["peeling paint"], visual: "🚪" },
        { word: "hesitate", pos: "verb", meaning: "to pause before doing something because you are not sure", ar: "يتردّد", pron: "/ˈhezɪteɪt/", ex: "She hesitated before opening the letter.", col: ["hesitate to ask"], visual: "🤔" },
        { word: "glimpse", pos: "noun/verb", meaning: "a very quick look", ar: "لمحة", pron: "/ɡlɪmps/", ex: "He caught a glimpse of her in the crowd.", col: ["catch a glimpse of"], visual: "👀" },
        { word: "decision", pos: "noun", meaning: "a choice you make after thinking", ar: "قرار", pron: "/dɪˈsɪʒn/", ex: "It was a difficult decision.", col: ["make a decision"], visual: "⚖️" },
      ], "Story words"),
    ],
    exercises: [
      match("Match the general word with a more precise one.", [["walk slowly and relaxed", "stroll"], ["look quickly", "glance"], ["say very quietly", "whisper"], ["very afraid", "terrified"]], "Precise words give the reader a clearer picture."),
      mc("She ___ before opening the letter because she was afraid of the news.", ["hesitated", "glimpsed", "strolled"], 0, "Hesitate = pause because you are unsure."),
      fill("He caught a ___ of his old friend in the crowd, but then lost sight of him.", ["glimpse"], "a glimpse = a very quick look."),
      mist("Find the mistake.", ["She", "did", "a difficult decision about the job."], 1, "made", "The natural collocation is make a decision."),
      mc("Which sentence is more vivid?", ["The man walked into the room.", "The man limped into the room, leaning heavily on his stick.", "The man went into the room."], 1, "Specific verb + detail."),
      sa("A quick look at something is a ___", ["glimpse", "glance"], "a glimpse / glance.", { hint: "g _ _ _ _ _ _" }),
    ],
  },
  {
    slug: "int-reading-flat-story",
    level: "INTERMEDIATE", category: "READING", title: "Reading: The Flat on Orchard Road", topic: "Narrative reading",
    difficulty: "CORE", minutes: 16, prereq: ["int-reading-welcoming-neighbour"],
    objective: "Understand a short story, track a character's decisions and infer feelings from small details.",
    tags: ["reading", "narrative", "reading-inference", "character", "modal-verbs", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Reading", topic: "Nancy's flat (Unit 4)" },
    sections: [
      text("In a story, **small details** (the state of a room, a gesture) often reveal **feelings and decisions**. Track how the character **changes** between the beginning and the end.", "Reading strategy"),
      passage("Example", "Sara stood outside the exam room. Her hands were cold. She checked her pen twice, then a third time.", "Details show a feeling"),
      list("Guided practice", ["Detail → cold hands, checking the pen three times.", "Feeling → nervousness.", "The narrator never says nervous; we infer it."]),
    ],
    exercises: [
      mc("What was the condition of the stairs and paint?", ["narrow stairs and peeling paint", "wide stairs and new paint", "no stairs"], 0, "“narrow… paint was peeling”.", FLAT),
      mc("What did the landlord say Nadia must do?", ["sign that day if she wanted the flat", "pay in cash", "clean the flat"], 0, "“You must sign today if you want it.”", FLAT),
      mc("Why was the landlord's pressure effective?", ["Other people were coming that afternoon.", "The rent was low.", "Nadia was in a hurry to leave."], 0, "The rival visitors created urgency.", FLAT),
      mc("What made Nadia decide to take the flat?", ["the light in the bedroom", "the kitchen table", "the price"], 0, "“the light in the bedroom felt like a decision already made”.", FLAT),
      mc("What did Nadia think she SHOULD have done?", ["compare other flats and ask about the rent", "ask for a discount", "phone her family"], 0, "“She should really compare it… ought to ask about the rent.”", FLAT),
      mc("How does Nadia feel at the end?", ["unsure whether she decided too quickly", "completely certain", "angry at the landlord"], 0, "“wonder whether she'd been too quick”.", FLAT),
    ],
  },
  {
    slug: "int-writing-narrative-sequencing",
    level: "INTERMEDIATE", category: "WRITING", title: "Narrative Writing: Sequencing and Text Modelling", topic: "Narrative writing",
    difficulty: "CORE", minutes: 18, prereq: ["int-writing-thesis-editing", "int-grammar-past-narrative-tenses"],
    objective: "Organise a narrative with a clear sequence using a model text as a pattern for your own story.",
    tags: ["writing", "narrative", "sequencing", "text-modelling", "past-tenses", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Writing", topic: "Narrative writing (Unit 4)" },
    sections: [
      text("A good narrative has a **clear sequence**: setting → problem → events → resolution. **Text modelling** means studying a model and following its **structure and language** with your own content.", "Explanation"),
      table("Narrative structure", ["Stage", "Purpose", "Typical tense"], [
        ["Setting", "who, where, when", "Past Continuous, Past Simple"],
        ["Problem", "something goes wrong or changes", "Past Simple"],
        ["Events", "what happens next (in order)", "Past Simple + sequencing words"],
        ["Resolution", "how it ends / what it means", "Past Simple, Past Perfect"],
      ]),
      annotated("Model narrative", [
        ["Setting", "It was a cold November evening, and I was waiting alone at the station."],
        ["Problem", "Suddenly, I realised that I had left my bag on the previous train."],
        ["Events", "First, I ran to the information desk. Then the assistant phoned the next station. After a few minutes, she smiled."],
        ["Resolution", "By nine o'clock my bag was safely in my hands, and I promised myself never to travel in a hurry again."],
      ]),
      table("Sequencing words", ["Stage", "Words"], [["Start", "at first · to begin with · one day"], ["Middle", "then · next · after that · meanwhile"], ["Sudden", "suddenly · all of a sudden"], ["End", "finally · in the end · eventually"]]),
    ],
    exercises: [
      order("Put the events in the correct order.", ["I was waiting alone at the station.", "I realised that I had left my bag on the train.", "I ran to the information desk.", "By nine o'clock my bag was back in my hands."], "sentence", "Setting, problem, action, resolution."),
      mc("Which stage of a narrative is “Suddenly, I realised I had lost my bag”?", ["setting", "problem", "resolution"], 1, "It introduces the problem."),
      fill("By the time the assistant called, I ___ (already / give up) hope.", ["had already given up"], "Earlier event: Past Perfect."),
      mist("Find the mistake.", ["It was raining", "when I leave", "the house."], 1, "left", "Past narrative: Past Simple."),
      match("Match the sequencing word with its stage.", [["one day", "start"], ["meanwhile", "middle"], ["suddenly", "problem"], ["finally", "end"]], "Use sequencing words to guide the reader."),
      mc("What does text modelling mean?", ["Following a model's structure and language with your own content", "Copying the text word for word", "Translating a text"], 0, "Model the pattern, not the words."),
    ],
  },

  // ============================================================ UNIT 5
  {
    slug: "int-grammar-future-forms",
    level: "INTERMEDIATE", category: "GRAMMAR", title: "Future Forms: will, going to and the Present Continuous", topic: "Future forms",
    difficulty: "CORE", minutes: 16, prereq: ["int-grammar-modals-obligation"],
    objective: "Choose between will, going to, the Present Continuous and the Present Simple to talk about the future.",
    tags: ["grammar", "future", "will", "going-to", "present-continuous", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Grammar", topic: "Future forms (Unit 5)" },
    sections: [
      text("English has **several ways** to talk about the future. The choice depends on **how sure** you are and **when you decided**.", "Explanation"),
      table("Future forms", ["Form", "Use", "Example"], [
        ["will + base verb", "instant decisions, predictions (opinion), promises", "I'll help you. I think it will rain."],
        ["be going to + base verb", "plans and intentions; predictions with evidence", "I'm going to study law. Look at those clouds: it's going to rain."],
        ["Present Continuous", "fixed arrangements (with a time and a person)", "I'm meeting the manager at ten tomorrow."],
        ["Present Simple", "timetables, schedules", "The train leaves at 6.30."],
      ]),
      flow("Which future form?", [["Is it a timetable or schedule?", "Present Simple (The class starts at nine.)"], ["Is it a fixed arrangement with a time or a person?", "Present Continuous (I'm seeing the dentist at four.)"], ["Is it a plan you decided before speaking, or a prediction with evidence?", "be going to"]], "will (instant decision, promise or opinion-based prediction)"),
    ],
    exercises: [
      mc("“There's no milk.” “Oh, I ___ buy some.” (instant decision)", ["'ll", "'m going to", "am buying"], 0, "Decision at the moment of speaking: will."),
      mc("Look at those clouds. It ___ rain.", ["will", "is going to", "rains"], 1, "Prediction with evidence: going to."),
      mc("I ___ the dentist at four tomorrow. (arrangement)", ["am seeing", "will see", "see"], 0, "A fixed arrangement: Present Continuous."),
      mc("The next train ___ at 6.30. (timetable)", ["leaves", "is leaving", "will leave"], 0, "Timetables: Present Simple."),
      mist("Find the mistake.", ["I", "will visit", "my aunt on Friday. I have already bought the ticket."], 1, "am going to visit", "A prepared plan: going to (or Present Continuous)."),
      fill("I promise I ___ (not / tell) anyone your secret.", ["won't tell"], "A promise: will / won't."),
    ],
  },
  {
    slug: "int-vocab-descriptive-adverbs",
    level: "INTERMEDIATE", category: "VOCABULARY", title: "Descriptive Adverbs of Manner", topic: "Adverbs",
    difficulty: "CORE", minutes: 12, prereq: ["int-vocab-story-literary"],
    objective: "Use adverbs of manner to describe how actions are done and vary their position in the sentence.",
    tags: ["vocabulary", "adverbs", "manner", "description", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Vocabulary", topic: "Descriptive adverbs (Unit 5)" },
    sections: [
      text("**Adverbs of manner** say **how** something happens. Most are formed with **-ly**, but some are irregular. They add **colour and precision** to descriptions."),
      table("Forming adverbs", ["Rule", "Examples"], [
        ["adjective + -ly", "slow → slowly · careful → carefully"],
        ["-y → -ily", "happy → happily · easy → easily"],
        ["-le → -ly", "gentle → gently · simple → simply"],
        ["irregular", "good → well · fast → fast · hard → hard · late → late"],
      ]),
      list("Position", ["After the verb: She spoke softly.", "After the object: He opened the door quietly.", "Before the verb for emphasis: She carefully placed the vase.", "At the start for style: Slowly, the sun rose."]),
      compare("Adjective or adverb?", [["He drives careful.", "He drives carefully.", "Modifies the verb: adverb."], ["She sings good.", "She sings well.", "The adverb of good is well."], ["The exam was hardly difficult.", "The exam was very hard.", "Hardly means almost not."]]),
    ],
    exercises: [
      match("Adjective → adverb.", [["gentle", "gently"], ["happy", "happily"], ["good", "well"], ["careful", "carefully"]], "Learn the spelling changes and the irregular form well."),
      fill("She spoke very ___ (soft), so I could hardly hear her.", ["softly"], "soft → softly."),
      mist("Find the mistake.", ["He", "drives", "very careful."], 2, "carefully", "An adverb is needed after the verb."),
      mc("She sings ___.", ["good", "well", "goodly"], 1, "The adverb of good is well."),
      order("Put the words in the correct order.", ["Slowly,", "the", "sun", "rose", "over", "the", "hills."], "word", "Adverb opens the sentence for style."),
      mc("Which sentence contains an adverb of manner?", ["She waited patiently.", "She waited in the hall.", "She waited for an hour."], 0, "Patiently answers how."),
    ],
  },
  {
    slug: "int-reading-forest-man",
    level: "INTERMEDIATE", category: "READING", title: "Reading: The Man Who Planted a Hillside", topic: "Descriptive reading",
    difficulty: "CORE", minutes: 16, prereq: ["int-reading-flat-story"],
    objective: "Read a descriptive story, identify how adverbs and detail create atmosphere, and understand the message.",
    tags: ["reading", "narrative", "description", "adverbs", "theme", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Reading", topic: "The forest man (Unit 5)" },
    sections: [
      text("Descriptive texts use **adverbs and specific detail** to create **atmosphere**. After reading, ask: **What is the message (theme)?** The message is often not stated directly.", "Reading strategy"),
      passage("Example", "Slowly, carefully, she folded the letter and put it away. She would not read it again.", "Manner adverbs show emotion"),
      list("Guided practice", ["Adverbs → slowly, carefully.", "Feeling → sadness or determination.", "Theme → a difficult decision."]),
    ],
    exercises: [
      mc("What was the condition of the hills when Karim arrived?", ["bare", "covered in forest", "full of water"], 0, "“the hills above it were bare”.", FOREST),
      mc("What did the villagers say at first?", ["“You will never finish.”", "“Thank you.”", "“Plant faster.”"], 0, "The villagers laughed at him.", FOREST),
      mc("What is Karim's attitude?", ["patient and long-term", "hurried and angry", "bored"], 0, "“I'm not planning to finish. I'm planning to begin.”", FOREST),
      mc("What happened after the trees grew?", ["The springs returned and the birds came back.", "The village left.", "The wells dried more."], 0, "The forest restored the water and wildlife.", FOREST),
      mc("Which pair of adverbs describes how Karim walked up the hill?", ["slowly and carefully", "quickly and noisily", "lazily and angrily"], 0, "“walked slowly up the slope, carefully carrying…”.", FOREST),
      mc("What is the message of the story?", ["Small, patient actions can change a place over time.", "Villagers are unkind.", "Trees grow quickly."], 0, "Theme: patience and persistence.", FOREST),
    ],
  },
  {
    slug: "int-writing-descriptive-adverbs",
    level: "INTERMEDIATE", category: "WRITING", title: "Descriptive Writing with Adverbs and Precise Detail", topic: "Descriptive writing",
    difficulty: "CORE", minutes: 18, prereq: ["int-writing-narrative-sequencing", "int-vocab-descriptive-adverbs"],
    objective: "Write a descriptive paragraph with a clear scene, precise vocabulary and adverbs used for effect.",
    tags: ["writing", "descriptive", "adverbs", "style", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Writing", topic: "Descriptive writing (Unit 5)" },
    sections: [
      text("Descriptive writing helps the reader **see, hear and feel** a scene. Choose a **focus**, use **all five senses**, and select **precise words** rather than many words.", "Explanation"),
      table("Plan a description", ["Step", "Question"], [["1 Focus", "What is the one main impression (calm, busy, lonely)?"], ["2 Senses", "What do you see, hear, smell, feel?"], ["3 Order", "From far to near? Left to right? Outside to inside?"], ["4 Language", "Precise verbs, adjectives and adverbs"]]),
      annotated("Model description", [
        ["Focus", "The market was never quiet, but it was most alive at dawn."],
        ["Senses", "Fishermen shouted cheerfully, and the smell of salt and spices drifted slowly through the crowd."],
        ["Detail", "A boy carefully arranged a pyramid of oranges while his father weighed the catch."],
        ["Closing", "By seven, the sun had risen, and the market breathed in one loud, happy rhythm."],
      ]),
      tip("Do not use too many adverbs. One precise verb is often better than a verb + adverb: whisper instead of speak quietly.", "Style"),
    ],
    exercises: [
      order("Put the sentences of the description in a logical order.", ["The market was most alive at dawn.", "Fishermen shouted cheerfully as the smell of salt drifted through the crowd.", "A boy carefully arranged a pyramid of oranges.", "By seven o'clock the sun had risen."], "paragraph", "Focus, senses, detail, closing."),
      mc("Which is more precise?", ["She spoke quietly.", "She whispered.", "She said something."], 1, "A precise verb replaces verb + adverb."),
      fill("The old man ___ (slow) crossed the road.", ["slowly"], "Adverb of manner."),
      mist("Find the mistake.", ["She", "cheerful", "greeted every customer."], 1, "cheerfully", "An adverb is needed to modify the verb."),
      mc("What should you do first when planning a description?", ["Choose one main impression", "List all the adjectives you know", "Write the conclusion"], 0, "A clear focus controls the description."),
      match("Which sense?", [["the smell of spices", "smell"], ["a loud cheerful shout", "hearing"], ["a pyramid of oranges", "sight"], ["the warm sun on my face", "touch"]], "Use several senses."),
    ],
  },

  // ============================================================ UNIT 6
  {
    slug: "int-grammar-information-questions",
    level: "INTERMEDIATE", category: "GRAMMAR", title: "Information Questions and Question Forms", topic: "Questions",
    difficulty: "CORE", minutes: 14, prereq: ["int-grammar-future-forms"],
    objective: "Form subject and object questions, and questions with prepositions and indirect questions accurately.",
    tags: ["grammar", "questions", "wh-questions", "indirect-questions", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Grammar", topic: "Information questions (Unit 6)" },
    sections: [
      text("Accurate question forms are essential. The key difference is between **subject questions** (the wh-word IS the subject; no auxiliary) and **object questions** (auxiliary needed).", "Explanation"),
      table("Subject and object questions", ["Type", "Structure", "Example"], [
        ["Subject question", "Wh-word + verb", "Who wrote this report? (Fatima wrote it.)"],
        ["Object question", "Wh-word + auxiliary + subject + verb", "What did Fatima write? (She wrote a report.)"],
        ["With a preposition", "Wh-word + auxiliary + subject + verb + preposition", "Who are you talking to? / To whom are you talking? (formal)"],
        ["Indirect question", "Polite phrase + statement word order", "Could you tell me where the station is?"],
      ]),
      compare("Errors", [["Who did write this?", "Who wrote this?", "Subject question: no do."], ["Do you know where is the bank?", "Do you know where the bank is?", "Indirect: statement order."], ["What you are doing?", "What are you doing?", "Auxiliary before subject."]]),
    ],
    exercises: [
      mc("___ this report? (Fatima wrote it.)", ["Who wrote", "Who did write", "Who does write"], 0, "Subject question: no auxiliary."),
      mc("What ___ Fatima write? (She wrote a report.)", ["does", "did", "has"], 1, "Object question in the past: did."),
      mist("Find the mistake.", ["Could you tell me", "where is", "the station?"], 1, "where the station is", "Indirect question: statement order."),
      order("Put the words in the correct order.", ["Who", "are", "you", "talking", "to?"], "word", "Wh-word + auxiliary + subject + verb + preposition."),
      fill("Do you know what time the meeting ___? (start)", ["starts"], "Indirect question: statement order, no do."),
      mc("Which is a subject question?", ["Who called you?", "Who did you call?", "Who are you calling?"], 0, "The wh-word is the subject."),
    ],
  },
  {
    slug: "int-grammar-relative-clauses",
    level: "INTERMEDIATE", category: "GRAMMAR", title: "Relative Clauses with who, that, which and whose", topic: "Relative clauses",
    difficulty: "CORE", minutes: 16, prereq: ["int-grammar-information-questions"],
    objective: "Join sentences with defining and non-defining relative clauses and choose the correct relative pronoun.",
    tags: ["grammar", "relative-clauses", "defining", "non-defining", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Grammar", topic: "Relative clauses (Unit 6)" },
    sections: [
      text("A **relative clause** adds information about a noun. **Defining** clauses identify *which* person or thing; **non-defining** clauses add extra information and are separated by **commas**.", "Explanation"),
      table("Relative pronouns", ["Pronoun", "Used for", "Example"], [
        ["who / that", "people (subject or object)", "The woman who lives next door is a doctor."],
        ["which / that", "things", "The book that I bought is excellent."],
        ["whose", "possession", "The man whose car was stolen called the police."],
        ["where / when", "places / times", "This is the town where I grew up."],
      ]),
      table("Defining vs non-defining", ["Type", "Commas?", "'that' possible?", "Object pronoun can be omitted?", "Example"], [
        ["Defining", "no", "yes", "yes", "The film (that) I saw was long."],
        ["Non-defining", "yes", "no (use which / who)", "no", "The film, which I saw on Friday, was long."],
      ]),
      tip("If you can remove the clause and the sentence still identifies the same noun, it's non-defining and needs commas.", "Test"),
    ],
    exercises: [
      mc("The woman ___ lives next door is a doctor.", ["who", "which", "whose"], 0, "People: who."),
      mc("The man ___ car was stolen called the police.", ["who", "whose", "which"], 1, "Possession: whose."),
      mc("My brother, ___ lives in Dubai, is an engineer. (extra information)", ["that", "who", "whose"], 1, "Non-defining: who (not that)."),
      mist("Find the mistake.", ["My car,", "that is very old,", "still works well."], 1, "which is very old,", "Non-defining clauses cannot use that."),
      fill("This is the town ___ I grew up.", ["where"], "Place: where."),
      match("Defining or non-defining?", [["The book that I bought is great.", "defining"], ["Muscat, which is the capital, is beautiful.", "non-defining"], ["Students who work hard succeed.", "defining"], ["My father, who is a teacher, retired.", "non-defining"]], "Non-defining clauses have commas."),
    ],
  },
  {
    slug: "int-vocab-numbers-statistics",
    level: "INTERMEDIATE", category: "VOCABULARY", title: "Numbers, Statistics and Ratios", topic: "Numbers",
    difficulty: "CORE", minutes: 14, prereq: ["int-vocab-descriptive-adverbs"],
    objective: "Talk about numbers, percentages, fractions and ratios accurately.",
    tags: ["vocabulary", "numbers", "statistics", "percentages", "ratios", "listening-support", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Vocabulary", topic: "Numbers, statistics, ratios (Unit 6)" },
    sections: [
      text("Statistics appear in news, reports and essays. Learn to **say, read and write** numbers clearly and use **approximation words**."),
      table("Saying numbers", ["Written", "Spoken"], [
        ["45%", "forty-five percent"], ["1/4", "a quarter"], ["3/4", "three quarters"], ["2.5", "two point five"], ["1:18", "a ratio of one to eighteen"], ["2,000", "two thousand"], ["1,500,000", "one and a half million / one million five hundred thousand"],
      ]),
      list("Approximation and comparison", ["**about / around / roughly / approximately** 60%", "**nearly / almost** 2,000 (just below)", "**more than / over** 100", "**a majority / a minority** of people", "**twice as many as** · **half as much as**"]),
      compare("Errors", [["Three hundreds people came.", "Three hundred people came.", "Hundred is not plural after a number."], ["The number of students are rising.", "The number of students is rising.", "The number is singular."], ["A lot of people is late.", "A lot of people are late.", "People is plural."]]),
    ],
    exercises: [
      match("Match the number and how to say it.", [["1/4", "a quarter"], ["45%", "forty-five percent"], ["2.5", "two point five"], ["1:18", "a ratio of one to eighteen"]], "Learn the spoken forms."),
      mist("Find the mistake.", ["Three", "hundreds", "students attended."], 1, "hundred", "Hundred stays singular after a number."),
      fill("The number of students in the class ___ (rise) every year.", [["rises", "is rising"]], "The number is singular."),
      mc("“Nearly 2,000 loaves” means ___.", ["a little less than 2,000", "a little more than 2,000", "exactly 2,000"], 0, "Nearly = just below."),
      mc("Which phrase shows an approximation?", ["around 60 percent", "exactly 60 percent", "60 percent"], 0, "Around shows it is not exact."),
      order("Put the words in the correct order.", ["Roughly", "half", "of", "the", "students", "walk", "to", "school."], "word", "Approximation + fraction + of + noun."),
    ],
  },
  {
    slug: "int-reading-whos-who",
    level: "INTERMEDIATE", category: "READING", title: "Reading: Who's Who", topic: "Reading for detail",
    difficulty: "CORE", minutes: 16, prereq: ["int-reading-forest-man"],
    objective: "Locate specific factual details (numbers, ratios, relative clauses) in short biographical texts.",
    tags: ["reading", "reading-details", "numbers", "relative-clauses", "biography", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Reading", topic: "Who's who (Unit 6)" },
    sections: [
      text("Short **profile texts** pack in many facts. **Scan** for names, numbers and relative clauses, then re-read the exact sentence to check the detail.", "Reading strategy"),
      passage("Example", "Ali, whose shop opened in 2015, sells around 500 books a week, most of which are novels.", "Details in a relative clause"),
      list("Guided practice", ["Opened → 2015.", "Sells → around 500 a week.", "Most are → novels."]),
    ],
    exercises: [
      mc("What does Dr Al Harthy study?", ["coral reefs", "birds", "bread"], 0, "“studies coral reefs along the Gulf of Oman”.", WHOS_WHO),
      mc("About what percentage of her research is done underwater?", ["60 percent", "16 percent", "20 percent"], 0, "“about 60 percent”.", WHOS_WHO),
      mc("When did Omar's bakery open?", ["2012", "2002", "2021"], 0, "“whose bakery opened in 2012”.", WHOS_WHO),
      mc("How many people work at the bakery?", ["eleven", "eighteen", "two thousand"], 0, "“which employs eleven people”.", WHOS_WHO),
      mc("What is the teacher-to-student ratio in Maryam's classes?", ["about one to eighteen", "about eighteen to one", "about one to two"], 0, "“about one to eighteen”.", WHOS_WHO),
      tf("Omar's bakery sells exactly 2,000 loaves every day.", false, "The text says “nearly 2,000”.", WHOS_WHO),
    ],
  },
  {
    slug: "int-writing-discursive-pros-cons",
    level: "INTERMEDIATE", category: "WRITING", title: "Discursive Writing: Presenting Advantages and Disadvantages", topic: "Discursive writing",
    difficulty: "CHALLENGING", minutes: 20, prereq: ["int-writing-thesis-editing", "int-writing-essay-1-paragraph-logic"],
    objective: "Plan and write a balanced discursive paragraph or essay that presents both sides of an issue.",
    tags: ["writing", "discursive", "advantages-disadvantages", "essay", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Writing", topic: "Discursive writing: pros and cons (Unit 6)" },
    sections: [
      text("A **discursive essay** discusses an issue from **different points of view**. Unlike a personal opinion piece, it must be **balanced**, **objective** and supported with **reasons and examples**.", "Explanation"),
      table("Balanced structure", ["Paragraph", "Content"], [["Introduction", "Introduce the issue; say that there are two sides"], ["Advantages", "2–3 points with reasons/examples"], ["Disadvantages", "2–3 points with reasons/examples"], ["Conclusion", "Summarise; give a balanced or personal view"]]),
      table("Useful language", ["Function", "Phrases"], [
        ["Advantages", "One major advantage is … · Another benefit is … · A further positive point is …"],
        ["Disadvantages", "On the other hand, … · One drawback is … · However, a serious disadvantage is …"],
        ["Balancing", "Although … · While … · Despite the fact that …"],
        ["Concluding", "Taking everything into account … · On balance …"],
      ]),
      tip("Use formal language: avoid contractions (don't → do not) and informal expressions (a lot of → many).", "Style"),
    ],
    exercises: [
      order("Put the parts of a discursive essay in order.", ["Introduction", "Advantages", "Disadvantages", "Conclusion"], "paragraph", "Introduce, advantages, disadvantages, conclude."),
      mc("Which phrase introduces a drawback?", ["One drawback is …", "Another benefit is …", "In addition, …"], 0, "Drawback = disadvantage."),
      mist("Find the mistake (formal style).", ["Online learning", "doesn't", "suit everyone."], 1, "does not", "Avoid contractions in formal writing."),
      mc("Which sentence is balanced?", ["Although online learning is flexible, it can be isolating.", "Online learning is the best thing ever.", "Online learning is terrible."], 0, "Although shows both sides."),
      fill("___ the fact that online courses are cheap, many students prefer classrooms.", ["Despite"], "Despite the fact that …"),
      mc("What does a discursive essay require?", ["balanced presentation of both sides", "only your own opinion", "a story"], 0, "Objectivity and balance."),
    ],
  },
];

void [compare, match, sa, structure, tip, vocab, annotated];
