import { HW, annotated, compare, fill, list, match, mc, mist, order, passage, sa, structure, table, text, tf, tip, vocab, type SeedLesson } from "./dsl";

// Intermediate course, Units 7-9. Topics follow the academy's syllabus; all text is ORIGINAL.

const FIRST_JOB = "MY FIRST JOB\n\nI got my first job when I was seventeen, at a small stationery shop near my school. I had never worked before, and on the first morning I arrived forty minutes early, which the owner, Mr Jamal, found very funny.\n\nFor the first month I did nothing but arrange pens and count boxes. I've been thinking about that time a lot recently, because I've just been promoted to manager at the same shop! Mr Jamal has retired, and I've been running the place for three weeks now.\n\nI have learned more from that shop than from any lesson: how to talk to difficult customers, how to stay calm under pressure, and how to keep going when the work is boring. I've worked there on and off for eleven years. Some people find that strange, but I have always felt that the best jobs are the ones you grow into.";
const OLDEN = "THE OLDEN DAYS\n\nMy grandfather says that life was simpler when he was young. He remembers walking two kilometres to school and helping his father to mend nets before dawn. “We didn't have much money,” he says, “but we never stopped talking to each other.”\n\nHe admits that he doesn't miss everything. “I don't miss the heat without air conditioning,” he laughs, “and I certainly don't miss writing letters that took a month to arrive.” Still, when I ask him whether he would go back, he pauses. “I'd like to see the old neighbours again,” he says. “But I wouldn't give up my telephone.”\n\nBefore I left, he told me something I keep thinking about: people who are always looking back can forget to notice what is good about now.";
const MONEY = "MONEY MATTERS\n\nMost people say that money doesn't buy happiness, yet most people also spend a great deal of time worrying about it. Economists suggest that, once basic needs are met, extra income makes a smaller and smaller difference to how satisfied we feel.\n\nWhat matters more, several studies argue, is how we spend. Money spent on experiences, such as a trip with friends, seems to give longer-lasting pleasure than money spent on objects. Similarly, giving money to others often makes people feel better than spending it on themselves.\n\nOf course, these findings do not mean that money is unimportant. If you can't pay your bills, you're likely to be very stressed. If people had more control over their finances, they would probably worry less. The evidence simply suggests that, beyond a certain point, the question is not how much you have, but what you do with it.";

export const INT_U7_U9: SeedLesson[] = [
  // ============================================================ UNIT 7
  {
    slug: "int-grammar-present-perfect-simple-continuous",
    level: "INTERMEDIATE", category: "GRAMMAR", title: "Present Perfect Simple and Continuous", topic: "Present Perfect",
    difficulty: "CORE", minutes: 16, prereq: ["int-grammar-relative-clauses", "int-grammar-past-narrative-tenses"],
    objective: "Choose between the Present Perfect Simple and Continuous for unfinished past, results and recent activities.",
    tags: ["grammar", "present-perfect", "present-perfect-continuous", "unfinished-past", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Grammar", topic: "Present Perfect Simple and Continuous (Unit 7)" },
    sections: [
      text("Both tenses connect the **past with the present**. The **Simple** focuses on the **result or completed quantity**; the **Continuous** focuses on the **activity and its duration**.", "Explanation"),
      table("Simple or continuous?", ["Feature", "Present Perfect Simple", "Present Perfect Continuous"], [
        ["Focus", "result, number, completion", "activity, duration, recent process"],
        ["Example", "I've written three emails.", "I've been writing emails all morning."],
        ["Unfinished past", "I've lived here for ten years.", "I've been living here for ten years."],
        ["Recent activity with visible evidence", "—", "You look tired. Have you been working?"],
      ]),
      list("Rules", ["**How many / how much / completed** → Simple: She's read four books this week.", "**How long / activity in progress / evidence now** → Continuous: She's been reading since lunch.", "**State verbs** (know, like, have, be) → Simple only: I've known him for years.", "**for + period, since + starting point**."]),
      compare("Errors", [["I am working here since 2015.", "I have been working here since 2015.", "Unfinished time: perfect."], ["I've been knowing her for years.", "I've known her for years.", "State verb: simple."], ["I've been writing three reports.", "I've written three reports.", "A number → Simple."]]),
    ],
    exercises: [
      mc("I ___ here since 2015 and I still love it.", ["work", "have worked", "am working"], 1, "Since + unfinished time: Present Perfect."),
      mc("Your eyes are red. ___ ?", ["Have you been crying", "Did you cry", "Do you cry"], 0, "Recent activity with visible evidence: continuous."),
      mc("She ___ four books this week.", ["has been reading", "has read", "reads"], 1, "A number: Simple."),
      mist("Find the mistake.", ["I", "have been knowing", "him for years."], 1, "have known", "State verbs are not used in the continuous."),
      fill("I ___ (write) emails all morning and my hands are tired.", [["have been writing", "'ve been writing"]], "Duration of an activity: continuous."),
      order("Put the words in the correct order.", ["How", "long", "have", "you", "been", "learning", "English?"], "word", "How long + have + subject + been + -ing."),
    ],
  },
  {
    slug: "int-vocab-professional-phrasal-verbs",
    level: "INTERMEDIATE", category: "VOCABULARY", title: "Professional Phrasal Verbs and Exclamations", topic: "Work vocabulary",
    difficulty: "CORE", minutes: 14, prereq: ["int-vocab-work-careers"],
    objective: "Use phrasal verbs and short exclamations that are common in workplace situations.",
    tags: ["vocabulary", "phrasal-verbs", "work", "exclamations", "listening-support", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Vocabulary", topic: "Phrasal verbs, work (Unit 7)" },
    sections: [
      text("Workplace English uses many **phrasal verbs**. Some are informal, so notice the **register** (formal or informal)."),
      table("Work phrasal verbs", ["Phrasal verb", "Meaning", "Example"], [
        ["take on", "accept a job or responsibility", "She took on extra work during the busy season."],
        ["carry out", "do or complete (a task, study)", "The team carried out a survey."],
        ["set up", "establish; organise", "They set up a new office in Salalah."],
        ["hand in", "give (work) to someone in authority", "Please hand in your report by Friday."],
        ["look into", "investigate", "We will look into the problem."],
        ["get on with", "continue or make progress with", "Let's get on with the meeting."],
        ["step down", "leave a position", "The manager stepped down last month."],
      ]),
      table("Exclamations", ["Pattern", "Example"], [
        ["What + (a) + adjective + noun!", "What a fantastic idea!"],
        ["How + adjective!", "How exciting! · How annoying!"],
        ["So / Such", "It's so difficult! · It's such a long day!"],
      ]),
    ],
    exercises: [
      match("Match the phrasal verb with its meaning.", [["take on", "accept a responsibility"], ["carry out", "do or complete"], ["step down", "leave a position"], ["look into", "investigate"], ["hand in", "give work to someone"]], "Learn each phrasal verb with its meaning."),
      mc("The manager ___ last month, and a new director was chosen.", ["stepped down", "took on", "handed in"], 0, "step down = leave a position."),
      fill("Please ___ in your report by Friday.", ["hand"], "hand in = submit."),
      mist("Find the mistake.", ["What", "fantastic idea", "you had!"], 1, "a fantastic idea", "What + a + adjective + noun."),
      mc("Which exclamation is correct?", ["How exciting!", "What exciting!", "How an exciting!"], 0, "How + adjective."),
      order("Put the words in the correct order.", ["We", "will", "look", "into", "the", "problem", "immediately."], "word", "Subject + will + look into + object + adverb."),
    ],
  },
  {
    slug: "int-reading-first-job",
    level: "INTERMEDIATE", category: "READING", title: "Reading: My First Job", topic: "Personal narrative",
    difficulty: "CORE", minutes: 16, prereq: ["int-reading-whos-who"],
    objective: "Follow the sequence and time relationships in a personal narrative that uses present perfect and past tenses.",
    tags: ["reading", "narrative", "tenses", "sequencing", "work", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Reading", topic: "My first job (Unit 7)" },
    sections: [
      text("In a personal narrative, the **tense** tells you **when** things happened: **Past Simple** = finished events; **Present Perfect** = connection to now. Track the **time line** as you read.", "Reading strategy"),
      passage("Example", "I started teaching in 2015. I've taught more than 500 students since then.", "Finished start, continuing result"),
      list("Guided practice", ["Started → 2015 (finished).", "500 students → up to now.", "The perfect tense connects past and present."]),
    ],
    exercises: [
      mc("How old was the writer at their first job?", ["seventeen", "seven", "twenty"], 0, "“when I was seventeen”.", FIRST_JOB),
      mc("What did the writer do on the first morning?", ["arrived forty minutes early", "arrived late", "stayed home"], 0, "“arrived forty minutes early”.", FIRST_JOB),
      mc("What recent news does the writer share?", ["a promotion to manager", "a decision to leave", "a new shop"], 0, "“I've just been promoted to manager”.", FIRST_JOB),
      mc("Why does the writer use “I've been running the place for three weeks”?", ["The activity started in the past and continues now.", "It ended yesterday.", "It will begin next week."], 0, "Present Perfect Continuous with for.", FIRST_JOB),
      tf("The writer has worked at the shop continuously without a break.", false, "“on and off for eleven years”.", FIRST_JOB),
      mc("What is the writer's main belief?", ["The best jobs are those you grow into.", "Work is boring.", "Everyone should be a manager."], 0, "The final sentence.", FIRST_JOB),
    ],
  },
  {
    slug: "int-writing-professional-correspondence",
    level: "INTERMEDIATE", category: "WRITING", title: "Professional Correspondence and CV Summaries", topic: "Formal writing",
    difficulty: "CORE", minutes: 18, prereq: ["int-writing-personal-profile"],
    objective: "Write a formal email or cover message and a concise CV personal summary using appropriate register.",
    tags: ["writing", "formal-writing", "email", "cv", "register", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Writing", topic: "Correspondence, CVs (Unit 7)" },
    sections: [
      text("**Professional writing** is clear, polite and concise. Choose **formal register**: full forms, neutral vocabulary and a logical order.", "Explanation"),
      table("Structure of a formal email", ["Part", "Example"], [
        ["Subject line", "Application for Marketing Assistant position"],
        ["Greeting", "Dear Ms Hilal, / Dear Sir or Madam,"],
        ["Purpose", "I am writing to apply for …"],
        ["Details", "I have worked as … for three years."],
        ["Closing", "I would be grateful if you could … / I look forward to hearing from you."],
        ["Sign-off", "Yours sincerely, (name known) / Yours faithfully, (name unknown)"],
      ]),
      annotated("Model CV personal summary", [
        ["Who", "Motivated graduate in business administration with two years of experience in customer service."],
        ["Strength", "Strong communication and organisational skills; fluent in Arabic and English."],
        ["Goal", "Seeking a marketing role where I can develop creative campaigns."],
      ]),
      compare("Formal or informal?", [["Hi, I'm after a job.", "Dear Ms Hilal, I am writing to apply for the position.", "Formal opening."], ["Can't wait to hear from you!", "I look forward to hearing from you.", "Formal closing."], ["I wanna know more.", "I would like to know more.", "No contractions or slang."]]),
    ],
    exercises: [
      order("Put the parts of the email in order.", ["Dear Ms Hilal,", "I am writing to apply for the position of Marketing Assistant.", "I have worked as a sales assistant for three years.", "I look forward to hearing from you.", "Yours sincerely, Aisha"], "sentence", "Greeting, purpose, details, closing, sign-off."),
      mc("Which sign-off is correct when you know the person's name?", ["Yours sincerely", "Yours faithfully", "Cheers"], 0, "Dear Ms Hilal → Yours sincerely."),
      mc("Which is the most formal?", ["I would be grateful if you could send me the details.", "Send me the details.", "Gimme the details."], 0, "Polite formal request."),
      mist("Find the mistake (register).", ["Hi", "I wanna", "apply for the job."], 1, "want to / would like to", "Avoid informal wanna in professional writing."),
      fill("I ___ (work) as a sales assistant for three years. (still working)", [["have worked", "have been working"]], "Unfinished time: perfect."),
      mc("Which is a CV personal summary?", ["Motivated graduate with two years of experience in customer service.", "I was born in Muscat in 1999.", "Dear Sir or Madam"], 0, "It is short and skills-focused."),
    ],
  },

  // ============================================================ UNIT 8
  {
    slug: "int-grammar-verb-patterns",
    level: "INTERMEDIATE", category: "GRAMMAR", title: "Verb Patterns: Infinitive or -ing?", topic: "Verb patterns",
    difficulty: "CHALLENGING", minutes: 16, prereq: ["int-grammar-present-perfect-simple-continuous"],
    objective: "Use verbs correctly followed by the infinitive or the -ing form, including verbs that change meaning.",
    tags: ["grammar", "verb-patterns", "infinitive", "gerund", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Grammar", topic: "Verb patterns (Unit 8)" },
    sections: [
      text("Some verbs are followed by **to + infinitive**, others by **-ing**, and a few by **either** with a **change in meaning**. Learn the patterns with the verbs.", "Explanation"),
      table("Common patterns", ["Pattern", "Verbs", "Example"], [
        ["verb + to-infinitive", "want, decide, hope, plan, refuse, manage, afford", "She decided to leave."],
        ["verb + -ing", "enjoy, avoid, finish, suggest, mind, keep, consider", "He enjoys swimming."],
        ["verb + object + infinitive", "want, ask, tell, allow, advise", "She asked him to help."],
        ["make / let + object + base verb", "make, let", "They made me wait. / She let him go."],
      ]),
      table("Verbs that change meaning", ["Verb", "+ -ing", "+ to-infinitive"], [
        ["stop", "stop doing (quit): He stopped smoking.", "stop to do (in order to): He stopped to buy water."],
        ["remember", "remember doing (past memory): I remember meeting her.", "remember to do (not forget): Remember to lock the door."],
        ["try", "try doing (experiment): Try switching it off.", "try to do (make an effort): I tried to open it."],
        ["forget", "forget doing (past): I'll never forget seeing it.", "forget to do (omit): I forgot to call."],
      ]),
      tip("After prepositions we always use -ing: interested in learning, good at cooking, before leaving.", "Rule"),
    ],
    exercises: [
      mc("She decided ___ her job.", ["to leave", "leaving", "leave"], 0, "decide + to-infinitive."),
      mc("I enjoy ___ in the sea.", ["to swim", "swimming", "swim"], 1, "enjoy + -ing."),
      mc("Remember ___ the door when you leave. (don't forget)", ["locking", "to lock", "lock"], 1, "remember to do."),
      mist("Find the mistake.", ["They", "made me to wait", "for an hour."], 1, "made me wait", "make + object + base verb (no to)."),
      mc("He stopped ___ some water because he was thirsty. (in order to)", ["buying", "to buy", "buy"], 1, "stop to do = pause in order to do something."),
      fill("She is interested in ___ (learn) about other cultures.", ["learning"], "After a preposition: -ing."),
    ],
  },
  {
    slug: "int-vocab-money-prepositions",
    level: "INTERMEDIATE", category: "VOCABULARY", title: "Money, Finance and Prepositions", topic: "Money vocabulary",
    difficulty: "CORE", minutes: 14, prereq: ["int-vocab-professional-phrasal-verbs"],
    objective: "Use vocabulary about money and finance together with the correct prepositions.",
    tags: ["vocabulary", "money", "finance", "prepositions", "collocations", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Vocabulary", topic: "Money vocabulary; prepositions (Unit 8)" },
    sections: [
      text("Money vocabulary is easiest to learn as **verb + preposition** and **noun + preposition** chunks."),
      table("Money and prepositions", ["Phrase", "Meaning", "Example"], [
        ["pay for", "give money in exchange for", "I paid for the tickets online."],
        ["spend money on", "use money to buy", "He spends too much on clothes."],
        ["save up for", "put money aside for", "She is saving up for a car."],
        ["invest in", "put money into something to earn more", "They invested in a small business."],
        ["be in debt / in credit", "owe money / have money in an account", "He is in debt to the bank."],
        ["a loan / a mortgage / interest", "money borrowed / for a house / extra you pay", "The interest on the loan is high."],
        ["afford", "have enough money to buy", "I can't afford a new laptop."],
      ]),
      list("Common mistakes", ["Pay for (not *pay the tickets*).", "Spend money on (not *spend money for*).", "Depend on · rely on · budget for."]),
    ],
    exercises: [
      mc("He spends too much money ___ clothes.", ["on", "for", "at"], 0, "spend money on."),
      mc("She is saving up ___ a car.", ["for", "on", "to"], 0, "save up for."),
      fill("I can't ___ a new laptop; it's too expensive.", ["afford"], "afford = have enough money."),
      mist("Find the mistake.", ["I", "paid", "the tickets online."], 1, "paid for", "pay for something."),
      match("Match the phrase and meaning.", [["invest in", "put money into something to earn more"], ["in debt", "owing money"], ["interest", "extra money paid on a loan"], ["mortgage", "a loan to buy a house"]], "Learn finance chunks."),
      mc("Which sentence is correct?", ["She relies on her savings.", "She relies of her savings.", "She relies to her savings."], 0, "rely on."),
    ],
  },
  {
    slug: "int-vocab-character-adjectives",
    level: "INTERMEDIATE", category: "VOCABULARY", title: "Character Adjectives: Describing Personality", topic: "Character adjectives",
    difficulty: "CORE", minutes: 12, prereq: ["int-vocab-money-prepositions"],
    objective: "Describe personality using a range of character adjectives, including opposites and word families.",
    tags: ["vocabulary", "adjectives", "personality", "opposites", "listening-support", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Vocabulary", topic: "Character adjectives (Unit 8)" },
    sections: [
      text("Character adjectives describe **personality and behaviour**. Many have **opposites** formed with prefixes (un-, in-, im-, dis-) or completely different words."),
      table("Character adjectives", ["Positive", "Negative", "Meaning of the positive"], [
        ["generous", "mean / stingy", "happy to give money or time"],
        ["patient", "impatient", "able to wait calmly"],
        ["reliable", "unreliable", "you can depend on them"],
        ["modest", "arrogant / boastful", "does not show off"],
        ["sociable", "shy / reserved", "enjoys the company of others"],
        ["honest", "dishonest", "tells the truth"],
        ["determined", "easily discouraged", "keeps trying"],
      ]),
      vocab([
        { word: "ambitious", pos: "adjective", meaning: "wanting to achieve success", ar: "طموح", pron: "/æmˈbɪʃəs/", ex: "She is ambitious and hopes to become a director.", col: ["fiercely ambitious"], visual: "🚀" },
        { word: "stubborn", pos: "adjective", meaning: "refusing to change your mind", ar: "عنيد", pron: "/ˈstʌbən/", ex: "He is too stubborn to admit he is wrong.", col: ["as stubborn as a mule"], visual: "🪨" },
      ], "Two useful words"),
    ],
    exercises: [
      match("Match the adjective with the description.", [["generous", "gives freely"], ["reliable", "can be depended on"], ["modest", "does not show off"], ["stubborn", "refuses to change his mind"]], "Learn the meaning with the noun."),
      mc("What is the opposite of “patient”?", ["impatient", "unpatient", "dispatient"], 0, "im- prefix."),
      mc("He refuses to admit he is wrong, even when it is obvious. He is ___.", ["stubborn", "generous", "modest"], 0, "Stubborn = does not change his mind."),
      mist("Find the mistake.", ["She", "is very", "unreliabel."], 2, "unreliable", "Spelling: unreliable."),
      fill("She is very ___: she always wants to get the top job. (ambitious)", ["ambitious"], "Ambitious = wants success."),
      mc("Which adjective is positive?", ["arrogant", "generous", "stingy"], 1, "Generous is positive."),
    ],
  },
  {
    slug: "int-reading-olden-days",
    level: "INTERMEDIATE", category: "READING", title: "Reading: The Olden Days", topic: "Reading for opinion and attitude",
    difficulty: "CORE", minutes: 16, prereq: ["int-reading-first-job"],
    objective: "Identify a speaker's attitude, comparing past and present in a reflective text.",
    tags: ["reading", "attitude", "comparison", "reported-speech", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Reading", topic: "The olden days (Unit 8)" },
    sections: [
      text("Reflective texts compare **the past and the present**. Ask: does the speaker feel **nostalgic** (missing the past), **critical** or **balanced**? Look for words that show **attitude** (still, but, certainly not).", "Reading strategy"),
      passage("Example", "“I loved my village,” he said. “But I wouldn't want to live there again.”", "The word but signals a balanced attitude"),
      list("Guided practice", ["Positive → loved my village.", "Negative → wouldn't want to live there.", "Attitude → balanced."]),
    ],
    exercises: [
      mc("What did the grandfather do before dawn as a boy?", ["mend nets with his father", "go to school", "write letters"], 0, "“helping his father to mend nets”.", OLDEN),
      mc("What does the grandfather say about the old days?", ["They had little money but they talked to each other.", "They were easy and rich.", "They were dangerous."], 0, "“We didn't have much money, but we never stopped talking to each other.”", OLDEN),
      mc("Which does he NOT miss?", ["writing letters that took a month to arrive", "the old neighbours", "talking to family"], 0, "“I certainly don't miss writing letters…”.", OLDEN),
      mc("What would he not give up?", ["his telephone", "his house", "his neighbours"], 0, "“I wouldn't give up my telephone.”", OLDEN),
      mc("What is the grandfather's attitude to the past?", ["balanced: he values some things and not others", "completely nostalgic", "completely negative"], 0, "He mixes praise and criticism.", OLDEN),
      mc("What advice is given in the last sentence?", ["Notice what is good about now.", "Return to the past.", "Write more letters."], 0, "“forget to notice what is good about now”.", OLDEN),
    ],
  },
  {
    slug: "int-writing-comparative-essays",
    level: "INTERMEDIATE", category: "WRITING", title: "Writing Comparative Essays", topic: "Comparison essays",
    difficulty: "CHALLENGING", minutes: 20, prereq: ["int-writing-discursive-pros-cons"],
    objective: "Organise and write a comparative essay using block or point-by-point structure and comparison language.",
    tags: ["writing", "comparison", "essay", "structure", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Writing", topic: "Comparative essays (Unit 8)" },
    sections: [
      text("A **comparative essay** examines the **similarities and differences** between two things (for example, life today and life in the past). There are two ways to organise it.", "Explanation"),
      table("Two structures", ["Structure", "How it works", "Best for"], [
        ["Block", "All about A, then all about B, then compare", "short essays, clear differences"],
        ["Point-by-point", "Point 1: A and B; Point 2: A and B", "longer essays, many features"],
      ]),
      table("Language of comparison", ["Function", "Phrases"], [
        ["Similarity", "similarly · likewise · both … and … · in the same way"],
        ["Difference", "whereas · while · in contrast · unlike · on the other hand"],
        ["Degree", "much more · slightly less · not as … as · twice as … as"],
      ]),
      annotated("Model point-by-point paragraph", [
        ["Topic sentence", "Communication has changed dramatically in one generation."],
        ["Then", "Whereas my grandfather wrote letters that took a month to arrive, I send messages that arrive in seconds."],
        ["Comparison", "Similarly, both of us value staying in touch, although we do it in different ways."],
      ]),
    ],
    exercises: [
      mc("Which word shows a CONTRAST?", ["whereas", "likewise", "similarly"], 0, "Whereas = contrast."),
      mc("Which word shows a SIMILARITY?", ["unlike", "similarly", "however"], 1, "Similarly = likewise."),
      order("Put the words in the correct order.", ["Whereas", "letters", "took", "a", "month,", "messages", "arrive", "instantly."], "word", "Whereas + clause 1, clause 2."),
      mist("Find the mistake.", ["My grandfather", "is more", "patient as me."], 2, "than me", "Comparative: more patient than."),
      mc("Which structure works best for an essay comparing many features?", ["point-by-point", "block", "narrative"], 0, "Point-by-point handles many features."),
      fill("Life in the city is ___ (busy) than life in the village.", ["busier"], "Comparative of busy: busier."),
    ],
  },

  // ============================================================ UNIT 9
  {
    slug: "int-grammar-second-third-conditionals",
    level: "INTERMEDIATE", category: "GRAMMAR", title: "Second and Third Conditionals and Regret", topic: "Conditionals",
    difficulty: "CHALLENGING", minutes: 18, prereq: ["int-grammar-verb-patterns", "int-grammar-conditionals"],
    objective: "Use second and third conditionals, wish and if only to talk about unreal present and past situations.",
    tags: ["grammar", "conditionals", "second-conditional", "third-conditional", "wish", "regret", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Grammar", topic: "Second and third conditionals (Unit 9)" },
    sections: [
      text("Conditionals with **unreal situations** are used to imagine, to give advice and to express **regret**. The **verb tense moves back one step** to signal unreality.", "Explanation"),
      table("Second and third conditionals", ["Type", "Structure", "Meaning", "Example"], [
        ["Second", "If + Past Simple, would + base verb", "unreal / improbable present or future", "If I had more money, I would travel."],
        ["Third", "If + Past Perfect, would have + past participle", "unreal past (too late)", "If I had studied, I would have passed."],
        ["Mixed", "If + Past Perfect, would + base verb", "past cause, present result", "If I had taken the job, I would be rich now."],
      ]),
      table("Wishes and regrets", ["Structure", "Meaning", "Example"], [
        ["wish / if only + Past Simple", "regret about the present", "I wish I lived closer to work."],
        ["wish / if only + Past Perfect", "regret about the past", "I wish I had listened to her."],
        ["wish + would", "annoyance about someone's behaviour", "I wish he would stop shouting."],
      ]),
      tip("In the if-clause, we can use were for all persons: If I were you, I would apologise.", "Style"),
    ],
    exercises: [
      mc("If I ___ more money, I would travel the world.", ["have", "had", "would have"], 1, "Second conditional: If + Past Simple."),
      mc("If she ___ harder, she would have passed.", ["studied", "had studied", "would study"], 1, "Third conditional: If + Past Perfect."),
      fill("I wish I ___ (listen) to her advice last year.", ["had listened"], "Regret about the past: wish + Past Perfect."),
      mist("Find the mistake.", ["If I", "would have", "more time, I would help."], 1, "had", "The if-clause uses Past Simple, not would."),
      mc("“If I had taken that job, I ___ rich now.”", ["would be", "would have been", "will be"], 0, "Mixed: past cause, present result."),
      order("Put the words in the correct order.", ["If", "I", "were", "you,", "I", "would", "apologise."], "word", "If + subject + were + you, would + verb."),
    ],
  },
  {
    slug: "int-vocab-synonyms-nuance",
    level: "INTERMEDIATE", category: "VOCABULARY", title: "Synonyms and Lexical Nuance", topic: "Synonyms",
    difficulty: "CHALLENGING", minutes: 14, prereq: ["int-vocab-character-adjectives"],
    objective: "Distinguish near-synonyms by meaning, strength and register.",
    tags: ["vocabulary", "synonyms", "nuance", "register", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Vocabulary", topic: "Synonyms (Unit 9)" },
    sections: [
      text("**Synonyms** have similar meanings but rarely identical ones. They differ in **strength**, **register** (formal / informal) and **collocation**. Choose the one that fits the **context**."),
      table("Nuance", ["Word group", "Difference"], [
        ["big · large · huge · enormous", "size increases; huge and enormous are stronger"],
        ["happy · delighted · thrilled", "delighted and thrilled are stronger than happy"],
        ["cheap · inexpensive · affordable", "cheap can sound negative (poor quality); inexpensive and affordable are neutral / positive"],
        ["begin · start · commence", "commence is formal"],
        ["buy · purchase", "purchase is formal"],
        ["job · occupation · profession", "profession = requires training; occupation is formal"],
      ]),
      list("Tips", ["Check a learner dictionary for examples.", "Notice which words go together (heavy rain, not strong rain).", "Use a thesaurus with care: check that the synonym fits."]),
    ],
    exercises: [
      match("Match the word with its nuance.", [["huge", "very big"], ["thrilled", "very happy"], ["commence", "formal for begin"], ["cheap", "low price, maybe poor quality"]], "Synonyms differ in strength and register."),
      mc("Which is the most FORMAL?", ["begin", "start", "commence"], 2, "Commence is formal."),
      mc("Which sentence sounds most natural?", ["We had heavy rain.", "We had strong rain.", "We had big rain."], 0, "Heavy rain is the collocation."),
      mist("Find the mistake.", ["She was", "very thrilled", "about the news."], 1, "thrilled", "Thrilled already means very happy, so very is unnecessary."),
      mc("Which word is stronger than “tired”?", ["exhausted", "sleepy", "relaxed"], 0, "Exhausted = extremely tired."),
      fill("The instructions were ___ (very clear): I understood immediately.", [["straightforward", "clear"]], "Choose a suitable synonym."),
    ],
  },
  {
    slug: "int-reading-money-matters",
    level: "INTERMEDIATE", category: "READING", title: "Reading: Money Matters", topic: "Argument and evidence",
    difficulty: "CHALLENGING", minutes: 18, prereq: ["int-reading-olden-days"],
    objective: "Identify claims, evidence and hedging in an argumentative article.",
    tags: ["reading", "argument", "evidence", "hedging", "conditionals", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Reading", topic: "Money matters (Unit 9)" },
    sections: [
      text("In an argumentative text, separate **claims** (what the writer says is true) from **evidence** (studies, examples) and notice **hedging** words such as *suggest, seem, probably, may*.", "Reading strategy"),
      passage("Example", "Studies suggest that people who exercise regularly sleep better. This may be because exercise reduces stress.", "Hedging: suggest, may"),
      list("Guided practice", ["Claim → exercise improves sleep.", "Evidence → studies.", "Hedge → suggest, may (not proven)."]),
    ],
    exercises: [
      mc("According to economists, what happens once basic needs are met?", ["extra income makes less difference to satisfaction", "people become poorer", "people stop working"], 0, "“a smaller and smaller difference”.", MONEY),
      mc("What seems to give longer-lasting pleasure?", ["spending on experiences", "spending on objects", "saving all money"], 0, "“experiences… longer-lasting pleasure”.", MONEY),
      mc("What often makes people feel better than spending on themselves?", ["giving money to others", "buying gadgets", "paying taxes"], 0, "“giving money to others”.", MONEY),
      tf("The writer claims that money is unimportant.", false, "“these findings do not mean that money is unimportant”.", MONEY),
      mc("Which word shows hedging (the writer is not certain)?", ["probably", "always", "definitely"], 0, "“would probably worry less”.", MONEY),
      mc("What is the main conclusion?", ["Beyond a certain point, what you do with money matters more than how much you have.", "Money is the key to happiness.", "Experiences are expensive."], 0, "The last sentence.", MONEY),
    ],
  },
  {
    slug: "int-writing-essay-2-argumentative",
    level: "INTERMEDIATE", category: "WRITING", title: "Essay 2: Discursive Logic and Argumentative Writing (200 words)", topic: "Argumentative essay",
    difficulty: "CHALLENGING", minutes: 24, prereq: ["int-writing-comparative-essays", "int-writing-essay-1-paragraph-logic", "int-grammar-second-third-conditionals"],
    objective: "Plan and write a 200-word argumentative essay with a clear thesis, counter-argument, evidence and a logical conclusion.",
    tags: ["writing", "argumentative", "essay", "counter-argument", "assessment-practice", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Writing", topic: "Essay 2: discursive logic (Units 7-9)" },
    sections: [
      text("Essay 2 tests **discursive logic**: a thesis, **reasons with evidence**, a **counter-argument** with a rebuttal and a **conclusion** that follows. Aim for about **200 words** in four paragraphs.", "Explanation"),
      table("Plan for 200 words", ["Paragraph", "Words", "Content"], [
        ["1 Introduction", "40", "topic + thesis (your position)"],
        ["2 Reason 1", "60", "topic sentence, explanation, example"],
        ["3 Counter-argument", "60", "the opposite view and why it is weaker (rebuttal)"],
        ["4 Conclusion", "40", "restate position; broader implication"],
      ]),
      table("Language for argument", ["Function", "Phrases"], [
        ["Position", "In my opinion, … · I firmly believe that … · This essay argues that …"],
        ["Evidence", "For example, … · Research suggests that … · According to …"],
        ["Counter-argument", "Some people argue that … · It is often claimed that …"],
        ["Rebuttal", "However, this overlooks … · Nevertheless, … · On the contrary, …"],
        ["Result", "As a result, … · Consequently, … · If governments invested more, schools would improve."],
      ]),
      annotated("Model counter-argument paragraph", [
        ["Opposing view", "Some people argue that money is the main source of happiness."],
        ["Rebuttal", "However, this overlooks the fact that many wealthy people are dissatisfied."],
        ["Evidence", "Research suggests that time with family matters more than income."],
      ]),
      tip("A rebuttal is not a rejection. First fairly present the other side, then explain why your position is stronger.", "Argument"),
    ],
    exercises: [
      order("Put the parts of the argumentative essay in order.", ["Introduction with thesis", "Reason with evidence", "Counter-argument and rebuttal", "Conclusion"], "paragraph", "Thesis, support, counter-argument, conclusion."),
      mc("Which sentence introduces a counter-argument?", ["Some people argue that money is the key to happiness.", "In conclusion, money is important.", "For example, my uncle is rich."], 0, "Some people argue that … = opposing view."),
      mc("Which sentence is a rebuttal?", ["However, this overlooks the fact that many wealthy people are dissatisfied.", "Some people are rich.", "Money is nice."], 0, "However, this overlooks … answers the opposing view."),
      mist("Find the mistake (hedging).", ["Research", "proves absolutely", "that experiences bring happiness."], 1, "suggests", "Academic writing avoids overly strong claims."),
      fill("If governments ___ (invest) more in schools, results would improve.", ["invested"], "Second conditional in the if-clause."),
      mc("How long is Essay 2?", ["about 200 words", "about 20 words", "about 800 words"], 0, "The assessment target is about 200 words."),
    ],
  },
];

void [compare, sa, structure, tip, vocab, annotated];
