import { HW, annotated, compare, examples, fill, flow, list, match, mc, ms, mist, order, passage, sa, structure, table, text, tf, tip, vocab, type SeedLesson } from "./dsl";

// Intermediate course, Units 1-3. Topics follow the academy's syllabus; all text is ORIGINAL.

const MATTERS = "AN INTERVIEW: WHAT MATTERS TO YOU?\n\nYousef Al Farsi, 28, is an architect who lives in Muscat. We asked him about his priorities.\n\n“Family comes first,” he says. “I've been close to my parents and my two sisters all my life, and I see them every Friday. Then there's my work. I don't just design buildings: I try to make places where people feel comfortable.”\n\nWe asked Yousef what he never leaves the house without. “My phone, obviously, but also a small notebook. I sketch ideas everywhere: on the bus, in cafés, even while I'm waiting for a meeting to start. My travel card is always in my wallet, because I take public transport whenever I can.”\n\nHe is currently learning to play the oud, which he finds difficult but relaxing. “What matters to me, in the end, is not being busy,” he says. “It's doing things that are worth doing.”";
const LANG_FACTS = "LANGUAGE FACTS\n\nExperts estimate that there are around 7,000 languages in the world, yet almost half of the world's population speaks only a small number of them. Mandarin Chinese is spoken as a first language by more people than any other language, while English is the language that is most widely learned as a second language.\n\nMany languages are spoken by very few people. It is believed that a large number of them are in danger of disappearing, because they are no longer taught to children. Efforts are being made to record and teach these languages before they are lost.\n\nArabic is used across many countries, and it is written from right to left. Every year, new words are added to dictionaries in every language, which shows that languages are constantly changing.";
const NEIGHBOUR = "WELCOMING A NEW NEIGHBOUR\n\nEva had only been in the flat for two hours when the doorbell rang. A woman in a bright blue coat was standing outside with a plate of biscuits.\n\n“I'm Mrs Harding, from number six,” she said, walking in before Eva could reply. “I saw the van. Are you married? Do you work? You look terribly young to be living alone.”\n\nEva smiled politely. “I'm a student,” she said. “I'm studying medicine.” “How wonderful,” said Mrs Harding, looking round the room. “The last tenant left in a hurry, you know. Some people said there'd been a lot of arguments.” She put the plate down. “Anyway, if you ever need anything, I'm always here. I'm usually alone.”\n\nWhen the door closed, Eva looked at the biscuits. They were still warm. She wasn't sure whether she had been welcomed or examined, but she decided to eat one anyway.";

export const INT_U1_U3: SeedLesson[] = [
  // ============================================================ UNIT 1
  {
    slug: "int-grammar-tense-review",
    level: "INTERMEDIATE", category: "GRAMMAR", title: "Tense Review: Consolidating the Main Tenses", topic: "Tense review",
    difficulty: "CORE", minutes: 16, prereq: ["pre-int-grammar-second-conditional"],
    objective: "Review and contrast the Present Simple, Present Continuous, Past Simple and Present Perfect to describe people and their lives.",
    tags: ["grammar", "tenses", "tense-review", "present-perfect", "past-simple", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Grammar", topic: "Tense review (Unit 1)" },
    sections: [
      text("At Intermediate level the aim is **accuracy and choice**: knowing not only how to form a tense but **why** you choose it. Use time expressions and the writer's **point of view** (finished, in progress, connected to now) to decide.", "Explanation"),
      table("Tense review", ["Tense", "Form", "Main use", "Example"], [
        ["Present Simple", "base verb (+ s)", "habits, permanent facts, states", "He works in a hospital."],
        ["Present Continuous", "am / is / are + -ing", "in progress now; temporary; changing", "I'm working on a new project."],
        ["Past Simple", "verb-ed / irregular", "finished action, definite time", "She graduated in 2019."],
        ["Present Perfect Simple", "have / has + past participle", "experience; result now; unfinished time", "I've visited Cairo twice."],
      ]),
      list("How to choose", ["**Finished + definite time** (in 2019, last week) → Past Simple.", "**Connected with now / no definite time** → Present Perfect.", "**Happening around now** → Present Continuous.", "**Routine or permanent** → Present Simple."]),
      structure("Structure", "Past Simple: I lived there for five years. (I don't live there now.)\nPresent Perfect: I've lived here for five years. (I still live here.)", "Compare both: the second one continues up to now."),
      compare("Typical errors", [["I am here since Monday.", "I have been here since Monday.", "Unfinished time: Present Perfect."], ["I have seen him yesterday.", "I saw him yesterday.", "Definite past time: Past Simple."], ["She is knowing the answer.", "She knows the answer.", "State verbs are not used in the continuous."]]),
    ],
    exercises: [
      mc("I ___ in Muscat since 2018, and I really like it.", ["live", "have lived", "lived"], 1, "Unfinished time with since: Present Perfect."),
      mc("She ___ university in 2019, and she now works for an international company.", ["has finished", "finished", "is finishing"], 1, "Definite finished time: Past Simple."),
      fill("Right now, I ___ (write) a report, and I ___ (not / finish) yet.", ["am writing", "haven't finished"], "Continuous for in progress; Present Perfect + yet."),
      mist("Find the mistake.", ["We", "are living", "here for ten years."], 1, "have lived", "Duration up to now: have lived."),
      match("Which tense and why?", [["He usually walks to work.", "Present Simple (habit)"], ["He is walking to work today because his car broke down.", "Present Continuous (temporary)"], ["He walked to work yesterday.", "Past Simple (finished)"], ["He has walked to work for years.", "Present Perfect (unfinished)"]], "Match the tense with the reason."),
      order("Put the words in the correct order.", ["Have", "you", "ever", "worked", "in", "another", "country?"], "word", "Have + subject + ever + past participle."),
    ],
  },
  {
    slug: "int-grammar-auxiliary-verbs",
    level: "INTERMEDIATE", category: "GRAMMAR", title: "Auxiliary Verbs: be, do and have", topic: "Auxiliary verbs",
    difficulty: "CORE", minutes: 14, prereq: ["int-grammar-tense-review"],
    objective: "Use be, do and have as auxiliaries to form questions, negatives, short answers and emphatic sentences without omitting them.",
    tags: ["grammar", "auxiliary-verbs", "questions", "negatives", "short-answers", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Grammar", topic: "Auxiliary verbs: be, do, have (Unit 1)" },
    sections: [
      text("**Auxiliary verbs** (helping verbs) do not carry the main meaning: they help to make **tenses, questions and negatives**. **Be**, **do** and **have** are the three main auxiliaries.", "Explanation"),
      table("The three auxiliaries", ["Auxiliary", "Used to form", "Example"], [
        ["be", "continuous tenses and the passive", "She is studying. The room was cleaned."],
        ["do / does / did", "questions and negatives in Present Simple and Past Simple", "Do you agree? He didn't come."],
        ["have / has / had", "perfect tenses", "I have finished. She had left."],
      ]),
      list("Where auxiliaries appear", ["**Questions**: auxiliary before the subject: Where do you live? Have you finished?", "**Negatives**: auxiliary + not: I don't know. She hasn't arrived.", "**Short answers**: repeat the auxiliary: Yes, I do. / No, he isn't.", "**Emphasis and agreement**: I DO like it. So do I. Neither has he."]),
      structure("Structure", "Question word + auxiliary + subject + main verb?", "Omitting the auxiliary is a common error: *Where you live?* → Where do you live? The short form for am not is I'm not (not *amn't*), but in questions we say Aren't I?"),
    ],
    exercises: [
      mist("Find the mistake.", ["Where", "you", "live?"], 1, "do you", "The auxiliary do is missing: Where do you live?"),
      mc("“Have you finished?” “Yes, I ___.”", ["do", "have", "am"], 1, "The short answer repeats the auxiliary: Yes, I have."),
      fill("She ___ not arrived yet. She ___ still working.", ["has", "is"], "has not arrived (Present Perfect); is working (continuous)."),
      mc("“I love this song.” “So ___ I.”", ["do", "am", "have"], 0, "So + auxiliary + subject: So do I."),
      order("Put the words in the correct order.", ["What", "time", "did", "the", "meeting", "start?"], "word", "Question word + did + subject + base verb."),
      mist("Find the mistake.", ["I", "amn't", "ready yet."], 1, "'m not", "There is no short form amn't: use I'm not."),
    ],
  },
  {
    slug: "int-vocab-verb-categories",
    level: "INTERMEDIATE", category: "VOCABULARY", title: "Categorising Verbs: Auxiliary, Modal and Full Verbs", topic: "Verb types",
    difficulty: "CORE", minutes: 12, prereq: ["int-grammar-auxiliary-verbs"],
    objective: "Classify verbs as auxiliary, modal or full (lexical) verbs and understand how each behaves.",
    tags: ["vocabulary", "grammar-terms", "auxiliary-verbs", "modal-verbs", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Vocabulary", topic: "Categorising verbs (Unit 1)" },
    sections: [
      text("Knowing the **category** of a verb helps you use it correctly. There are **three main categories**."),
      table("Verb categories", ["Category", "Examples", "How it behaves"], [
        ["Auxiliary", "be, do, have", "helps other verbs; makes questions, negatives and tenses"],
        ["Modal", "can, could, must, should, may, might, will, would", "adds meaning (ability, obligation, possibility); no -s; followed by base verb"],
        ["Full (lexical)", "work, study, arrive, consider, remember", "carries the main meaning; takes -s, -ed, -ing"],
      ]),
      list("Tests", ["A modal has **no -s** (she can, not she cans) and **no to** after it (must go, not must to go).", "**Be, do, have** can be auxiliary or full verb: She has a car (full). She has finished (auxiliary).", "A full verb needs **do** to make a question or negative: Do you work? (not *Work you?*)"]),
    ],
    exercises: [
      match("Which category?", [["can", "modal"], ["have (in “I have finished”)", "auxiliary"], ["arrive", "full verb"], ["must", "modal"], ["did (in “Did you go?”)", "auxiliary"]], "Modals add meaning; auxiliaries help; full verbs carry the meaning."),
      mc("Which verb is used as a FULL verb?", ["She has finished.", "She has a car.", "She has been working."], 1, "In She has a car, has means owns."),
      mist("Find the mistake.", ["She", "cans", "speak three languages."], 1, "can", "A modal verb has no -s."),
      mc("Which sentence is correct?", ["He must to leave early.", "He must leave early.", "He musts leave early."], 1, "Modal + base verb."),
      fill("She ___ not want to come. (auxiliary needed for a negative with a full verb)", ["does"], "Full verb want → does not want."),
      mc("Which is NOT a modal verb?", ["should", "might", "study"], 2, "Study is a full verb."),
    ],
  },
  {
    slug: "int-vocab-personal-objects",
    level: "INTERMEDIATE", category: "VOCABULARY", title: "Personal Objects and What They Say About Us", topic: "Objects",
    difficulty: "CORE", minutes: 12, prereq: ["int-vocab-verb-categories"],
    objective: "Describe personal possessions precisely and explain why they matter.",
    tags: ["vocabulary", "objects", "description", "personal-narrative", "listening-support", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Vocabulary", topic: "Personal objects and global facts (Unit 1)" },
    sections: [
      text("The things we carry say a lot about our lives. **Concrete nouns** make personal writing specific. Use adjectives and **reasons** to make them meaningful."),
      vocab([
        { word: "travel card", pos: "noun", meaning: "a card you use to pay for public transport", ar: "بطاقة مواصلات", pron: "/ˈtrævl kɑːd/", ex: "He always keeps his travel card in his wallet.", col: ["top up a travel card"], visual: "🎫" },
        { word: "notebook", pos: "noun", meaning: "a small book for writing notes or ideas", ar: "دفتر", pron: "/ˈnəʊtbʊk/", ex: "She sketches ideas in a small notebook.", col: ["keep a notebook"], visual: "📓" },
        { word: "wallet", pos: "noun", meaning: "a small flat case for money and cards", ar: "محفظة", pron: "/ˈwɒlɪt/", ex: "I lost my wallet on the bus.", col: ["a leather wallet"], visual: "👛" },
        { word: "charger", pos: "noun", meaning: "a device that gives power to a phone", ar: "شاحن", pron: "/ˈtʃɑːdʒə/", ex: "Don't forget your charger.", col: ["a phone charger"], visual: "🔌" },
        { word: "keepsake", pos: "noun", meaning: "a small object you keep to remember a person or place", ar: "تذكار عزيز", pron: "/ˈkiːpseɪk/", ex: "The watch is a keepsake from my grandfather.", col: ["a treasured keepsake"], visual: "⌚" },
      ], "Objects"),
      list("Useful patterns", ["I never leave the house without my …", "It's important to me because …", "I've had it since …", "It reminds me of …"]),
    ],
    exercises: [
      match("Match the object with its purpose.", [["travel card", "paying for buses and trains"], ["notebook", "writing down ideas"], ["wallet", "carrying money and cards"], ["charger", "powering a phone"]], "Each object has a practical purpose."),
      mc("The old watch is a ___ from my grandfather. I keep it in a drawer.", ["keepsake", "charger", "travel card"], 0, "A keepsake reminds you of a person."),
      fill("I never leave the house ___ my phone.", ["without"], "never leave the house without …"),
      mist("Find the mistake.", ["I've", "had", "this notebook since three years."], 2, "for three years", "Use for with a period of time; since with a starting point."),
      mc("Which phrase explains WHY an object matters?", ["It reminds me of my childhood.", "It costs ten rials.", "It is made of plastic."], 0, "Personal reasons make an object meaningful."),
      sa("A small object you keep to remember someone: a ___", ["keepsake"], "keepsake.", { hint: "k _ _ _ _ _ _ e" }),
    ],
  },
  {
    slug: "int-reading-what-matters",
    level: "INTERMEDIATE", category: "READING", title: "Reading: What Matters to Me", topic: "Personal priorities",
    difficulty: "CORE", minutes: 16, prereq: ["int-reading-multiple-choice"],
    objective: "Analyse an interview to identify a person's priorities and the details that support them.",
    tags: ["reading", "reading-details", "reading-main-idea", "interview", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Reading", topic: "What matters to me: an interview (Unit 1)" },
    sections: [
      text("An **interview article** gives you the interviewer's framing and the speaker's own words. To find someone's **priorities**, look for **ranking words** (comes first, most important, what matters) and **repeated ideas**.", "Reading strategy"),
      passage("Example", "“Health is my priority,” says Dr Noor. “I walk every morning and I've been cooking at home for years.”", "Priority + evidence"),
      list("Guided practice", ["Priority → health.", "Evidence → walks every morning; cooks at home.", "Tense clue: have been cooking = a habit that continues now."]),
    ],
    exercises: [
      mc("What does Yousef say comes first?", ["his work", "his family", "his hobbies"], 1, "“Family comes first.”", MATTERS),
      mc("How often does he see his family?", ["every Friday", "every day", "once a month"], 0, "“I see them every Friday.”", MATTERS),
      mc("Which object does he mention as always being in his wallet?", ["his travel card", "his notebook", "his phone"], 0, "“My travel card is always in my wallet.”", MATTERS),
      mc("Why does he always carry a notebook?", ["He sketches ideas everywhere.", "He forgets things.", "He writes letters."], 0, "“I sketch ideas everywhere.”", MATTERS),
      tf("Yousef finds learning the oud easy.", false, "“which he finds difficult but relaxing”.", MATTERS),
      mc("What does the last quotation suggest about his real priority?", ["doing worthwhile things rather than being busy", "earning more money", "learning music"], 0, "“It's doing things that are worth doing.”", MATTERS),
    ],
  },
  {
    slug: "int-writing-personal-profile",
    level: "INTERMEDIATE", category: "WRITING", title: "Developing a Personal Profile", topic: "Profile writing",
    difficulty: "CORE", minutes: 18, prereq: ["int-grammar-auxiliary-verbs"],
    objective: "Write a coherent personal profile using a mix of tenses and precise vocabulary.",
    tags: ["writing", "profile", "tenses", "biography", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Writing", topic: "Personal profile (Unit 1)" },
    sections: [
      text("A **personal profile** presents you (or another person) in a **clear, engaging** way. It moves from **background** to **present** and **future**, using the right tense for each part.", "Explanation"),
      table("Structure of a profile", ["Part", "Content", "Tenses"], [
        ["Who you are", "name, age, place, job or study", "Present Simple"],
        ["Background", "education, experience, key events", "Past Simple, Present Perfect"],
        ["Now", "current activity and interests", "Present Simple, Present Continuous"],
        ["Future", "goals and plans", "going to, would like to, hope to"],
      ]),
      annotated("Model profile (about 100 words)", [
        ["Who", "Yousef Al Farsi is a 28-year-old architect from Muscat. He has always been fascinated by buildings and how people use them."],
        ["Background", "He studied architecture in Cairo, and he has worked for the same firm for five years."],
        ["Now", "At the moment he is designing a small library, and in his free time he is learning to play the oud."],
        ["Future", "In the next few years he hopes to open his own studio."],
      ]),
      tip("Do not list facts one after another. Join them with linking words and vary the sentence openings.", "Style"),
    ],
    exercises: [
      order("Put the sentences in the correct order to make a profile.", ["Yousef Al Farsi is a 28-year-old architect from Muscat.", "He studied architecture in Cairo and has worked for the same firm for five years.", "At the moment he is designing a small library.", "In the next few years he hopes to open his own studio."], "paragraph", "Who, background, now, future."),
      mc("Which sentence belongs in the BACKGROUND part?", ["He studied architecture in Cairo.", "He hopes to open a studio.", "He is designing a library."], 0, "Past events are background."),
      fill("He ___ (work) for the same firm for five years. (still works there)", ["has worked"], "Unfinished time: Present Perfect."),
      mist("Find the mistake.", ["He is working", "for the same firm", "since 2019."], 0, "has been working", "Duration with since: Present Perfect (Continuous)."),
      order("Put the words in the correct order.", ["In", "the", "future,", "she", "hopes", "to", "study", "abroad."], "word", "Time phrase + subject + verb + to-infinitive."),
      mc("Which opening is most engaging for a profile?", ["Layla Nasser is a nurse who never stops learning.", "Layla is a nurse.", "This is about Layla."], 0, "A specific, interesting first sentence."),
    ],
  },

  // ============================================================ UNIT 2
  {
    slug: "int-grammar-present-simple-vs-continuous",
    level: "INTERMEDIATE", category: "GRAMMAR", title: "Present Simple and Present Continuous: States and Actions", topic: "Present tenses",
    difficulty: "CORE", minutes: 14, prereq: ["int-grammar-auxiliary-verbs"],
    objective: "Choose accurately between Present Simple and Present Continuous, including changing situations and habits with always.",
    tags: ["grammar", "present-simple", "present-continuous", "tenses", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Grammar", topic: "Present Simple and Continuous (Unit 2)" },
    sections: [
      text("The **Present Simple** describes **facts, habits and states**. The **Present Continuous** describes **actions in progress, temporary situations and changes**.", "Explanation"),
      table("Simple or Continuous?", ["Feature", "Present Simple", "Present Continuous"], [
        ["Meaning", "permanent, repeated, general", "in progress, temporary, changing"],
        ["Example", "She teaches biology.", "She is teaching a summer course."],
        ["Time words", "always, usually, every day", "now, at the moment, these days, this year"],
      ]),
      list("Special uses", ["**Changing situations**: Prices are rising. More people are working from home.", "**Annoying habits** with always: He's always leaving his things everywhere.", "**Story telling / headlines**: The president arrives in Cairo today. (Present Simple)"]),
      structure("Structure", "Simple: subject + verb(s)\nContinuous: subject + be + verb-ing", "Some verbs (state verbs) are not normally used in the continuous. See the next lesson."),
    ],
    exercises: [
      mc("More and more people ___ from home these days.", ["work", "are working", "have worked"], 1, "A changing situation: Present Continuous."),
      mc("Water ___ at 100°C.", ["boils", "is boiling", "boiled"], 0, "A general fact: Present Simple."),
      fill("He ___ (always / leave) the lights on! It's so annoying.", ["is always leaving"], "always + continuous = a repeated annoying habit."),
      mist("Find the mistake.", ["I", "am working", "in a bank. I like it very much."], 1, "work", "A permanent situation: Present Simple."),
      match("Simple or continuous?", [["She teaches biology.", "permanent"], ["She's teaching a summer course.", "temporary"], ["Prices are rising.", "changing"], ["He plays chess on Fridays.", "habit"]], "Match the use."),
      order("Put the words in the correct order.", ["What", "are", "you", "working", "on", "at", "the", "moment?"], "word", "Wh-word + are + subject + verb-ing."),
    ],
  },
  {
    slug: "int-grammar-state-vs-action-verbs",
    level: "INTERMEDIATE", category: "GRAMMAR", title: "State Verbs and Action Verbs: Avoiding Continuous Errors", topic: "State verbs",
    difficulty: "CORE", minutes: 12, prereq: ["int-grammar-present-simple-vs-continuous"],
    objective: "Distinguish state verbs from action verbs and use verbs with two meanings correctly.",
    tags: ["grammar", "state-verbs", "action-verbs", "present-continuous", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Grammar", topic: "State verbs vs activity verbs (Unit 2)" },
    sections: [
      text("**State verbs** describe **states** (thoughts, feelings, possession, senses), not actions. They are **not used in continuous tenses**. Some verbs can be both, with **different meanings**.", "Explanation"),
      table("State verbs", ["Group", "Verbs", "Example"], [
        ["Thinking", "know, understand, believe, remember, doubt", "I understand the question."],
        ["Feeling / wanting", "like, love, hate, prefer, want, need", "She needs more time."],
        ["Possession / relationship", "own, belong, have (possess), contain", "This bag belongs to me."],
        ["Senses / appearance", "seem, appear, sound, smell (state)", "That sounds interesting."],
      ]),
      table("Verbs with two meanings", ["Verb", "State (simple)", "Action (continuous)"], [
        ["think", "I think it's a good idea. (opinion)", "I'm thinking about my holiday. (process)"],
        ["have", "She has a car. (own)", "She's having lunch. (eat)"],
        ["see", "I see what you mean. (understand)", "I'm seeing my doctor tomorrow. (meet)"],
        ["taste", "The soup tastes salty. (quality)", "He is tasting the soup. (action)"],
      ]),
    ],
    exercises: [
      mc("I ___ the answer. It's on the tip of my tongue.", ["don't remember", "am not remembering", "not remember"], 0, "Remember (state) is not used in the continuous."),
      mist("Find the mistake.", ["She", "is owning", "three houses."], 1, "owns", "Own is a state verb."),
      mc("Which sentence describes an ACTION?", ["I think you are right.", "I'm thinking about changing my job.", "I know his name."], 1, "Thinking about = a mental process."),
      fill("Can you wait? I ___ (have) lunch at the moment.", ["am having"], "have = eat: an action, so continuous is correct."),
      match("State or action?", [["belong", "state"], ["run", "action"], ["doubt", "state"], ["build", "action"]], "State verbs are not used in the continuous."),
      mist("Find the mistake.", ["I", "am understanding", "the problem now."], 1, "understand", "Understand is a state verb."),
    ],
  },
  {
    slug: "int-grammar-passive-facts-processes",
    level: "INTERMEDIATE", category: "GRAMMAR", title: "The Passive for Facts and Processes", topic: "Passive voice",
    difficulty: "CORE", minutes: 14, prereq: ["int-grammar-passive", "int-grammar-state-vs-action-verbs"],
    objective: "Use the passive in different tenses and with modals to describe facts and processes, focusing on the data rather than the agent.",
    tags: ["grammar", "passive-voice", "processes", "academic-writing", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Grammar", topic: "Passive (Unit 2)" },
    sections: [
      text("In academic and factual writing, the **passive** shifts the focus from **who does** something to **what is done**. It is common in **descriptions of processes**, **reports** and **statistics**.", "Explanation"),
      table("Passive forms", ["Tense / modal", "Form", "Example"], [
        ["Present Simple", "am / is / are + participle", "Arabic is spoken in many countries."],
        ["Past Simple", "was / were + participle", "The first dictionary was published in 1604."],
        ["Present Perfect", "has / have been + participle", "Thousands of new words have been added."],
        ["Modal", "modal + be + participle", "Languages can be lost quickly. The data must be checked."],
        ["Continuous", "is / are being + participle", "New words are being added every year."],
      ]),
      list("When to use the passive", ["The agent is unknown, obvious or unimportant: The report was published last year.", "The result is more important than the doer: Over 7,000 languages are spoken today.", "Formal or scientific style: The samples were heated to 80°C.", "Add the agent with by only if it is important: The report was written by a team of experts."]),
      structure("Structure", "subject + be (+ been / being) + past participle (+ by agent)", "The passive of a modal: can be done · must be done · should be done."),
    ],
    exercises: [
      fill("Thousands of new words ___ (add) to the dictionary every year.", ["are added"], "Present Simple passive."),
      fill("The results ___ (publish) next month.", ["will be published"], "will be + participle."),
      mist("Find the mistake.", ["The samples", "was heated", "to 80°C."], 1, "were heated", "Samples is plural: were."),
      mc("New words ___ into the language at this very moment.", ["are being added", "have added", "were adding"], 0, "In progress now: are being added."),
      sa("Rewrite in the passive: People speak Arabic in many countries. → Arabic ___ in many countries.", ["is spoken"], "Present Simple passive.", { hint: "is + participle" }),
      order("Put the words in the correct order.", ["Many", "languages", "are", "in", "danger", "of", "disappearing."], "word", "Subject + are + in danger of + -ing."),
    ],
  },
  {
    slug: "int-vocab-phrasal-verbs-journeys",
    level: "INTERMEDIATE", category: "VOCABULARY", title: "Phrasal Verbs for Journeys and Relationships", topic: "Phrasal verbs",
    difficulty: "CORE", minutes: 14, prereq: ["int-vocab-personal-objects"],
    objective: "Use common phrasal verbs connected with travelling and personal relationships.",
    tags: ["vocabulary", "phrasal-verbs", "travel", "relationships", "listening-support", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Vocabulary", topic: "Phrasal verbs: journeys (Unit 2)" },
    sections: [
      text("Phrasal verbs are extremely common in everyday English. Learn them **in context** and note whether they are **separable** (pick up the bag / pick the bag up) or **inseparable** (look after the children)."),
      table("Journeys", ["Phrasal verb", "Meaning", "Example"], [
        ["set off", "start a journey", "We set off at dawn to avoid the traffic."],
        ["pick up", "collect a person or thing", "Can you pick me up from the station?"],
        ["drop off", "take someone somewhere and leave them", "I'll drop you off at the airport."],
        ["check in", "register on arrival", "You must check in two hours before your flight."],
        ["get back", "return", "We got back late last night."],
        ["break down", "stop working (a vehicle)", "Our car broke down on the motorway."],
      ]),
      table("Relationships", ["Phrasal verb", "Meaning", "Example"], [
        ["split up", "end a relationship", "They split up after ten years."],
        ["get on (with)", "have a good relationship", "I get on well with my colleagues."],
        ["fall out (with)", "have an argument and stop being friends", "He fell out with his brother."],
        ["make up", "become friends again", "They argued but made up quickly."],
      ]),
    ],
    exercises: [
      match("Match the phrasal verb with its meaning.", [["set off", "start a journey"], ["split up", "end a relationship"], ["pick up", "collect someone"], ["break down", "stop working"], ["make up", "become friends again"]], "Learn each phrasal verb with its meaning."),
      mc("Our car ___ on the motorway, so we arrived two hours late.", ["broke down", "set off", "got back"], 0, "broke down = stopped working."),
      fill("I'll ___ you off at the airport on my way to work.", ["drop"], "drop someone off."),
      mist("Find the mistake.", ["They", "fell out", "with their neighbours and became close friends."], 1, "get on", "Fell out means argued; the sentence needs a positive relationship."),
      mc("Which sentence is correct?", ["Can you pick up me?", "Can you pick me up?", "Can you pick up to me?"], 1, "With a pronoun, the object goes in the middle."),
      order("Put the words in the correct order.", ["We", "set", "off", "early", "to", "avoid", "the", "traffic."], "word", "Subject + set off + adverb + to + verb."),
    ],
  },
  {
    slug: "int-reading-language-facts",
    level: "INTERMEDIATE", category: "READING", title: "Reading: Language Facts", topic: "Synthesising information",
    difficulty: "CORE", minutes: 16, prereq: ["int-reading-what-matters"],
    objective: "Synthesise global information from a factual text and recognise how the passive shifts focus to the data.",
    tags: ["reading", "reading-details", "passive-voice", "factual-text", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Reading", topic: "Language facts (Unit 2)" },
    sections: [
      text("Factual texts often use the **passive** and **hedging** (experts estimate, it is believed) because the writer is reporting **data**, not personal opinion. Read for **numbers**, **comparisons** and **cause-and-effect**.", "Reading strategy"),
      passage("Example", "It is estimated that 70 percent of the world's freshwater is used for farming. As a result, water is being carefully managed in many regions.", "Data + effect"),
      list("Guided practice", ["Fact → 70% of freshwater is used for farming.", "Hedge → it is estimated (not certain).", "Effect → water is being carefully managed."]),
    ],
    exercises: [
      mc("About how many languages are there in the world?", ["around 700", "around 7,000", "around 70,000"], 1, "“around 7,000 languages”.", LANG_FACTS),
      mc("Which language has the most first-language speakers?", ["English", "Mandarin Chinese", "Arabic"], 1, "“Mandarin Chinese is spoken as a first language by more people than any other language”.", LANG_FACTS),
      mc("Why are many small languages in danger?", ["They are no longer taught to children.", "They are too difficult.", "They have no words."], 0, "“no longer taught to children”.", LANG_FACTS),
      tf("The text states exactly how many languages will disappear.", false, "It uses hedging: “It is believed that a large number of them are in danger”.", LANG_FACTS),
      mc("Why does the text use “It is believed”?", ["The information is an estimate, not a certain fact.", "The writer is angry.", "It is a quotation."], 0, "The passive with believe shows that it is not proven.", LANG_FACTS),
      mc("What does the last paragraph show about languages?", ["They are constantly changing.", "They are never written down.", "They are all the same."], 0, "“languages are constantly changing”.", LANG_FACTS),
    ],
  },
  {
    slug: "int-writing-sentence-variety",
    level: "INTERMEDIATE", category: "WRITING", title: "Improving Style through Sentence Variety", topic: "Style",
    difficulty: "CORE", minutes: 16, prereq: ["int-writing-personal-profile"],
    objective: "Vary sentence length and structure by combining short sentences and changing how sentences begin.",
    tags: ["writing", "style", "sentence-variety", "cohesion", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Writing", topic: "Improving style: sentence variety (Unit 2)" },
    sections: [
      text("A text made only of **short, similar sentences** sounds **choppy**. A text with **varied** sentences reads more smoothly and shows greater control. Use three techniques.", "Explanation"),
      table("Three techniques", ["Technique", "Example (before → after)"], [
        ["Combine with a conjunction", "It was raining. We stayed inside. → It was raining, so we stayed inside."],
        ["Start with a different word", "We arrived late. → Unfortunately, we arrived late. / Exhausted, we arrived late."],
        ["Use a participle or relative clause", "Fatima is a teacher. She lives in Nizwa. → Fatima, who lives in Nizwa, is a teacher."],
      ]),
      passage("Before (choppy)", "The museum opened in 2010. It is in Muscat. It is very popular. Many tourists visit it. It has a large garden.", "Repetitive"),
      passage("After (varied)", "The museum, which opened in 2010, is very popular with tourists. Located in Muscat, it also has a large garden.", "Varied"),
    ],
    exercises: [
      sa("Combine with a conjunction: It was raining. We stayed inside. → It was raining, ___ we stayed inside.", ["so"], "so shows result.", { hint: "so" }),
      mc("Which version has the best sentence variety?", ["The museum is old. It is big. It is famous.", "Famous for its size and age, the museum is one of the city's main attractions.", "The museum is old and big and it is famous and it is in the city."], 1, "The second combines ideas with a participial phrase."),
      mc("Which opener adds variety? “___, we decided to leave early.”", ["Feeling tired", "We were tired and", "It was that"], 0, "A participle phrase opens the sentence."),
      order("Put the words in the correct order.", ["Fatima,", "who", "lives", "in", "Nizwa,", "is", "a", "teacher."], "word", "Noun + relative clause + main verb."),
      mc("Which is the best way to improve: “I like the city. I like the people. I like the food.”?", ["I like the city, the people and the food.", "I like the city. Also the people. Also the food.", "I like the city and I like the people and I like the food."], 0, "Combining the objects removes the repetition."),
      match("Which technique?", [["Unfortunately, we arrived late.", "different opener"], ["It rained, so we stayed in.", "conjunction"], ["Ali, who is a doctor, lives here.", "relative clause"]], "Name the technique used."),
    ],
  },

  // ============================================================ UNIT 3
  {
    slug: "int-grammar-past-narrative-tenses",
    level: "INTERMEDIATE", category: "GRAMMAR", title: "Past Simple, Past Continuous and Past Perfect", topic: "Narrative tenses",
    difficulty: "CORE", minutes: 16, prereq: ["int-grammar-passive-facts-processes"],
    objective: "Build a narrative with Past Simple (events), Past Continuous (background) and Past Perfect (earlier events).",
    tags: ["grammar", "past-simple", "past-continuous", "past-perfect", "narrative", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Grammar", topic: "Past Simple, Continuous, Perfect (Unit 3)" },
    sections: [
      text("Good narratives use **three past tenses together**: the **Past Simple** for the main events, the **Past Continuous** for background and interrupted actions, and the **Past Perfect** for events that happened **before** the story time.", "Explanation"),
      table("The three tenses", ["Tense", "Form", "Job", "Example"], [
        ["Past Simple", "verb-ed / irregular", "main events in sequence", "She opened the door and saw a stranger."],
        ["Past Continuous", "was / were + -ing", "background; interrupted action", "It was raining when we left."],
        ["Past Perfect", "had + past participle", "earlier past", "She had already left when I arrived."],
      ]),
      list("Time links", ["**when** + Past Simple: I was cooking when the phone rang.", "**while** + Past Continuous: While she was reading, he was cooking.", "**by the time / already / before / after** + Past Perfect: By the time I got there, they had gone."]),
      structure("Structure", "Past Perfect (earlier) → Past Simple (later)\nBackground (was doing) → interruption (Past Simple)", "The Past Perfect is not needed if the order of events is already clear from time words like after and before."),
    ],
    exercises: [
      mc("When I got to the station, the train ___.", ["left", "had left", "was leaving"], 1, "The train left before I arrived: Past Perfect."),
      mc("I ___ dinner when the lights went out.", ["cooked", "was cooking", "had cooked"], 1, "Interrupted background action: Past Continuous."),
      fill("She was upset because she ___ (lose) her passport.", ["had lost"], "Earlier reason: had lost."),
      mist("Find the mistake.", ["While he", "read", "a book, the phone rang."], 1, "was reading", "While + Past Continuous."),
      order("Put the words in the correct order.", ["By", "the", "time", "we", "arrived,", "the", "film", "had", "started."], "word", "By the time + Past Simple, Past Perfect."),
      match("Which tense?", [["The rain was falling heavily.", "Past Continuous (background)"], ["He had never seen the sea before.", "Past Perfect (earlier)"], ["She picked up the letter and read it.", "Past Simple (events)"]], "Match the job of each tense."),
    ],
  },
  {
    slug: "int-grammar-used-to-would",
    level: "INTERMEDIATE", category: "GRAMMAR", title: "used to and would for Past Habits and States", topic: "Past habits",
    difficulty: "CORE", minutes: 12, prereq: ["int-grammar-past-narrative-tenses"],
    objective: "Contrast past habits and states with present situations using used to and would.",
    tags: ["grammar", "used-to", "would", "past-habits", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Grammar", topic: "used to (Unit 3)" },
    sections: [
      text("**Used to** describes **past habits and states** that are **no longer true**. **Would** can describe **repeated past actions** (not states).", "Explanation"),
      table("used to and would", ["Form", "Use", "Example"], [
        ["used to + base verb", "past habits and states", "I used to live in a village. She used to be shy."],
        ["would + base verb", "repeated past actions (not states)", "Every summer we would visit my grandparents."],
        ["didn't use to", "negative", "I didn't use to like coffee."],
        ["Did you use to …?", "question", "Did you use to play football?"],
      ]),
      structure("Structure", "used to + base verb (no -ed on use in negatives and questions: did / didn't use to)", "Would cannot describe states: I would live in a village is wrong. Compare: I used to live in a village."),
      list("Do not confuse", ["**used to do** = past habit: I used to walk to school.", "**be used to doing** = be accustomed: I'm used to walking to school.", "**get used to doing** = become accustomed: I'm getting used to the heat."]),
    ],
    exercises: [
      mc("I ___ in a small village when I was young. (state)", ["would live", "used to live", "was used to live"], 1, "A past state: used to (not would)."),
      mc("Every summer we ___ visit our grandparents in the mountains. (repeated action)", ["would", "used to be", "are used to"], 0, "Would describes repeated actions."),
      mist("Find the mistake.", ["Did you", "used to played", "football as a child?"], 1, "use to play", "After did: use to + base verb."),
      fill("He didn't ___ to like coffee, but now he drinks it every day.", ["use"], "didn't use to."),
      match("Meaning?", [["I used to walk to school.", "past habit"], ["I'm used to walking to school.", "accustomed now"], ["I'm getting used to the heat.", "becoming accustomed"]], "Compare the three patterns."),
      order("Put the words in the correct order.", ["She", "used", "to", "be", "very", "shy."], "word", "Subject + used to + be + adjective."),
    ],
  },
  {
    slug: "int-vocab-collocations-social-situations",
    level: "INTERMEDIATE", category: "VOCABULARY", title: "Collocations and Social Situations", topic: "Collocations",
    difficulty: "CORE", minutes: 14, prereq: ["int-vocab-phrasal-verbs-journeys"],
    objective: "Use natural collocations to describe social situations, behaviour and relationships.",
    tags: ["vocabulary", "collocations", "social-situations", "listening-support", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Vocabulary", topic: "Collocations; social situations (Unit 3)" },
    sections: [
      text("**Collocations** are natural word partnerships. Using them makes your English sound **fluent and precise**. Learn them in **chunks**."),
      table("Social collocations", ["Verb + noun", "Adjective + noun", "Example"], [
        ["make friends · make an effort · make a good impression", "close friend · polite conversation · awkward silence", "She made a good impression at the interview."],
        ["keep in touch · keep a secret · keep your promise", "warm welcome · friendly neighbour", "We promised to keep in touch."],
        ["break the ice · break the news · break a promise", "small talk · lasting friendship", "A joke can help to break the ice."],
        ["pay a visit · pay attention · pay a compliment", "nosy neighbour · genuine interest", "He paid her a compliment."],
      ]),
      list("Useful phrases for social situations", ["make small talk", "welcome someone warmly", "feel out of place", "get to know someone"]),
    ],
    exercises: [
      match("Match the verb with the noun.", [["make", "a good impression"], ["keep", "in touch"], ["break", "the ice"], ["pay", "a compliment"]], "These are natural collocations."),
      mc("A joke can help to ___ the ice at a party.", ["break", "make", "keep"], 0, "break the ice = start a friendly conversation."),
      fill("We promised to keep in ___ after the course.", ["touch"], "keep in touch."),
      mist("Find the mistake.", ["She", "did", "a good impression at the interview."], 1, "made", "make a good impression."),
      mc("The silence was ___ : nobody knew what to say.", ["awkward", "delicious", "heavy rain"], 0, "an awkward silence."),
      sa("You ___ friends when you meet new people and become close to them.", ["make"], "make friends.", { hint: "m _ _ e" }),
    ],
  },
  {
    slug: "int-vocab-past-forms-time-expressions",
    level: "INTERMEDIATE", category: "VOCABULARY", title: "Past Forms: Spelling Rules and Time Expressions", topic: "Spelling and time",
    difficulty: "CORE", minutes: 12, prereq: ["int-vocab-collocations-social-situations"],
    objective: "Spell regular past forms correctly and use time expressions to sequence past events.",
    tags: ["vocabulary", "spelling", "past-simple", "time-expressions", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Vocabulary", topic: "Time expressions; -ed spelling (Unit 3)" },
    sections: [
      text("Two skills improve written accuracy: **spelling** regular past forms and using **time expressions** to organise a narrative."),
      table("Spelling of regular past forms", ["Rule", "Examples"], [
        ["+ -ed", "walk → walked · visit → visited"],
        ["ends in -e: + -d", "arrive → arrived · like → liked"],
        ["consonant + y: y → -ied", "study → studied · carry → carried"],
        ["one syllable, one vowel + one consonant: double", "stop → stopped · plan → planned · drop → dropped"],
        ["stressed last syllable: double", "prefer → preferred · admit → admitted (but visit → visited)"],
      ]),
      table("Time expressions", ["Expression", "Example"], [
        ["at first / in the beginning", "At first, I didn't like the city."],
        ["then / after that / afterwards", "Then we went to a café."],
        ["meanwhile", "Meanwhile, my brother was waiting outside."],
        ["eventually / in the end", "Eventually, we found the house."],
        ["by the time", "By the time we arrived, it was dark."],
      ]),
    ],
    exercises: [
      match("Base → past.", [["stop", "stopped"], ["study", "studied"], ["prefer", "preferred"], ["visit", "visited"], ["arrive", "arrived"]], "Follow the spelling rules."),
      fill("She ___ (plan) the trip carefully.", ["planned"], "One syllable, one vowel + one consonant: double n."),
      mist("Find the mistake.", ["He", "admited", "that he was wrong."], 1, "admitted", "Stress on the last syllable: double the t."),
      mc("___, the rain stopped and we could continue our journey.", ["Eventually", "By the way", "Meanwhile it"], 0, "Eventually = after a long time."),
      fill("___ we got to the cinema, the film had started.", ["By the time"], "By the time + Past Simple, Past Perfect."),
      order("Put the words in the correct order.", ["At", "first,", "I", "didn't", "like", "the", "city."], "word", "Time expression + clause."),
    ],
  },
  {
    slug: "int-reading-welcoming-neighbour",
    level: "INTERMEDIATE", category: "READING", title: "Reading: Welcoming a New Neighbour", topic: "Social subtext",
    difficulty: "CORE", minutes: 18, prereq: ["int-reading-language-facts"],
    objective: "Evaluate social subtext: what characters really mean and how they feel beyond the literal words.",
    tags: ["reading", "reading-inference", "subtext", "narrative", "characterisation", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Reading", topic: "Welcome, a social encounter (Unit 3)" },
    sections: [
      text("In narrative, **subtext** is the meaning **beneath the words**. To read it, notice **how** characters speak (tone, questions, interruptions), **what they avoid saying** and **how others react**.", "Reading strategy"),
      passage("Example", "“It's a lovely flat,” said the landlord. “The last tenants didn't stay long.” He didn't look at her as he said it.", "What is not said"),
      list("Guided practice", ["Literal → the flat is lovely.", "Subtext → there is a problem with the flat (last tenants left early).", "Clue → he avoids looking at her."]),
    ],
    exercises: [
      mc("How long had Eva been in the flat when the doorbell rang?", ["two hours", "two days", "two weeks"], 0, "“had only been in the flat for two hours”.", NEIGHBOUR),
      mc("What does Mrs Harding do before Eva can answer?", ["She walks in.", "She goes home.", "She leaves the biscuits outside."], 0, "“walking in before Eva could reply”.", NEIGHBOUR),
      mc("What does Mrs Harding's line “I'm usually alone” suggest?", ["She is lonely.", "She is very busy.", "She is angry."], 0, "It suggests she wants company.", NEIGHBOUR),
      mc("Why does Mrs Harding mention arguments in the old tenant's flat?", ["She likes to gossip.", "She wants to help Eva.", "She dislikes biscuits."], 0, "She gives private information carelessly: gossip.", NEIGHBOUR),
      mc("What does “welcomed or examined” tell us about Eva's feelings?", ["She feels uncomfortable and questioned.", "She feels delighted.", "She feels angry."], 0, "Eva felt observed as well as welcomed.", NEIGHBOUR),
      tf("Eva refuses the biscuits.", false, "“she decided to eat one anyway”.", NEIGHBOUR),
    ],
  },
  {
    slug: "int-writing-thesis-editing",
    level: "INTERMEDIATE", category: "WRITING", title: "Thesis Statements and Self-Editing", topic: "Thesis and editing",
    difficulty: "CHALLENGING", minutes: 18, prereq: ["int-writing-sentence-variety", "int-writing-hook-topic-support"],
    objective: "Write a clear thesis statement and use an editing checklist to correct your own writing.",
    tags: ["writing", "thesis-statement", "editing", "self-correction", "essay", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Writing", topic: "Thesis statements; editing (Unit 3)" },
    sections: [
      text("A **thesis statement** is **one sentence** in your introduction that states the **main point** of the whole essay. A good thesis is **specific**, **arguable** and **tells the reader what to expect**.", "Explanation"),
      table("Weak and strong thesis statements", ["Weak", "Strong"], [
        ["This essay is about technology.", "Although technology has made communication faster, it has also made people less patient, and schools should teach students to use it wisely."],
        ["Many people like travelling.", "Travelling broadens the mind by exposing people to new cultures, but it can also cost more than most people can afford."],
      ]),
      list("Self-editing checklist", ["**Content**: Does every paragraph support the thesis?", "**Organisation**: Topic sentence + support + concluding sentence?", "**Grammar**: tenses, agreement, articles, prepositions.", "**Vocabulary**: repeated words? Use a precise synonym.", "**Mechanics**: spelling, capital letters, punctuation.", "**Read aloud** and read once for each problem type."]),
      tip("Leave your draft for an hour, then read it as if you were someone else.", "Editing tip"),
    ],
    exercises: [
      mc("Which is the strongest thesis statement?", ["I will write about cars.", "Although cars are convenient, public transport is cheaper, cleaner and better for cities.", "Cars are very useful."], 1, "It is specific and arguable, and it tells the reader what to expect."),
      mc("What is a thesis statement?", ["The main point of the whole essay in one sentence", "A list of sources", "The conclusion"], 0, "It states the central argument."),
      mist("Find the mistake (editing).", ["Yesterday I", "have seen", "an interesting film."], 1, "saw", "Definite past time: Past Simple."),
      mist("Find the mistake (editing).", ["Everyone", "have", "their own opinion."], 1, "has", "Everyone takes a singular verb."),
      order("Put the sentences in a logical order for an introduction.", ["Technology has changed the way we communicate.", "Although it makes life easier, it can also create problems.", "This essay will argue that people should use it wisely."], "paragraph", "Hook, balance, thesis."),
      mc("Which is part of a self-editing checklist?", ["Read the text aloud", "Add more adjectives at once", "Delete the conclusion"], 0, "Reading aloud helps to find errors."),
    ],
  },
  {
    slug: "int-writing-essay-1-paragraph-logic",
    level: "INTERMEDIATE", category: "WRITING", title: "Essay 1: Paragraph Logic — Topic Sentences and Cohesive Devices (200 words)", topic: "Essay writing",
    difficulty: "CHALLENGING", minutes: 22, prereq: ["int-writing-thesis-editing", "int-writing-opinion-paragraph", "int-grammar-past-narrative-tenses"],
    objective: "Plan and write a 200-word essay with a thesis, clear topic sentences and cohesive devices, using narrative tenses where needed.",
    tags: ["writing", "essay", "topic-sentence", "cohesion", "assessment-practice", "B1", "B2"],
    ref: { book: HW, level: "Intermediate", area: "Writing", topic: "Essay 1: paragraph logic (Units 1-3)" },
    sections: [
      text("Essay 1 tests **paragraph logic**: each paragraph has a **topic sentence**, **supporting sentences** and a **link** to the next paragraph. Your essay is about **200 words** in **four paragraphs**.", "Explanation"),
      table("Plan for 200 words", ["Paragraph", "Words", "Content"], [
        ["1 Introduction", "40", "hook + background + thesis statement"],
        ["2 Body 1", "60", "topic sentence + evidence / example"],
        ["3 Body 2", "60", "topic sentence + evidence / example"],
        ["4 Conclusion", "40", "restate thesis + final thought"],
      ]),
      table("Cohesive devices", ["Function", "Devices"], [
        ["Adding", "furthermore · in addition · moreover · also"],
        ["Contrast", "however · although · on the other hand · whereas"],
        ["Result", "as a result · therefore · consequently"],
        ["Sequence", "firstly · secondly · finally · in conclusion"],
      ]),
      annotated("Model topic sentences", [
        ["Body 1", "Firstly, life in a big city offers more opportunities for education and work."],
        ["Body 2", "However, living in a city can also be stressful and expensive."],
        ["Conclusion", "In conclusion, although cities offer opportunities, people should think carefully about the price they pay."],
      ]),
      tip("Your topic sentence should tell the reader what the whole paragraph is about. Check that every other sentence supports it.", "Paragraph logic"),
    ],
    exercises: [
      order("Put the paragraph parts in the correct order.", ["Topic sentence", "Supporting reason", "Example", "Concluding sentence"], "paragraph", "Topic sentence first, then support, example, conclusion."),
      mc("Which is the best topic sentence for a paragraph about the benefits of city life?", ["Firstly, life in a big city offers more opportunities for education and work.", "Cities are big.", "I like the city."], 0, "It is specific and controls the whole paragraph."),
      mc("Which cohesive device introduces a contrast?", ["However", "Furthermore", "As a result"], 0, "However = contrast."),
      mist("Find the mistake (cohesion).", ["The city is expensive.", "Furthermore,", "it is cheaper than the village."], 1, "However", "Furthermore adds a similar idea; the second idea contrasts."),
      order("Put the words in the correct order.", ["In", "conclusion,", "cities", "offer", "opportunities", "but", "also", "challenges."], "word", "Linker + subject + verb + object."),
      mc("How many words should Essay 1 have?", ["about 200", "about 50", "about 1,000"], 0, "The assessment asks for about 200 words."),
    ],
  },
];

void [compare, examples, flow, ms, tf, tip, sa, vocab];
