import { HW, annotated, compare, examples, fill, list, match, mc, ms, mist, order, passage, sa, structure, table, text, tf, tip, vocab, type SeedLesson } from "./dsl";

// Pre-Intermediate course, Units 7-9. Topics follow the academy's teaching report; all text is ORIGINAL.

const PICTURES = "THREE PEOPLE, THREE PICTURES\n\nSalim: “My favourite picture is a photo of my grandmother's kitchen. It isn't as modern as my kitchen, but it is much warmer. You can see the old clay pots and my grandmother, who is smiling at the camera. Whenever I look at it, I can almost smell the coffee she was making.”\n\nNoor: “I love a painting of a desert at sunset that hangs in my aunt's house. The colours are amazing: orange, pink and purple. It's the most peaceful picture I have ever seen, and it reminds me of the place where I grew up.”\n\nHamed: “I took my favourite photograph on a mountain in Jabal Akhdar. It's not as sharp as a professional photo, but it is special because it was my first trip alone. I'm standing at the top and the clouds are below me.”";
const STUNT = "Zaina is a stunt performer, and she says her job is not as dangerous as people think. “We are very well prepared,” she explains. “Before every scene, we have to test the equipment, and we must never skip a safety check.”\n\nShe trains five days a week. In the morning she does gymnastics, and in the afternoon she practises falling from heights. “You have to be fit, and you should never stop learning new skills,” she says. On set she always wears protective gear: a helmet, knee and elbow pads, and special boots. “You mustn't take risks that you don't need to take.”\n\nAt the end of a day's filming, Zaina doesn't have to stay long, but she often does. “I like helping the younger performers,” she says. “Anyone can be brave. The clever people are the ones who go home safely.”";
const BUS = "The bus was hot and crowded, and three young children were getting louder and louder. Their aunt, who was reading a magazine, kept saying, “Sit down and be quiet!” but nobody listened.\n\nAn old man in the seat opposite smiled at the children. “Would you like to hear a story?” he asked. They stopped shouting at once. He began: “Once there was a crow who was very thirsty. He found a jug with a little water at the bottom, but his beak was too short to reach it. He thought for a long time. Then he dropped small stones into the jug, one by one, until the water reached the top, and at last he could drink.”\n\n“That's a good story,” said the smallest girl, “but it's not true.” “Isn't it?” said the old man, and he winked. When the bus reached the city, the aunt turned to him. “Thank you,” she said. “I had been trying to calm them for an hour.” The old man only smiled: he had known that clever ideas work better than loud voices.";

export const PRE_INT_U7_U9: SeedLesson[] = [
  // ============================================================ UNIT 7
  {
    slug: "pre-int-grammar-as-as-what-like",
    level: "PRE_INTERMEDIATE", category: "GRAMMAR", title: "as … as, not as … as and What's it like?", topic: "Comparison",
    difficulty: "CORE", minutes: 12, prereq: ["pre-int-grammar-comparatives-superlatives"],
    objective: "Express equality and difference with as … as and not as … as, and ask for descriptions with What's it like?",
    tags: ["grammar", "comparison", "as-as", "descriptions", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Grammar", topic: "as … as; What's it like? (Unit 7)" },
    sections: [
      text("Comparatives show that two things are **different** (bigger than). **As … as** shows that they are **equal**, and **not as … as** shows a **difference**. **What … like?** asks for a **description**.", "Explanation"),
      table("Comparison patterns", ["Pattern", "Meaning", "Example"], [
        ["as + adjective + as", "equal", "My car is as fast as yours."],
        ["not as + adjective + as", "less than", "This café isn't as expensive as that one."],
        ["the same as", "identical", "Your phone is the same as mine."],
        ["different from", "not the same", "This town is different from my town."],
      ]),
      list("What's it like?", ["**What's it like?** asks for a description (not an opinion of like): What's your new flat like? — It's small but comfortable.", "**What does it look like?** asks for appearance: What does she look like? — She's tall with dark hair.", "**Do you like it?** asks for your opinion: Do you like your flat? — Yes, I do."]),
      structure("Structure", "as + adjective + as (not as + comparative)\nWhat + be + subject + like?", "Don't say as bigger as. Say as big as."),
    ],
    exercises: [
      fill("My phone is ___ fast ___ yours. (equal)", ["as", "as"], "as + adjective + as."),
      mist("Find the mistake.", ["This bag is", "as bigger as", "that one."], 1, "as big as", "Use the base adjective: as big as."),
      mc("“___ your new teacher like?” “She's very friendly.”", ["What is", "How is", "Who is"], 0, "What is she like? asks for a description."),
      mc("This café is cheaper than that one. → That café isn't ___ this one.", ["as cheap as", "cheaper than", "as cheaper as"], 0, "That café isn't as cheap as this one."),
      order("Put the words in the correct order.", ["Your", "phone", "is", "the", "same", "as", "mine."], "word", "the same as + noun."),
      match("Which question?", [["Do you like your job?", "your opinion"], ["What's your job like?", "a description"], ["What does your boss look like?", "appearance"]], "Choose the right question."),
    ],
  },
  {
    slug: "pre-int-vocab-synonyms-antonyms",
    level: "PRE_INTERMEDIATE", category: "VOCABULARY", title: "Synonyms and Antonyms", topic: "Adjectives",
    difficulty: "CORE", minutes: 14, prereq: ["pre-int-vocab-word-building-stress"],
    objective: "Use synonyms and antonyms to make your descriptions more precise.",
    tags: ["vocabulary", "synonyms", "antonyms", "adjectives", "describing-people", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Vocabulary", topic: "Synonyms and antonyms (Unit 7)" },
    sections: [
      text("**Synonyms** are words with a **similar meaning**; **antonyms** have an **opposite meaning**. Knowing both lets you avoid repetition and describe things precisely."),
      table("Antonyms", ["Word", "Opposite", "Example"], [
        ["polite", "rude", "He was polite to everyone. She was rude to the waiter."],
        ["cheap", "expensive", "The hotel is cheap; the flight was expensive."],
        ["intelligent", "stupid (strong; say silly / unwise politely)", "She is an intelligent student."],
        ["generous", "mean", "He is very generous with his time."],
        ["honest", "dishonest", "An honest answer."],
        ["polite / possible", "impolite / impossible", "Prefixes im-, in-, un- also make opposites."],
      ]),
      table("Synonyms", ["Word", "Similar words"], [
        ["intelligent", "clever, bright, smart"], ["cheap", "inexpensive, affordable"], ["big", "large, huge"], ["tired", "exhausted, worn out"], ["funny", "amusing, hilarious"],
      ]),
      tip("Be careful with strong words: stupid and mean can sound offensive. Use “not very clever” or “not very generous” in polite conversation.", "Politeness"),
    ],
    exercises: [
      match("Match the antonyms.", [["polite", "rude"], ["cheap", "expensive"], ["generous", "mean"], ["honest", "dishonest"]], "Each pair is opposite in meaning."),
      match("Match the synonyms.", [["intelligent", "clever"], ["tired", "exhausted"], ["big", "huge"], ["funny", "amusing"]], "These words have similar meanings."),
      mc("He always says “please” and “thank you”. He is very ___.", ["polite", "rude", "mean"], 0, "Polite = with good manners."),
      fill("The service was terrible and the waiter was very ___. (opposite of polite)", ["rude"], "The antonym of polite is rude."),
      mc("Which is a polite way to say someone is not clever?", ["stupid", "not very clever", "silly and dull"], 1, "Not very clever is softer."),
      mc("Which sentence is logical?", ["The hotel was expensive, but it was worth every rial.", "The hotel was expensive, so it was very cheap.", "The hotel was cheap, but it cost a fortune."], 0, "The other two sentences contradict themselves: expensive and cheap are antonyms."),
    ],
  },
  {
    slug: "pre-int-reading-favourite-pictures",
    level: "PRE_INTERMEDIATE", category: "READING", title: "Reading: Favourite Pictures", topic: "Opinions and description",
    difficulty: "CORE", minutes: 14, prereq: ["pre-int-reading-vocabulary-context"],
    objective: "Extract opinions and descriptive details from short personal statements.",
    tags: ["reading", "reading-details", "opinion", "descriptive-vocabulary", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Reading", topic: "Favourite pictures (Unit 7)" },
    sections: [
      text("When several people describe the **same kind of thing**, keep track of **who says what**. Underline **opinion words** (favourite, special, amazing, peaceful) and **descriptive words** (colours, sizes, feelings).", "Reading strategy"),
      passage("Example", "Ahmad: “My favourite picture is a photo of the sea. It's very calm and blue.” Mariam: “I prefer a painting of a market. It's busy and colourful.”", "Two opinions"),
      list("Guided practice", ["Ahmad: sea photo → calm and blue.", "Mariam: market painting → busy and colourful.", "Opinion words: favourite, prefer, calm, colourful."]),
    ],
    exercises: [
      mc("What is Salim's favourite picture?", ["a photo of his grandmother's kitchen", "a painting of a desert", "a photo from a mountain"], 0, "“My favourite picture is a photo of my grandmother's kitchen.”", PICTURES),
      mc("What colours does Noor mention?", ["orange, pink and purple", "red, blue and green", "black and white"], 0, "“orange, pink and purple”.", PICTURES),
      mc("Why is Hamed's photograph special?", ["It was his first trip alone.", "It is very sharp.", "It was taken by a professional."], 0, "“it is special because it was my first trip alone.”", PICTURES),
      tf("Salim says his grandmother's kitchen is more modern than his own.", false, "“It isn't as modern as my kitchen.”", PICTURES),
      mc("Which word describes Noor's painting?", ["peaceful", "noisy", "crowded"], 0, "“It's the most peaceful picture I have ever seen.”", PICTURES),
      mc("Who talks about a place where they grew up?", ["Salim", "Noor", "Hamed"], 1, "Noor: “it reminds me of the place where I grew up.”", PICTURES),
    ],
  },
  {
    slug: "pre-int-writing-comparison-paragraph",
    level: "PRE_INTERMEDIATE", category: "WRITING", title: "Comparison and Contrast Paragraphs", topic: "Comparison writing",
    difficulty: "CORE", minutes: 18, prereq: ["pre-int-writing-chronological-biography", "pre-int-grammar-as-as-what-like"],
    objective: "Write a comparison / contrast paragraph and join descriptive clauses with who, which, that and where.",
    tags: ["writing", "writing-paragraph", "comparison", "relative-clauses", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Writing", topic: "Comparing and describing (Unit 7)" },
    sections: [
      text("A **comparison paragraph** shows how two things are **similar** and **different**. It needs a **topic sentence**, **points of comparison**, and **linking language**. **Relative pronouns** let you add descriptions smoothly.", "Explanation"),
      table("Language for comparing", ["Job", "Language", "Example"], [
        ["Similarity", "both · similarly · also · as … as", "Both cities are near the sea."],
        ["Difference", "however · whereas · while · but · not as … as", "Muscat is busy, whereas Sur is quiet."],
        ["Add information", "who (people) · which / that (things) · where (places)", "Sur is a town where people build traditional boats."],
      ]),
      annotated("Model paragraph", [
        ["Topic sentence", "Muscat and Sur are both coastal cities, but they are very different."],
        ["Similarities", "Both cities have beautiful beaches, and both are places where visitors can enjoy fresh seafood."],
        ["Differences", "Muscat is the capital, which makes it busier and more modern, whereas Sur is a small, quiet town which is famous for its boats."],
        ["Conclusion", "In short, Muscat offers more excitement, while Sur is not as crowded and feels more traditional."],
      ]),
    ],
    exercises: [
      order("Put the sentences in order to make a paragraph.", ["Muscat and Sur are both coastal cities, but they are very different.", "Both cities have beautiful beaches.", "Muscat is busy, whereas Sur is quiet.", "In short, Muscat is more exciting, while Sur is more traditional."], "paragraph", "Topic sentence, similarities, differences, conclusion."),
      fill("Sur is a town ___ people build traditional boats.", ["where"], "where for places."),
      fill("I have a friend ___ speaks four languages.", ["who"], "who for people."),
      mist("Find the mistake.", ["Muscat is busy,", "however", "Sur is quiet."], 1, "whereas", "However can't join two clauses with a comma. Use whereas or a full stop."),
      order("Put the words in the correct order.", ["Sur", "isn't", "as", "crowded", "as", "Muscat."], "word", "not as + adjective + as."),
      match("Similarity or difference?", [["Both cities have beaches.", "similarity"], ["Muscat is busy, whereas Sur is quiet.", "difference"], ["Sur is not as crowded as Muscat.", "difference"], ["They are also both near the sea.", "similarity"]], "Both, also = similarity; whereas, not as … as = difference."),
    ],
  },

  // ============================================================ UNIT 8
  {
    slug: "pre-int-grammar-have-to",
    level: "PRE_INTERMEDIATE", category: "GRAMMAR", title: "have to and don't have to", topic: "Obligation",
    difficulty: "CORE", minutes: 12, prereq: ["pre-int-grammar-as-as-what-like"],
    objective: "Express external obligation with have to and the lack of obligation with don't have to.",
    tags: ["grammar", "obligation", "have-to", "modal-verbs", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Grammar", topic: "have to / don't have to (Unit 8)" },
    sections: [
      text("**Have to** expresses **obligation** that comes from **outside** (rules, laws, a boss). **Don't have to** means there is **no obligation**: it is **not necessary**, but it is allowed.", "Explanation"),
      table("have to", ["Type", "Form", "Example"], [
        ["Positive", "have / has to + base verb", "I have to wear a uniform at work."],
        ["Negative", "don't / doesn't have to + base verb", "You don't have to pay: it's free."],
        ["Question", "Do / Does + subject + have to + verb?", "Do you have to work on Sundays?"],
        ["Past", "had to / didn't have to", "I had to wait for an hour."],
      ]),
      structure("Structure", "subject + have to / has to + verb\nsubject + don't / doesn't have to + verb", "Don't have to is NOT the same as mustn't: You don't have to come (it isn't necessary). You mustn't come (it is forbidden)."),
      examples("Examples", { Obligation: ["Pilots have to pass a medical test.", "We have to be at the airport by six."], "No obligation": ["You don't have to book: just come!", "She doesn't have to work on Fridays."] }),
    ],
    exercises: [
      mc("In this school, students ___ wear a uniform. It's a rule.", ["have to", "don't have to", "mustn't to"], 0, "A school rule = external obligation: have to."),
      mc("You ___ bring food. We have plenty. (it isn't necessary)", ["have to", "don't have to", "must"], 1, "It isn't necessary: don't have to."),
      mist("Find the mistake.", ["She", "have to", "work on Sundays."], 1, "has to", "With she: has to."),
      fill("___ you have to wear a tie at your office?", ["Do"], "Questions: Do + subject + have to."),
      match("have to, don't have to, or mustn't?", [["It's necessary.", "have to"], ["It isn't necessary.", "don't have to"], ["It is forbidden.", "mustn't"]], "Learn the three meanings."),
      order("Put the words in the correct order.", ["You", "don't", "have", "to", "pay", "for", "the", "tickets."], "word", "Subject + don't have to + verb + object."),
    ],
  },
  {
    slug: "pre-int-grammar-should-must",
    level: "PRE_INTERMEDIATE", category: "GRAMMAR", title: "should, must and can for Advice, Duty and Permission", topic: "Modal verbs",
    difficulty: "CORE", minutes: 14, prereq: ["pre-int-grammar-have-to"],
    objective: "Use should for advice, must for strong obligation and can / can't for permission and ability.",
    tags: ["grammar", "modal-verbs", "should", "must", "can", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Grammar", topic: "should / must / can (Unit 8)" },
    sections: [
      text("**Modal verbs** express attitudes: advice, duty, permission and ability. They are followed by the **base verb** and never change form.", "Explanation"),
      table("Modal verbs", ["Modal", "Meaning", "Example"], [
        ["should / shouldn't", "advice (a good idea)", "You should see a doctor. You shouldn't stay up late."],
        ["must", "strong obligation (a personal rule or a strong belief)", "I must finish this report today."],
        ["mustn't", "prohibition (forbidden)", "You mustn't use your phone in the exam."],
        ["can / can't", "permission or ability", "You can park here. I can't swim."],
      ]),
      structure("Structure", "should / must / can + base verb\nQuestion: Should I …? Can I …? Must I …?", "Must has no past form: use had to. Mustn't ≠ don't have to."),
      list("Polite permission", ["Can I open the window? (informal)", "Could I borrow your pen? (polite)", "May I come in? (formal)"]),
    ],
    exercises: [
      mc("You look ill. You ___ see a doctor.", ["should", "can't", "mustn't"], 0, "Advice: should."),
      mc("You ___ smoke in the hospital. It's forbidden.", ["mustn't", "shouldn't", "don't have to"], 0, "Forbidden: mustn't."),
      mist("Find the mistake.", ["You", "should to", "drink more water."], 1, "should", "No to after a modal."),
      fill("You ___ park here. It's allowed. (permission)", ["can"], "Permission: can."),
      match("Which meaning?", [["You should exercise more.", "advice"], ["You mustn't touch the paintings.", "prohibition"], ["I must call my mother tonight.", "strong personal duty"]], "Match the modal with its meaning."),
      order("Put the words in the correct order.", ["You", "shouldn't", "eat", "too", "much", "sugar."], "word", "Subject + shouldn't + verb + object."),
    ],
  },
  {
    slug: "pre-int-vocab-body-protective-gear",
    level: "PRE_INTERMEDIATE", category: "VOCABULARY", title: "Parts of the Body and Protective Gear", topic: "The body",
    difficulty: "CORE", minutes: 14, prereq: ["pre-int-vocab-synonyms-antonyms"],
    objective: "Name parts of the body and the clothes and equipment that protect them.",
    tags: ["vocabulary", "body", "safety", "clothes", "listening-support", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Vocabulary", topic: "Parts of the body and protective clothing (Unit 8)" },
    sections: [
      text("People in dangerous jobs and sports **protect their bodies** with special equipment. Each piece of gear protects a **specific part of the body**."),
      table("Body part → protective gear", ["Body part", "Protective gear"], [
        ["head", "helmet"], ["eyes", "goggles"], ["hands", "gloves"], ["elbows and knees", "elbow pads and knee pads"], ["feet", "boots"], ["whole body", "protective suit"],
      ]),
      vocab([
        { word: "helmet", pos: "noun", meaning: "a hard hat that protects your head", ar: "خوذة", pron: "/ˈhelmɪt/", ex: "Always wear a helmet when you ride a bike.", col: ["wear a helmet"], visual: "⛑️" },
        { word: "goggles", pos: "noun (plural)", meaning: "tight glasses that protect your eyes", ar: "نظارات واقية", pron: "/ˈɡɒɡlz/", ex: "Swimmers wear goggles to protect their eyes.", col: ["a pair of goggles"], visual: "🥽" },
        { word: "gloves", pos: "noun (plural)", meaning: "covers for your hands", ar: "قفازات", pron: "/ɡlʌvz/", ex: "He wore thick gloves to hold the hot pan.", col: ["a pair of gloves"], visual: "🧤" },
        { word: "boots", pos: "noun (plural)", meaning: "strong shoes that cover the ankle", ar: "حذاء ثقيل", pron: "/buːts/", ex: "Climbers wear strong boots.", col: ["safety boots"], visual: "🥾" },
        { word: "elbow / knee", pos: "noun", meaning: "the joints in the middle of your arm and leg", ar: "مرفق / ركبة", pron: "/ˈelbəʊ/ · /niː/", ex: "She hurt her knee when she fell.", col: ["knee pads", "elbow pads"], visual: "🦵" },
      ], "Protective gear"),
    ],
    exercises: [
      match("Which part of the body does it protect?", [["helmet", "head"], ["goggles", "eyes"], ["gloves", "hands"], ["boots", "feet"], ["knee pads", "knees"]], "Each piece of gear protects a body part."),
      mc("A cyclist should always wear a ___.", ["helmet", "goggles", "suit"], 0, "A helmet protects the head."),
      mc("Swimmers wear ___ to protect their eyes from the water.", ["goggles", "gloves", "boots"], 0, "Goggles protect the eyes."),
      fill("She fell and hurt her ___. (the joint in the middle of the leg)", ["knee"], "Knee is the joint in the middle of the leg."),
      mist("Find the mistake.", ["Climbers wear", "a pair of boot", "on the mountain."], 1, "a pair of boots", "Boots is plural."),
      sa("You wear ___ on your hands to keep them warm or safe.", ["gloves"], "Gloves cover the hands.", { hint: "g _ _ _ _ s" }),
    ],
  },
  {
    slug: "pre-int-reading-stunt-performer",
    level: "PRE_INTERMEDIATE", category: "READING", title: "Reading: A Day with a Stunt Performer", topic: "Profiles",
    difficulty: "CORE", minutes: 16, prereq: ["pre-int-reading-favourite-pictures"],
    objective: "Understand a profile that uses modal verbs for rules and advice, and identify the writer's key points.",
    tags: ["reading", "reading-details", "reading-main-idea", "modal-verbs", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Reading", topic: "Stunt professionals (Unit 8)" },
    sections: [
      text("Texts about **dangerous jobs** talk about **rules and safety**. Notice the modal verbs: **must / have to** (duty), **should** (advice), **mustn't** (forbidden). They tell you the **attitude** of the speaker.", "Reading strategy"),
      passage("Example", "Firefighters have to train every week. They must check their equipment before every shift, and they should always work in a team.", "Modals in a text"),
      list("Guided practice", ["What is a duty? → check equipment before every shift (must).", "What is advice? → always work in a team (should).", "What is required by rule? → train every week (have to)."]),
    ],
    exercises: [
      mc("How many days a week does Zaina train?", ["three", "five", "seven"], 1, "“She trains five days a week.”", STUNT),
      mc("What do the performers have to do before every scene?", ["test the equipment", "call a friend", "eat lunch"], 0, "“Before every scene, we have to test the equipment.”", STUNT),
      mc("Which protective gear does the text mention?", ["a helmet, knee and elbow pads, and boots", "only goggles", "gloves and a coat"], 0, "“a helmet, knee and elbow pads, and special boots”.", STUNT),
      mc("What does “You mustn't take risks that you don't need to take” mean?", ["It is forbidden to take unnecessary risks.", "You don't have to take risks.", "You should take more risks."], 0, "Mustn't = prohibition.", STUNT),
      tf("Zaina thinks her job is more dangerous than people believe.", false, "“her job is not as dangerous as people think.”", STUNT),
      mc("According to Zaina, who are the clever ones?", ["the people who go home safely", "the people who take the most risks", "the youngest performers"], 0, "“The clever people are the ones who go home safely.”", STUNT),
    ],
  },
  {
    slug: "pre-int-writing-formal-informal-register",
    level: "PRE_INTERMEDIATE", category: "WRITING", title: "Formal and Informal Register: Emails and Notes", topic: "Register",
    difficulty: "CORE", minutes: 18, prereq: ["pre-int-writing-comparison-paragraph"],
    objective: "Write a formal email and an informal note in the correct register and layout.",
    tags: ["writing", "register", "formal-writing", "email", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Writing", topic: "Formal and informal writing (Unit 8)" },
    sections: [
      text("**Register** is the level of formality of your writing. You choose it by looking at **who you are writing to** and **why**. A formal email and an informal note about the same topic look very different.", "Explanation"),
      table("Formal and informal features", ["Feature", "Formal email", "Informal note"], [
        ["Greeting", "Dear Mr Hassan, / Dear Sir or Madam,", "Hi Sami, / Hello Sami,"],
        ["Opening", "I am writing to ask about…", "Just a quick note to say…"],
        ["Verb forms", "full forms: I would like, I cannot", "short forms: I'd like, I can't"],
        ["Vocabulary", "purchase, request, assist", "buy, ask for, help"],
        ["Closing", "I look forward to hearing from you. Yours sincerely,", "See you soon! / Speak soon, / Cheers,"],
      ]),
      annotated("Same message, two registers", [
        ["Formal", "Dear Ms Farsi, I am writing to request a copy of my exam results. I would be grateful if you could send them to me by email. I look forward to hearing from you. Yours sincerely, Omar Al Lawati"],
        ["Informal", "Hi Nora, just a quick note: can you send me the exam results by email? Thanks a lot! Speak soon, Omar"],
      ]),
      tip("Stay consistent: do not mix “Dear Sir or Madam” with slang like “cheers”.", "Consistency"),
    ],
    exercises: [
      match("Formal or informal?", [["Dear Sir or Madam,", "formal"], ["Hi Sami,", "informal"], ["I would be grateful if you could…", "formal"], ["Cheers,", "informal"], ["I look forward to hearing from you.", "formal"]], "Learn the typical phrases."),
      mc("You write to your bank manager. Which opening is best?", ["I am writing to enquire about a loan.", "Just a quick note about a loan!", "Hey, about the loan."], 0, "A formal opening."),
      mist("Find the mistake. (formal email)", ["Dear Mr Hassan,", "I can't attend the meeting.", "Yours sincerely, Nora"], 1, "I cannot attend the meeting.", "Formal writing avoids short forms."),
      order("Put the parts of the formal email in order.", ["Dear Ms Farsi,", "I am writing to request a copy of my exam results.", "I look forward to hearing from you.", "Yours sincerely, Omar"], "paragraph", "Greeting, purpose, closing line, sign-off."),
      fill("I would be ___ if you could send me the details. (thankful)", ["grateful"], "I would be grateful if you could… is a formal request."),
      mc("Which closing suits an informal note to a friend?", ["Yours faithfully,", "Speak soon,", "With kind regards,"], 1, "Speak soon is informal."),
    ],
  },

  // ============================================================ UNIT 9
  {
    slug: "pre-int-grammar-past-perfect",
    level: "PRE_INTERMEDIATE", category: "GRAMMAR", title: "Past Perfect Simple", topic: "Past Perfect",
    difficulty: "CORE", minutes: 14, prereq: ["pre-int-grammar-should-must"],
    objective: "Use the Past Perfect (had + past participle) for an action that happened before another past action.",
    tags: ["grammar", "past-perfect", "tenses", "narrative", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Grammar", topic: "Past Perfect Simple (Unit 9)" },
    sections: [
      text("The **Past Perfect** shows an action that happened **before another past action**. It gives the **earlier past** and makes the **sequence** of events clear.", "Explanation"),
      table("Forms", ["Type", "Form", "Example"], [
        ["Positive", "had + past participle", "When I arrived, the film had started."],
        ["Negative", "hadn't + past participle", "I hadn't eaten, so I was hungry."],
        ["Question", "Had + subject + past participle?", "Had you seen the film before?"],
      ]),
      list("When do we use it?", ["To show which past action happened first: When we got to the station, the train had left.", "To explain the reason for a past situation: She was tired because she hadn't slept.", "With already, just, never, before, by the time."]),
      structure("Structure", "Past Perfect (earlier) → Past Simple (later)\nWhen I got home, my brother had already cooked dinner.", "If the order is clear (first … then), you can use the Past Simple for both: I opened the door and went in."),
    ],
    exercises: [
      mc("When we arrived at the cinema, the film ___.", ["started", "had started", "was starting"], 1, "The film started before we arrived: Past Perfect."),
      fill("I was hungry because I ___ (not / eat) all day.", ["hadn't eaten"], "Earlier reason: hadn't eaten."),
      mist("Find the mistake.", ["When I called her,", "she already left", "the office."], 1, "had already left", "Earlier past: had already left."),
      match("Which happened first?", [["When I got to the station, the train had left.", "the train left"], ["After she had finished, she went out.", "she finished"], ["I saw him after he had left.", "he left"]], "The Past Perfect action happened first."),
      order("Put the words in the correct order.", ["She", "had", "already", "left", "when", "I", "arrived."], "word", "Past Perfect + when + Past Simple."),
      sa("Complete: By the time we arrived, they ___ (finish) dinner.", ["had finished"], "Earlier action: had finished.", { hint: "had + participle" }),
    ],
  },
  {
    slug: "pre-int-grammar-narrative-tenses-conjunctions",
    level: "PRE_INTERMEDIATE", category: "GRAMMAR", title: "Narrative Tenses and Time Conjunctions", topic: "Narrative tenses",
    difficulty: "CORE", minutes: 16, prereq: ["pre-int-grammar-past-perfect"],
    objective: "Combine Past Simple, Past Continuous and Past Perfect in a story and link ideas with time, cause, result and contrast conjunctions.",
    tags: ["grammar", "narrative", "past-tenses", "conjunctions", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Grammar", topic: "Narrative tenses; conjunctions (Unit 9)" },
    sections: [
      text("A good story uses **three past tenses together**. Each one has a job. **Conjunctions** connect the events and show their **time, cause, result and contrast**.", "Explanation"),
      table("Three tenses in a story", ["Tense", "Job", "Example"], [
        ["Past Simple", "main events", "She opened the door and saw a stranger."],
        ["Past Continuous", "background / interrupted actions", "It was raining and the wind was blowing."],
        ["Past Perfect", "events before the story", "He had lost his keys earlier that day."],
      ]),
      table("Conjunctions", ["Type", "Words", "Example"], [
        ["Time", "as soon as · when · while · until · after · before", "As soon as she arrived, it started to rain."],
        ["Cause", "because", "He was late because the bus had broken down."],
        ["Result", "so", "It was late, so we went home."],
        ["Contrast", "although · however", "Although it was cold, they swam. It was cold; however, they swam."],
      ]),
      annotated("Model paragraph", [
        ["Background", "It was a stormy night and the wind was blowing hard."],
        ["Earlier event", "Karim had missed the last bus, so he was walking home."],
        ["Main events", "As soon as he turned the corner, he saw a light. Although he was frightened, he walked towards it."],
        ["Ending", "It was a small café which had just opened, and he stayed there until the storm ended."],
      ]),
    ],
    exercises: [
      mc("It was raining hard when I ___ home.", ["left", "leaving", "had left"], 0, "A main event: Past Simple."),
      fill("Although it ___ (be) cold, they went swimming.", ["was"], "Past Simple of be after although."),
      fill("She was crying because she ___ (lose) her phone.", ["had lost"], "The earlier reason: had lost."),
      mc("___ he had finished his homework, he went out. (after)", ["After", "Until", "Although"], 0, "After = later than."),
      mist("Find the mistake.", ["We waited", "when", "the rain stopped."], 1, "until", "Waited until the rain stopped."),
      order("Put the words in the correct order.", ["As", "soon", "as", "I", "arrived,", "it", "started", "to", "rain."], "word", "As soon as + clause, main clause."),
    ],
  },
  {
    slug: "pre-int-vocab-feelings-adjectives",
    level: "PRE_INTERMEDIATE", category: "VOCABULARY", title: "Adjectives for Feelings: heartbroken, homesick, furious …", topic: "Feelings",
    difficulty: "CORE", minutes: 12, prereq: ["pre-int-vocab-body-protective-gear"],
    objective: "Use precise adjectives to describe physical and emotional states.",
    tags: ["vocabulary", "feelings", "adjectives", "emotions", "listening-support", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Vocabulary", topic: "Adjectives of feeling (Unit 9)" },
    sections: [
      text("Instead of always saying **happy, sad or angry**, use **more precise adjectives**. They make stories and descriptions more powerful."),
      table("Stronger and more precise", ["Basic", "More precise", "Meaning"], [
        ["sad", "heartbroken · homesick · disappointed", "very sad after a loss · missing home · sad because something wasn't as good as hoped"],
        ["afraid", "nervous", "a little afraid before something important"],
        ["happy", "delighted", "very pleased"],
        ["angry", "furious", "extremely angry"],
      ]),
      vocab([
        { word: "homesick", pos: "adjective", meaning: "sad because you are away from home", ar: "مشتاق للوطن", pron: "/ˈhəʊmsɪk/", ex: "During his first month abroad, he felt very homesick.", col: ["feel homesick"], visual: "🏠" },
        { word: "disappointed", pos: "adjective", meaning: "sad because something was not as good as you hoped", ar: "مُحبَط", pron: "/ˌdɪsəˈpɔɪntɪd/", ex: "I was disappointed with the results.", col: ["disappointed with / about"], visual: "😞" },
        { word: "nervous", pos: "adjective", meaning: "worried before something important", ar: "متوتر", pron: "/ˈnɜːvəs/", ex: "She felt nervous before the interview.", col: ["nervous about"], visual: "😬" },
        { word: "delighted", pos: "adjective", meaning: "very happy and pleased", ar: "مسرور جدًا", pron: "/dɪˈlaɪtɪd/", ex: "We were delighted to hear the news.", col: ["delighted to hear / with"], visual: "😄" },
        { word: "furious", pos: "adjective", meaning: "extremely angry", ar: "غاضب جدًا", pron: "/ˈfjʊəriəs/", ex: "He was furious when he saw the broken window.", col: ["furious with someone"], visual: "😡" },
        { word: "heartbroken", pos: "adjective", meaning: "extremely sad, especially after losing someone or something", ar: "منكسر القلب", pron: "/ˈhɑːtbrəʊkən/", ex: "She was heartbroken when her cat died.", col: ["feel heartbroken"], visual: "💔" },
      ], "Feelings"),
    ],
    exercises: [
      match("Match the feeling with the situation.", [["furious", "extremely angry"], ["homesick", "missing home"], ["delighted", "very happy"], ["nervous", "worried before an interview"]], "Each word describes a different emotion."),
      mc("She was ___ when she lost her job. She cried for days.", ["heartbroken", "delighted", "nervous"], 0, "Heartbroken = extremely sad."),
      mc("He was ___ when the waiter dropped soup on his suit.", ["furious", "homesick", "delighted"], 0, "Furious = extremely angry."),
      mist("Find the mistake.", ["I was", "delighted with", "the bad news."], 1, "upset about", "Delighted doesn't fit bad news."),
      fill("I felt ___ before my exam. My hands were shaking.", ["nervous"], "Nervous = worried before something important."),
      sa("You are sad because you miss your home: you are ___.", ["homesick"], "Homesick = sad because you are away from home.", { hint: "h _ _ _ _ _ _ k" }),
    ],
  },
  {
    slug: "pre-int-reading-bus-story",
    level: "PRE_INTERMEDIATE", category: "READING", title: "Reading: The Storyteller on the Bus", topic: "Literary reading",
    difficulty: "CORE", minutes: 18, prereq: ["pre-int-reading-stunt-performer"],
    objective: "Understand a short story, evaluate its message and analyse a character.",
    tags: ["reading", "reading-inference", "narrative", "character", "moral", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Reading", topic: "A short literary story (Unit 9)" },
    sections: [
      text("In a literary story you need to read **between the lines**. Ask about **the characters** (what they say and do), **the message** (moral) and **the tone** (funny, serious, gentle). What a character **does** often shows more than what the writer **tells** us.", "Reading strategy"),
      passage("Example", "Ali never said a word during the meeting, but he wrote every idea on the board and put a cup of coffee on each desk.", "A character in action"),
      list("Guided practice", ["Actions: writes ideas down, brings coffee.", "Character: quiet, helpful and thoughtful.", "Tone: gentle and positive."]),
    ],
    exercises: [
      mc("Why did the children stop shouting?", ["The old man offered to tell them a story.", "Their aunt shouted at them.", "The bus stopped."], 0, "“Would you like to hear a story?” … “They stopped shouting at once.”", BUS),
      mc("In the old man's story, why couldn't the crow reach the water?", ["The jug was too far away.", "His beak was too short.", "The water was too hot."], 1, "“his beak was too short to reach it.”", BUS),
      mc("How did the crow finally get a drink?", ["He dropped small stones into the jug.", "He asked for help.", "He broke the jug."], 0, "He dropped small stones until the water reached the top.", BUS),
      mc("What is the message of the story?", ["Clever ideas work better than loud voices.", "Children must be quiet.", "Buses are crowded."], 0, "The last sentence says so.", BUS),
      mc("Which word best describes the old man?", ["clever and gentle", "angry and rude", "nervous and shy"], 0, "He calms the children with a clever story and a kind manner.", BUS),
      tf("The aunt had been trying to calm the children for an hour.", true, "“I had been trying to calm them for an hour.”", BUS),
    ],
  },
  {
    slug: "pre-int-writing-book-film-review",
    level: "PRE_INTERMEDIATE", category: "WRITING", title: "Writing a Book or Film Review", topic: "Review writing",
    difficulty: "CORE", minutes: 18, prereq: ["pre-int-writing-formal-informal-register", "pre-int-grammar-narrative-tenses-conjunctions"],
    objective: "Write a review with a plot summary, an evaluation and a recommendation, using conjunctions to build complex sentences.",
    tags: ["writing", "writing-paragraph", "review", "conjunctions", "word-order", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Writing", topic: "Book / film review (Unit 9)" },
    sections: [
      text("A **review** tells the reader **what a book or film is about** and **what you think of it**. It has four parts, and the **plot summary is written in the Present Simple**.", "Explanation"),
      table("Parts of a review", ["Part", "Content", "Example"], [
        ["Introduction", "title, type, writer or director", "“The Silent Garden” is a mystery novel by Layla Al Harthy."],
        ["Plot summary (Present Simple)", "main events, no spoilers", "A young girl finds a key in her grandmother's garden and follows a trail of clues."],
        ["Evaluation", "what you liked or disliked, and why", "Although the story is slow at first, the characters are very believable."],
        ["Recommendation", "who will enjoy it", "I would recommend it to anyone who likes mysteries."],
      ]),
      annotated("Model review", [
        ["Introduction", "“The Silent Garden” is a mystery novel by Layla Al Harthy."],
        ["Plot", "A young girl finds a key in her grandmother's garden. She follows a trail of clues until she discovers a family secret."],
        ["Evaluation", "Although the beginning is slow, the ending is exciting because every clue finally makes sense."],
        ["Recommendation", "I would recommend it to anyone who enjoys a good mystery."],
      ]),
      tip("Do not tell the ending: readers don't want spoilers.", "No spoilers"),
    ],
    exercises: [
      order("Put the sentences in the correct order.", ["“The Silent Garden” is a mystery novel.", "A young girl finds a key in her grandmother's garden.", "Although the beginning is slow, the ending is exciting.", "I would recommend it to anyone who enjoys mysteries."], "paragraph", "Introduction, plot, evaluation, recommendation."),
      order("Put the words in the correct order.", ["Although", "the", "beginning", "is", "slow,", "the", "ending", "is", "exciting."], "word", "Although + clause, main clause."),
      order("Put the words in the correct order.", ["The", "film", "is", "about", "a", "boy", "who", "wants", "to", "become", "a", "pilot."], "word", "Main clause + who + verb."),
      mc("In which tense do we write the plot summary?", ["Present Simple", "Past Perfect", "Future"], 0, "Plot summaries use the Present Simple."),
      mist("Find the mistake.", ["A girl finds a key.", "She followed", "clues to a secret."], 1, "follows", "Keep the Present Simple in a plot summary."),
      mc("Which sentence is the RECOMMENDATION?", ["I would recommend it to anyone who likes mysteries.", "The story is set in Muscat.", "The author was born in 1980."], 0, "It says who will enjoy it."),
    ],
  },
];

void [compare, examples, ms, tf, tip, passage, sa, annotated];
