import { HW, annotated, compare, examples, fill, list, match, mc, ms, mist, order, passage, sa, structure, table, text, tf, tip, vocab, type SeedLesson } from "./dsl";

// Pre-Intermediate course, Units 10-12. Topics follow the academy's teaching report; all text is ORIGINAL
// (the clubs, brands and people below are imaginary).

const FAMOUS_NAMES = "TWO IMAGINARY SUCCESS STORIES\n\nSalalah Stars\nSalalah Stars football club was founded in 1965 by a group of schoolteachers. The first matches were played on a sandy field near the sea. In 1982 a new stadium was built, and the first national trophy was won two years later. Since then, the club has been supported by fans all over the region, and more than fifty thousand shirts are sold every year. Next season, a museum will be opened next to the stadium.\n\nDhofar Gold\nDhofar Gold is a perfume brand. It was created in 1990 in a small workshop, and it is made from frankincense. At first it was sold only in local markets, but in 2005 it was exported to Europe. Today it is bought by customers in more than twenty countries, and a new range will be launched next year.";
const COLLECTORS = "THREE COLLECTORS (imaginary profiles)\n\nMaryam has been collecting stamps since she was nine. She now owns more than 12,000 stamps from 90 countries, and she spends every Friday sorting them into albums.\n\nAli has collected teapots for twenty years. He has 300 teapots, and he has been looking for a golden teapot for ten years. “I haven't found it yet,” he says, “but I haven't given up.”\n\nSami has been building model cars since he retired. He has finished 45 models this year, and he has been working on a big racing car for three weeks. “It's difficult,” he says, “but I've never been bored.”";
const CHANCE = "Every day we make decisions without knowing what will happen. Will it rain? Will the bus be late? Some risks are small, but others are more serious.\n\nScientists say that people are often bad at judging risk. We worry about unusual events, such as a plane crash, but we forget everyday dangers, such as crossing a busy road. Chance also plays tricks on us. If you toss a coin ten times, you might get heads seven times, and that isn't strange at all. In the same way, if twenty-three people are in a room, there is a good chance that two of them share a birthday, even though it seems unlikely.\n\nIf we understand chance better, we will make better decisions.";

export const PRE_INT_U10_U12: SeedLesson[] = [
  // ============================================================ UNIT 10
  {
    slug: "pre-int-grammar-passive-simple",
    level: "PRE_INTERMEDIATE", category: "GRAMMAR", title: "The Passive: Present Simple and Past Simple", topic: "Passive voice",
    difficulty: "CORE", minutes: 14, prereq: ["pre-int-grammar-narrative-tenses-conjunctions"],
    objective: "Form and use the passive in the Present Simple and Past Simple, and add the agent with by.",
    tags: ["grammar", "passive-voice", "present-simple", "past-simple", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Grammar", topic: "Passive voice (Unit 10)" },
    sections: [
      text("In an **active** sentence the **subject does** the action. In a **passive** sentence the **object of the action becomes the subject**. We use the passive when the **action or result** is more important than **who did it**, or when we **don't know** who did it.", "Explanation"),
      table("Active and passive", ["Tense", "Active", "Passive"], [
        ["Present Simple", "They make cars in Japan.", "Cars are made in Japan."],
        ["Past Simple", "Someone stole my bike.", "My bike was stolen."],
        ["With the agent", "Picasso painted this picture.", "This picture was painted by Picasso."],
      ]),
      structure("Structure", "Present: subject + am / is / are + past participle\nPast: subject + was / were + past participle\n(+ by + agent, only when it is important)", "The verb be agrees with the new subject: The window was broken. The windows were broken."),
      list("When do we use the passive?", ["The doer is unknown: My phone was stolen.", "The doer is obvious or unimportant: English is spoken in many countries.", "We want to focus on the object or the result: The bridge was built in 1990."]),
    ],
    exercises: [
      mc("English ___ in many countries.", ["speaks", "is spoken", "was speaking"], 1, "Present Simple passive: is spoken."),
      fill("This novel ___ (write) by an Omani author in 2010.", ["was written"], "Past Simple passive: was written."),
      mist("Find the mistake.", ["The letters", "was sent", "yesterday."], 1, "were sent", "Letters is plural: were sent."),
      sa("Rewrite in the passive: Someone stole my car. → My car ___.", ["was stolen"], "Past Simple passive: was stolen.", { hint: "was + participle" }),
      order("Put the words in the correct order.", ["This", "picture", "was", "painted", "by", "Picasso."], "word", "Subject + was + participle + by + agent."),
      match("Active → passive.", [["They make cars in Japan.", "Cars are made in Japan."], ["Someone broke the window.", "The window was broken."], ["Shakespeare wrote Hamlet.", "Hamlet was written by Shakespeare."]], "The object becomes the subject."),
    ],
  },
  {
    slug: "pre-int-grammar-passive-perfect-will",
    level: "PRE_INTERMEDIATE", category: "GRAMMAR", title: "The Passive: Present Perfect and will; Active or Passive?", topic: "Passive voice",
    difficulty: "CORE", minutes: 14, prereq: ["pre-int-grammar-passive-simple"],
    objective: "Form the passive with the Present Perfect and will, and choose between active and passive.",
    tags: ["grammar", "passive-voice", "present-perfect", "will", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Grammar", topic: "Passive: Present Perfect and future (Unit 10)" },
    sections: [
      text("The passive can be used in **other tenses** too. We change the auxiliary and keep the **past participle**. Choosing between **active** and **passive** depends on what you want to **focus** on.", "Explanation"),
      table("Passive forms", ["Tense", "Form", "Example"], [
        ["Present Perfect", "has / have been + past participle", "The new bridge has been built."],
        ["will (future)", "will be + past participle", "The results will be published next week."],
        ["Present Simple", "am / is / are + past participle", "The shop is opened at nine."],
        ["Past Simple", "was / were + past participle", "The shop was opened in 2010."],
      ]),
      list("Active or passive?", ["**Active** — the doer is important or known: The mayor opened the bridge.", "**Passive** — the object or result is important, or the doer is unknown: The bridge was opened yesterday.", "Use the passive in news, reports and descriptions of processes."]),
      structure("Structure", "has / have been + participle · will be + participle", "In passive questions the auxiliary comes first: Has the bridge been built? Will the book be published?"),
    ],
    exercises: [
      fill("The results ___ (publish) next week.", ["will be published"], "Future passive: will be + participle."),
      fill("The new stadium ___ (build) — it is finished.", ["has been built"], "Present Perfect passive: has been built."),
      mist("Find the mistake.", ["The house", "has been build", "by a local company."], 1, "has been built", "Past participle: built."),
      mc("Which sentence puts the focus on the result and not on the doer?", ["A company has built a new bridge.", "A new bridge has been built.", "They have built a new bridge."], 1, "The passive focuses on the bridge."),
      order("Put the words in the correct order.", ["Has", "the", "book", "been", "published", "yet?"], "word", "Has + subject + been + participle."),
      match("Which is the correct form?", [["Present Perfect", "has been done"], ["future", "will be done"], ["Past Simple", "was done"], ["Present Simple", "is done"]], "Each tense has its own passive form."),
    ],
  },
  {
    slug: "pre-int-vocab-compound-nouns-collocations",
    level: "PRE_INTERMEDIATE", category: "VOCABULARY", title: "Compound Nouns and Adverb + Adjective Collocations", topic: "Word partners",
    difficulty: "CORE", minutes: 14, prereq: ["pre-int-vocab-feelings-adjectives"],
    objective: "Use noun + noun compounds and natural adverb + adjective pairs.",
    tags: ["vocabulary", "compound-nouns", "collocations", "adverbs", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Vocabulary", topic: "Compound nouns; adverb + adjective (Unit 10)" },
    sections: [
      text("**Compound nouns** are made of **two nouns** (business card). **Adverb + adjective** collocations are natural pairs (well-known, badly behaved). Learn each as **one unit**."),
      table("Compound nouns", ["Compound", "Meaning"], [
        ["business card", "a small card with your name and job"], ["phone number", "the digits you dial to call someone"], ["computer virus", "a harmful program"],
        ["traffic jam", "a long line of slow cars"], ["bus ticket", "a paper or e-ticket to travel by bus"], ["credit card", "a card for paying now and paying later"],
      ]),
      table("Adverb + adjective", ["Collocation", "Example"], [
        ["well-known", "a well-known singer"], ["badly behaved", "a badly behaved child"], ["highly successful", "a highly successful company"],
        ["deeply worried", "She was deeply worried."], ["fully booked", "The hotel is fully booked."], ["seriously ill", "He is seriously ill."],
      ]),
      tip("Some compounds are one word (toothpaste, newspaper), some two (bus stop), some hyphenated (well-known). Check a dictionary.", "Spelling"),
    ],
    exercises: [
      match("Match the two parts.", [["business", "card"], ["phone", "number"], ["computer", "virus"], ["traffic", "jam"]], "These compound nouns are made from two nouns."),
      match("Match the adverb and adjective.", [["highly", "successful"], ["fully", "booked"], ["deeply", "worried"], ["seriously", "ill"]], "These pairs sound natural."),
      fill("The hotel is ___ booked. There are no rooms.", ["fully"], "fully booked."),
      mist("Find the mistake.", ["She is a", "well-known", "actress and very hardly successful."], 1, "(replace 'very hardly' with 'highly')", "The natural collocation is highly successful."),
      mc("A long line of slow cars on the road is a ___.", ["traffic jam", "phone number", "credit card"], 0, "A traffic jam = slow cars in a line."),
      sa("A small card with your name and job is a business ___.", ["card"], "business card.", { hint: "c _ _ d" }),
    ],
  },
  {
    slug: "pre-int-reading-famous-names",
    level: "PRE_INTERMEDIATE", category: "READING", title: "Reading: Two Success Stories", topic: "Dates and passives",
    difficulty: "CORE", minutes: 16, prereq: ["pre-int-reading-bus-story"],
    objective: "Extract dates and facts from informative texts that use the passive.",
    tags: ["reading", "reading-scanning", "reading-details", "passive-voice", "dates", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Reading", topic: "History of a club and a brand (Unit 10)" },
    sections: [
      text("Informative texts about **brands and organisations** use **dates** and **passive verbs** (was founded, is made, will be launched). To find facts quickly, **scan for numbers**, then read the sentence to see **what happened** in that year.", "Reading strategy"),
      passage("Example", "The bakery was opened in 1998. Bread is baked every morning, and a new shop will be opened next month.", "Passive facts"),
      list("Guided practice", ["1998 → the bakery was opened.", "Every morning → bread is baked.", "Next month → a new shop will be opened."]),
    ],
    exercises: [
      mc("When was Salalah Stars founded?", ["1965", "1982", "1984"], 0, "“founded in 1965 by a group of schoolteachers”.", FAMOUS_NAMES),
      mc("Who founded the club?", ["a group of schoolteachers", "the government", "a famous player"], 0, "“founded … by a group of schoolteachers”.", FAMOUS_NAMES),
      mc("When was the first national trophy won?", ["1982", "1984", "2005"], 1, "A stadium was built in 1982, and the trophy was won two years later: 1984.", FAMOUS_NAMES),
      mc("What is Dhofar Gold made from?", ["frankincense", "roses", "sandalwood"], 0, "“it is made from frankincense”.", FAMOUS_NAMES),
      tf("Dhofar Gold was exported to Europe in 1990.", false, "It was created in 1990; it was exported to Europe in 2005.", FAMOUS_NAMES),
      ms("Select TWO things that will happen in the future.", ["A museum will be opened next to the stadium.", "The club was founded.", "A new range of perfume will be launched.", "Shirts are sold every year."], [0, 2], "Look for will be + participle.", FAMOUS_NAMES),
    ],
  },
  {
    slug: "pre-int-writing-discursive-essay",
    level: "PRE_INTERMEDIATE", category: "WRITING", title: "Discursive Essay: Advantages and Disadvantages", topic: "Essay writing",
    difficulty: "CHALLENGING", minutes: 20, prereq: ["pre-int-writing-book-film-review"],
    objective: "Write a balanced discursive essay that presents advantages and disadvantages, with linkers and a conclusion.",
    tags: ["writing", "essay", "writing-paragraph", "linkers", "argument", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Writing", topic: "Discursive essay: pros and cons (Unit 10)" },
    sections: [
      text("A **discursive essay** discusses a topic from **different sides**. A balanced essay presents the **advantages** and the **disadvantages** and ends with a **reasoned conclusion**. The style is **formal**: no short forms and no slang.", "Explanation"),
      table("Essay structure", ["Paragraph", "Content", "Useful language"], [
        ["1 Introduction", "introduce the topic and state the question", "Nowadays, many people … This essay will consider…"],
        ["2 Advantages", "two or three benefits with examples", "First of all, … Furthermore, … For example, …"],
        ["3 Disadvantages", "two or three drawbacks with examples", "On the other hand, … However, … Another problem is …"],
        ["4 Conclusion", "summarise and give your opinion", "In conclusion, … On balance, … "],
      ]),
      annotated("Model essay: Should students study abroad?", [
        ["Introduction", "Nowadays, many students choose to study abroad. This essay will consider the advantages and disadvantages of this decision."],
        ["Advantages", "First of all, studying abroad improves a student's language skills. Furthermore, it gives them the chance to meet people from different cultures."],
        ["Disadvantages", "On the other hand, it can be very expensive. Another problem is that some students feel homesick."],
        ["Conclusion", "In conclusion, although studying abroad has some disadvantages, I believe that the benefits are greater."],
      ]),
      tip("Use linkers to guide the reader: First of all → Furthermore → On the other hand → In conclusion.", "Linkers"),
    ],
    exercises: [
      order("Put the sentences in the correct order.", ["Nowadays, many students choose to study abroad.", "First of all, it improves their language skills.", "On the other hand, it can be very expensive.", "In conclusion, I believe that the benefits are greater."], "paragraph", "Introduction, advantage, disadvantage, conclusion."),
      match("Which linker?", [["adds another advantage", "Furthermore,"], ["introduces a disadvantage", "On the other hand,"], ["begins the conclusion", "In conclusion,"], ["begins the first point", "First of all,"]], "Learn the job of each linker."),
      mc("Which sentence is suitable for a formal essay?", ["It's a total nightmare.", "It can be very expensive.", "It costs loads."], 1, "Formal essays avoid slang."),
      mist("Find the mistake. (formal essay)", ["Studying abroad", "isn't", "always easy."], 1, "is not", "Formal writing avoids short forms."),
      order("Put the words in the correct order.", ["On", "the", "other", "hand,", "it", "can", "be", "expensive."], "word", "On the other hand, + clause."),
      mc("What should the conclusion do?", ["summarise the main points and give an opinion", "introduce a new topic", "repeat the introduction word for word"], 0, "A conclusion summarises and gives a reasoned opinion."),
    ],
  },

  // ============================================================ UNIT 11
  {
    slug: "pre-int-grammar-present-perfect-continuous",
    level: "PRE_INTERMEDIATE", category: "GRAMMAR", title: "Present Perfect Continuous", topic: "Present Perfect",
    difficulty: "CORE", minutes: 14, prereq: ["pre-int-grammar-passive-perfect-will"],
    objective: "Use have / has been + -ing for actions that started in the past and continue now, and for recent activities with a present result.",
    tags: ["grammar", "present-perfect-continuous", "tenses", "duration", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Grammar", topic: "Present Perfect Continuous (Unit 11)" },
    sections: [
      text("The **Present Perfect Continuous** focuses on an **activity** (not its result). It is used for actions that **started in the past and are still going on**, or that **finished recently and have a result now**.", "Explanation"),
      table("Forms", ["Type", "Form", "Example"], [
        ["Positive", "have / has been + verb-ing", "I've been studying for two hours."],
        ["Negative", "haven't / hasn't been + verb-ing", "She hasn't been feeling well."],
        ["Question", "Have / Has + subject + been + verb-ing?", "How long have you been waiting?"],
      ]),
      list("When do we use it?", ["Activity still continuing: I've been learning English since 2020.", "Recent activity with a visible result: Your eyes are red. Have you been crying?", "With for and since: for ten minutes, since morning."]),
      structure("Structure", "subject + have / has + been + verb-ing (+ for / since …)", "State verbs (know, want, like) are not used in the continuous: I've known him for years. (not I've been knowing)"),
    ],
    exercises: [
      fill("How long ___ you ___ (wait)?", ["have", "been waiting"], "How long have you been waiting?"),
      fill("She ___ (study) English since 2020.", ["has been studying"], "Present Perfect Continuous + since."),
      mist("Find the mistake.", ["I", "have been knowing", "him for years."], 1, "have known", "Know is a state verb: I have known him."),
      mc("Your clothes are dirty. What ___ you ___?", ["have / been doing", "did / do", "are / doing"], 0, "A recent activity with a visible result."),
      order("Put the words in the correct order.", ["It", "has", "been", "raining", "since", "morning."], "word", "has been + verb-ing + since + time."),
      sa("Make it negative: She has been feeling well. → She ___ well.", ["hasn't been feeling", "has not been feeling"], "Negative: hasn't been feeling.", { hint: "hasn't …" }),
    ],
  },
  {
    slug: "pre-int-grammar-pp-simple-vs-continuous",
    level: "PRE_INTERMEDIATE", category: "GRAMMAR", title: "Present Perfect Simple or Continuous?", topic: "Present Perfect",
    difficulty: "CHALLENGING", minutes: 14, prereq: ["pre-int-grammar-present-perfect-continuous"],
    objective: "Choose between the Present Perfect Simple (result, quantity, completion) and Continuous (activity, duration).",
    tags: ["grammar", "present-perfect", "present-perfect-continuous", "tenses", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Grammar", topic: "Present Perfect Simple vs Continuous (Unit 11)" },
    sections: [
      text("Both tenses connect the past with now, but they **focus** on different things. The **Simple** focuses on the **result, completion or number**. The **Continuous** focuses on the **activity and how long**.", "Explanation"),
      table("Simple or Continuous?", ["Focus", "Present Perfect Simple", "Present Perfect Continuous"], [
        ["Meaning", "completed action, result, number", "activity, duration, still in progress"],
        ["Question", "How many / How much?", "How long?"],
        ["Example", "I've written five emails.", "I've been writing emails all morning."],
        ["Example", "She has read three books this month.", "She has been reading a lot lately."],
      ]),
      list("Rules of thumb", ["**How many / how much** → Simple: I've read three chapters.", "**How long** → Continuous: I've been reading for two hours.", "**State verbs** → Simple only: I've known her for years.", "**Finished result** → Simple: I've painted the room. **Activity (not finished)** → Continuous: I've been painting the room."]),
    ],
    exercises: [
      mc("I ___ ten emails this morning.", ["have written", "have been writing"], 0, "A number (ten): Present Perfect Simple."),
      mc("She ___ for two hours and she is still working.", ["has worked", "has been working"], 1, "Duration and still in progress: Continuous."),
      match("Simple or continuous?", [["How many pages have you read?", "Simple"], ["How long have you been reading?", "Continuous"], ["I've finished my homework.", "Simple"], ["I've been studying all evening.", "Continuous"]], "Number / result = Simple; duration / activity = Continuous."),
      mist("Find the mistake.", ["I", "have been knowing", "her since 2015."], 1, "have known", "Know is a state verb."),
      fill("How many cups of coffee ___ you ___ (drink) today?", ["have", "drunk"], "A number: Present Perfect Simple: have drunk."),
      order("Put the words in the correct order.", ["How", "long", "have", "you", "been", "waiting?"], "word", "How long + have + subject + been + verb-ing."),
    ],
  },
  {
    slug: "pre-int-vocab-life-milestones",
    level: "PRE_INTERMEDIATE", category: "VOCABULARY", title: "Life Milestones", topic: "Life events",
    difficulty: "CORE", minutes: 12, prereq: ["pre-int-vocab-compound-nouns-collocations"],
    objective: "Talk about the stages and major events of a person's life with the right verbs and nouns.",
    tags: ["vocabulary", "life-events", "biography", "listening-support", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Vocabulary", topic: "Life events (Unit 11)" },
    sections: [
      text("Life has **stages** and **events**. Each event has a noun (a wedding) and a verb (get married). Use them to talk about **your life** or someone else's **biography**."),
      table("Life events: noun and verb", ["Event", "Verb phrase", "Example"], [
        ["birth", "be born", "I was born in 1999."],
        ["childhood", "grow up", "She grew up in a small village."],
        ["university", "go to / graduate from university", "He graduated from university in 2022."],
        ["engagement", "get engaged", "They got engaged last summer."],
        ["marriage", "get married", "They got married in June."],
        ["divorce", "get divorced", "His parents got divorced."],
        ["retirement", "retire", "My father retires next year."],
        ["death", "die", "He died in 2010."],
      ]),
      tip("We say be born (passive): I was born in Muscat. NOT I born.", "Grammar note"),
    ],
    exercises: [
      order("Put the life stages in order.", ["birth", "childhood", "university", "marriage", "retirement"], "word", "The usual order of life stages."),
      match("Noun → verb phrase.", [["marriage", "get married"], ["retirement", "retire"], ["birth", "be born"], ["engagement", "get engaged"]], "Each life event has a verb phrase."),
      mist("Find the mistake.", ["I", "born", "in Sohar in 1995."], 1, "was born", "We say I was born."),
      fill("She ___ up in a small village near Nizwa.", ["grew"], "grow up → grew up."),
      mc("After he ___ from university, he got a job.", ["graduated", "retired", "married"], 0, "graduate from university."),
      sa("The event when a person stops working because of age is ___.", ["retirement"], "retirement.", { hint: "r _ _ _ _ _ _ _ _ t" }),
    ],
  },
  {
    slug: "pre-int-reading-collectors",
    level: "PRE_INTERMEDIATE", category: "READING", title: "Reading: The Collectors", topic: "Numbers and motivation",
    difficulty: "CORE", minutes: 16, prereq: ["pre-int-reading-famous-names"],
    objective: "Scan for numerical records, understand motivation and work out unknown words from context.",
    tags: ["reading", "reading-scanning", "reading-vocabulary-context", "present-perfect", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Reading", topic: "People with a passion (Unit 11)" },
    sections: [
      text("Texts about **hobbies and passions** are full of **numbers** (how many, how long) and **personal reasons**. Scan for numbers first. Then look for **quotations**: people often explain **why** they do what they do.", "Reading strategy"),
      passage("Example", "Hana has been collecting coins since she was seven. She has 500 coins now. “Each coin tells a story,” she says.", "A short profile"),
      list("Guided practice", ["How long? → since she was seven.", "How many? → 500 coins.", "Motivation? → “Each coin tells a story.”"]),
    ],
    exercises: [
      mc("How many stamps does Maryam own?", ["about 90", "more than 12,000", "300"], 1, "“more than 12,000 stamps”.", COLLECTORS),
      mc("How long has Ali been looking for a golden teapot?", ["twenty years", "ten years", "three weeks"], 1, "“for ten years”.", COLLECTORS),
      sa("How many models has Sami finished this year? (write a number)", ["45", "forty-five"], "“He has finished 45 models this year”.", { context: COLLECTORS }),
      mc("In the text, “given up” means…", ["stopped trying", "started to collect", "found something"], 0, "“I haven't found it yet, but I haven't given up” = I have not stopped looking.", COLLECTORS),
      tf("Sami started building model cars when he was a child.", false, "“since he retired”.", COLLECTORS),
      mc("Why does the text use “has been collecting” for Maryam?", ["The activity started in the past and continues now.", "The activity is finished.", "It is a future plan."], 0, "Present Perfect Continuous for an ongoing activity.", COLLECTORS),
    ],
  },
  {
    slug: "pre-int-writing-notes-summary",
    level: "PRE_INTERMEDIATE", category: "WRITING", title: "Note-Taking and Summary Writing", topic: "Summary",
    difficulty: "CHALLENGING", minutes: 20, prereq: ["pre-int-writing-discursive-essay"],
    objective: "Take notes from a text and use them to write a concise summary in your own words.",
    tags: ["writing", "summary", "note-taking", "paraphrasing", "study-skills", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Writing", topic: "Note-taking and summary (Unit 11)" },
    sections: [
      text("A **summary** is a **short version** of a longer text that contains only the **main ideas**, written in **your own words**. The best method is to **read, take notes, then write from your notes** (not from the text).", "Explanation"),
      list("Five steps", ["1. **Read** the whole text and find the main idea.", "2. **Underline** key words and facts (not every detail).", "3. **Write notes** as bullet points or a mind map (key words only).", "4. **Write** the summary from your notes, in complete sentences and your own words.", "5. **Check**: main ideas included? Own words? Right length?"]),
      passage("Original text (about 60 words)", "Many people in Oman are interested in growing dates. Date palms need a lot of water and heat, and farmers look after them carefully. Dates are harvested in summer, and they are eaten fresh or dried. Dates are also exported to many countries, so they help the country's economy.", "A short text"),
      table("Notes → summary", ["Notes", "Summary"], [
        ["Dates: popular in Oman · palms need water + heat · harvest: summer · eaten fresh / dried · exported → economy", "Dates are a popular crop in Oman. The palms need plenty of water and heat, and the fruit is harvested in summer. Dates are eaten fresh or dried, and because they are exported, they support the economy."],
      ]),
      tip("Do not copy sentences. Change the words and the structure, but keep the meaning.", "Paraphrase"),
    ],
    exercises: [
      order("Put the steps of summary writing in order.", ["Read the text and find the main idea.", "Underline the key words.", "Write notes in bullet points.", "Write the summary from your notes."], "paragraph", "Read → underline → notes → write."),
      mc("Which is the BEST set of notes for “Date palms need a lot of water and heat, and farmers look after them carefully”?", ["palms: water + heat; farmers: careful", "Date palms need a lot of water and heat and farmers look after them carefully", "dates"], 0, "Notes use key words only."),
      mc("Which sentence is a good paraphrase of “Dates are harvested in summer”?", ["The fruit is picked in the summer months.", "Dates are harvested in summer.", "Summer dates."], 0, "It keeps the meaning but uses different words."),
      mist("Find the mistake. (a summary)", ["Dates are a popular crop.", "Many people in Oman are interested in growing dates,", "and they are exported."], 1, "(this is copied from the text)", "A summary should be in your own words, not copied."),
      order("Put the words in the correct order.", ["Dates", "are", "exported", "to", "many", "countries."], "word", "Subject + are + participle + to + place."),
      tf("A good summary includes every detail of the original text.", false, "A summary includes only the main ideas."),
    ],
  },

  // ============================================================ UNIT 12
  {
    slug: "pre-int-grammar-first-conditional-might",
    level: "PRE_INTERMEDIATE", category: "GRAMMAR", title: "First Conditional and might", topic: "Conditionals",
    difficulty: "CORE", minutes: 14, prereq: ["pre-int-grammar-pp-simple-vs-continuous"],
    objective: "Talk about real future possibilities with the first conditional, and express possibility with might.",
    tags: ["grammar", "conditionals", "first-conditional", "might", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Grammar", topic: "First conditional; might (Unit 12)" },
    sections: [
      text("The **first conditional** talks about a **real or likely future situation** and its **result**. **If + Present Simple**, **will + base verb**. Use **might** when the result is only **possible**.", "Explanation"),
      table("First conditional", ["Part", "Form", "Example"], [
        ["if-clause", "If + Present Simple", "If it rains tomorrow,"],
        ["result", "will + base verb", "we will stay at home."],
        ["possibility", "might + base verb", "If you study, you might pass the exam."],
        ["reversed order", "will + verb + if + Present Simple", "We'll stay at home if it rains."],
      ]),
      structure("Structure", "If + Present Simple, will / won't / might + verb", "Never use will in the if-clause: If I will see him… is wrong. Use unless = if … not: Unless you hurry, you'll be late."),
      examples("Examples", { will: ["If you don't hurry, you'll miss the train."], might: ["If it's sunny, we might go to the beach."], unless: ["Unless you leave now, you'll be late."] }),
    ],
    exercises: [
      mc("If it ___ tomorrow, we will stay at home.", ["rains", "will rain", "rained"], 0, "Present Simple in the if-clause."),
      fill("If you don't hurry, you ___ (miss) the train.", ["will miss"], "Result: will + base verb."),
      mist("Find the mistake.", ["If I", "will see", "him, I will tell him."], 1, "see", "No will in the if-clause."),
      mc("If it's sunny, we ___ go to the beach. (it's possible, not sure)", ["will", "might", "would"], 1, "Possibility: might."),
      order("Put the words in the correct order.", ["If", "you", "study,", "you", "will", "pass", "the", "exam."], "word", "If + Present Simple, will + verb."),
      sa("Complete with unless: ___ you leave now, you'll be late.", ["Unless"], "Unless = if … not.", { hint: "U…" }),
    ],
  },
  {
    slug: "pre-int-grammar-second-conditional",
    level: "PRE_INTERMEDIATE", category: "GRAMMAR", title: "Second Conditional", topic: "Conditionals",
    difficulty: "CHALLENGING", minutes: 14, prereq: ["pre-int-grammar-first-conditional-might"],
    objective: "Talk about hypothetical, unreal or improbable situations with if + Past Simple, would + verb.",
    tags: ["grammar", "conditionals", "second-conditional", "hypothetical", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Grammar", topic: "Second conditional (Unit 12)" },
    sections: [
      text("The **second conditional** talks about **unreal, imaginary or improbable** situations in the present or future. **If + Past Simple**, **would + base verb**. The **Past Simple** here doesn't refer to past time: it shows the situation is **not real**.", "Explanation"),
      table("First and second conditional", ["Feature", "First conditional", "Second conditional"], [
        ["Meaning", "real, likely", "unreal, improbable"],
        ["Form", "If + Present Simple, will + verb", "If + Past Simple, would + verb"],
        ["Example", "If I win, I'll buy a car.", "If I won the lottery, I would buy an island."],
      ]),
      list("Use it for", ["Imaginary situations: If I were a bird, I would fly to the mountains.", "Unlikely situations: If I had a million rials, I would travel the world.", "Advice: If I were you, I would talk to him."]),
      structure("Structure", "If + Past Simple, would / wouldn't + base verb", "With I / he / she / it we often use were: If I were you… (was is also possible in informal English)."),
    ],
    exercises: [
      mc("If I ___ a million rials, I would travel the world.", ["have", "had", "will have"], 1, "Past Simple in the if-clause."),
      fill("If she ___ (be) taller, she would join the basketball team.", [["were", "was"]], "were (or was) in second conditional."),
      mist("Find the mistake.", ["If I", "would have", "more time, I would learn Chinese."], 1, "had", "No would in the if-clause: If I had…"),
      match("Which conditional?", [["If it rains, we'll stay in.", "first (real)"], ["If I were you, I'd stay in.", "second (unreal / advice)"], ["If I won the lottery, I'd travel.", "second (improbable)"]], "Real = first; unreal = second."),
      order("Put the words in the correct order.", ["If", "I", "were", "you,", "I", "would", "talk", "to", "him."], "word", "If I were you, I would …"),
      sa("Complete: If I had a car, I ___ (drive) to work.", ["would drive"], "would + base verb.", { hint: "would …" }),
    ],
  },
  {
    slug: "pre-int-vocab-bring-take-come-go",
    level: "PRE_INTERMEDIATE", category: "VOCABULARY", title: "bring / take and come / go", topic: "Movement verbs",
    difficulty: "CORE", minutes: 12, prereq: ["pre-int-vocab-life-milestones"],
    objective: "Choose between bring and take, and between come and go, according to the direction of movement.",
    tags: ["vocabulary", "movement-verbs", "bring-take", "come-go", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Vocabulary", topic: "bring / take; come / go (Unit 12)" },
    sections: [
      text("These verbs depend on the **direction of the movement**, relative to **where the speaker is** (or the place we are talking about)."),
      table("Direction", ["Verb", "Meaning", "Example"], [
        ["bring", "carry something TOWARDS the speaker / the place we are talking about", "Please bring your books to my house."],
        ["take", "carry something AWAY from the speaker / to another place", "Take your books to the library."],
        ["come", "move TOWARDS the speaker / the place we are talking about", "Come to my party!"],
        ["go", "move AWAY from the speaker / to another place", "I'm going to the market."],
      ]),
      tip("Memory: bring and come → towards here. take and go → away from here.", "Trick"),
    ],
    exercises: [
      match("bring or take?", [["Please ___ your ID to the exam (we are at the exam centre).", "bring"], ["Don't forget to ___ your umbrella when you leave.", "take"], ["Can you ___ me a glass of water?", "bring"]], "Bring = towards; take = away."),
      mc("“Are you ___ to Sara's party?” (you and I are not there)", ["coming", "going"], 1, "Away from here: going."),
      mc("Can you ___ this letter to the post office on your way home?", ["bring", "take"], 1, "To another place: take."),
      mist("Find the mistake.", ["Please", "take", "your book to me tomorrow."], 1, "bring", "Towards the speaker: bring."),
      fill("Would you like to ___ to my house for dinner? (towards the speaker)", ["come"], "Towards the speaker: come."),
      sa("If you visit me, remember to ___ your passport. (to my place)", ["bring"], "Towards me: bring.", { hint: "b _ _ _ g" }),
    ],
  },
  {
    slug: "pre-int-vocab-prepositional-combinations",
    level: "PRE_INTERMEDIATE", category: "VOCABULARY", title: "Prepositional Combinations", topic: "Prepositions",
    difficulty: "CORE", minutes: 14, prereq: ["pre-int-vocab-bring-take-come-go"],
    objective: "Use fixed combinations: verb + preposition, preposition + noun and adjective + preposition.",
    tags: ["vocabulary", "prepositions", "collocations", "A2", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Vocabulary", topic: "Prepositional combinations (Unit 12)" },
    sections: [
      text("Many English words need a **fixed preposition**. There is no rule, so learn each one **with its partner**. Three groups are especially common."),
      table("Three groups", ["Group", "Examples"], [
        ["Verb + preposition", "listen to · wait for · depend on · look at · apologise for · ask for"],
        ["Preposition + noun", "by car · on holiday · in trouble · at work · on time · in a hurry · by mistake"],
        ["Adjective + preposition", "afraid of · proud of · good at · married to · similar to · tired of"],
      ]),
      compare("Common mistakes", [["I'm waiting the bus.", "I'm waiting for the bus.", "wait for."], ["I go to work with car.", "I go to work by car.", "by + transport."], ["She is married with a doctor.", "She is married to a doctor.", "married to."]]),
    ],
    exercises: [
      fill("I'm waiting ___ the bus.", ["for"], "wait for."),
      fill("We travelled ___ car.", ["by"], "by car."),
      fill("She is proud ___ her son.", ["of"], "proud of."),
      mist("Find the mistake.", ["He", "depends of", "his parents."], 1, "depends on", "depend on."),
      match("Match the word with its preposition.", [["listen", "to"], ["married", "to"], ["afraid", "of"], ["look", "at"]], "Learn the pair together."),
      mc("They are on ___ in Turkey this month.", ["holiday", "the holiday", "a holiday time"], 0, "on holiday."),
    ],
  },
  {
    slug: "pre-int-reading-risk-chance",
    level: "PRE_INTERMEDIATE", category: "READING", title: "Reading: Risk and Chance", topic: "Critical reading",
    difficulty: "CHALLENGING", minutes: 18, prereq: ["pre-int-reading-collectors"],
    objective: "Follow an argument about probability, and tell facts from opinions and examples from claims.",
    tags: ["reading", "reading-inference", "critical-thinking", "argument", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Reading", topic: "Risk and chance (Unit 12)" },
    sections: [
      text("An **argument text** has a **claim** (the writer's main idea), **examples** that support it, and a **conclusion**. To read critically, ask: **What is the claim? What is the evidence? Does the example really prove the claim?**", "Reading strategy"),
      passage("Example", "Many people are afraid of sharks, but you are more likely to be hurt by a falling coconut. We often fear the unusual and ignore the ordinary.", "Claim and example"),
      list("Guided practice", ["Claim: we fear unusual dangers and ignore ordinary ones.", "Example: sharks vs. a falling coconut.", "Reaction: the example makes the claim more convincing."]),
    ],
    exercises: [
      mc("What does the writer say about people?", ["They are often bad at judging risk.", "They never take risks.", "They always make good decisions."], 0, "“people are often bad at judging risk”.", CHANCE),
      mc("Which unusual event do people worry about?", ["a plane crash", "crossing a busy road", "the weather"], 0, "“We worry about unusual events, such as a plane crash”.", CHANCE),
      mc("What is an everyday danger that people forget?", ["crossing a busy road", "flying", "a coin toss"], 0, "“crossing a busy road”.", CHANCE),
      tf("Getting heads seven times in ten coin tosses is very strange.", false, "“that isn't strange at all”.", CHANCE),
      mc("What is the writer's conclusion?", ["Understanding chance helps us make better decisions.", "Nobody can understand chance.", "Risk should always be avoided."], 0, "The last sentence.", CHANCE),
      mc("What does the birthday example show?", ["Coincidences can be more likely than they seem.", "Birthdays are always on the same day.", "Twenty-three is a lucky number."], 0, "“even though it seems unlikely”.", CHANCE),
    ],
  },
  {
    slug: "pre-int-writing-editing-proofreading",
    level: "PRE_INTERMEDIATE", category: "WRITING", title: "Editing and Proofreading", topic: "Correction",
    difficulty: "CHALLENGING", minutes: 20, prereq: ["pre-int-writing-notes-summary"],
    objective: "Find and correct common mistakes in grammar, spelling, punctuation and structure in a draft text.",
    tags: ["writing", "editing", "proofreading", "error-correction", "B1"],
    ref: { book: HW, level: "Pre-Intermediate", area: "Writing", topic: "Editing and proofreading (Unit 12)" },
    sections: [
      text("**Editing** is improving your text: ideas, order and style. **Proofreading** is the last check for **small mistakes**. Always **read your work aloud, slowly, and more than once**, checking one type of error each time.", "Explanation"),
      table("Common errors to check", ["Type", "Mistake", "Correction"], [
        ["Subject–verb agreement", "She go to school.", "She goes to school."],
        ["Tense", "Yesterday I go to the market.", "Yesterday I went to the market."],
        ["Word order", "I bought yesterday a book.", "I bought a book yesterday."],
        ["Articles", "He is engineer.", "He is an engineer."],
        ["Spelling", "recieve · definately", "receive · definitely"],
        ["Punctuation", "i like coffee but she doesnt", "I like coffee, but she doesn't."],
      ]),
      list("Checklist", ["Does every sentence have a subject and a verb?", "Do verbs agree with their subjects and use the correct tense?", "Are capital letters and full stops in the right places?", "Are the ideas in a logical order and joined with linking words?", "Is the spelling correct? (check words you are not sure about)"]),
      passage("A draft to correct", "yesterday i go to the market with my sister. we buyed some fruit and vegetable. she is teacher and she know a lot about food.", "Draft"),
      passage("Edited version", "Yesterday I went to the market with my sister. We bought some fruit and vegetables. She is a teacher, and she knows a lot about food.", "After editing"),
    ],
    exercises: [
      sa("Correct the sentence: She go to school every day.", ["She goes to school every day.", "She goes to school every day"], "Third person singular: goes.", { hint: "She goes …" }),
      mist("Find the mistake.", ["We", "buyed", "some fruit yesterday."], 1, "bought", "Buy is irregular: bought."),
      mist("Find the mistake.", ["He is", "engineer", "in a big company."], 1, "an engineer", "A job needs an article: an engineer."),
      mc("Which is the correct sentence?", ["I like coffee but she doesnt.", "I like coffee, but she doesn't.", "i like coffee, but she doesnt."], 1, "Comma before but; apostrophe in doesn't; capital I."),
      order("Put the words in the correct order.", ["I", "bought", "a", "book", "yesterday."], "word", "Subject + verb + object + time."),
      match("Type of error?", [["She go to school.", "subject–verb agreement"], ["I bought yesterday a book.", "word order"], ["recieve", "spelling"], ["He is engineer.", "articles"]], "Name the kind of mistake."),
    ],
  },
];

void [annotated, compare, examples, ms, tip, vocab];
